"""Parity vectors for the browser twins of the targets and lab maths (ARCHITECTURE.md "Frontend modules").

``tests/data/targets_vectors.json`` (``app/targets.py``) and ``tests/data/kidney_function_vectors.json``
(``app/units.py`` + ``app/kidney_function.py``) are generated by ``tests/data/gen_targets_vectors.py`` and
``tests/data/gen_kidney_function_vectors.py`` and replayed against ``app/static/js/engine/targets.js`` and
``kidney_function.js`` by ``node tests/js/run_vectors.mjs``. These tests fail when a committed file no longer
matches the Python rules (regenerate it), and check that the vectors cover what they must.
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

from app import target_rules as R
from app import units

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "tests" / "data"


def _generator(name: str):
    spec = importlib.util.spec_from_file_location(name, DATA / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(
    "generator, filename, sources",
    [
        ("gen_targets_vectors", "targets_vectors.json", "app/targets.py or app/target_rules.py"),
        ("gen_kidney_function_vectors", "kidney_function_vectors.json", "app/units.py or app/kidney_function.py"),
    ],
)
def test_vectors_are_current(generator, filename, sources):
    committed = json.loads((DATA / filename).read_text(encoding="utf-8"))
    fresh = json.loads(json.dumps(_generator(generator).build()))  # the same JSON round trip as the file
    assert committed == fresh, (
        f"tests/data/{filename} is stale: {sources} changed. Run `python3 tests/data/{generator}.py`, then "
        "`node tests/js/run_vectors.mjs`, and update the browser twin until both agree."
    )


def test_targets_vectors_cover_the_whole_catalogue():
    doc = json.loads((DATA / "targets_vectors.json").read_text(encoding="utf-8"))
    ids = [c["id"] for c in doc["cases"]]
    assert ids[:23] == [f"TV{n:02d}" for n in range(1, 24)] and len(set(ids)) == len(ids)
    used = {key for c in doc["cases"] if "rules" in c["expect"] for key in c["expect"]["rules"]}
    refusals = {c["expect"]["error"]["code"] for c in doc["cases"] if "error" in c["expect"]}
    # every rule that produces a target or a note is exercised; S-* by the refusals; G-1 lives in the card vectors
    assert used == set(R.RULES) - {"S-1", "S-2", "S-3", "G-1"}
    assert refusals == set(R.REFUSALS)
    assert any("invalid" in c["expect"] for c in doc["cases"])
    assert {lvl for c in doc["cases"] if "alerts" in c["expect"] for lvl in (a["level"] for a in c["expect"]["alerts"])} == {"urgent", "emergency"}
    assert doc["tables"]["rules"] == json.loads(json.dumps(R.RULES)) and doc["tables"]["notes"] == R.NOTES
    assert {tuple(c["args"][1:3]) for c in doc["wrapper_cases"]} >= {("4", "none"), ("5", "hemodialysis")}


def test_kidney_function_vectors_cover_every_analyte_and_message():
    doc = json.loads((DATA / "kidney_function_vectors.json").read_text(encoding="utf-8"))
    assert [row["key"] for row in doc["unit_table"]] == list(units.ANALYTE_KEYS)
    converted = {(c["analyte"], c["expect"].get("entered_unit")) for c in doc["conversion_cases"] if "error" not in c["expect"]}
    for analyte in units.ANALYTE_KEYS:
        for unit in units.analyte_def(analyte).units:
            assert (analyte, unit) in converted, (analyte, unit)
    assert any("error" in c["expect"] for c in doc["conversion_cases"])
    assert {c["equation"] for c in doc["egfr_cases"]} == {"cr", "cr_cys", "cys"}
    methods = {c["expect"]["egfr"]["method"] for c in doc["assess_cases"] if c["expect"]["egfr"]}
    assert methods == {"lab", "ckd_epi_2021_cr_cys", "ckd_epi_2021_cr", "ckd_epi_2012_cys"}
    messages = " ".join(c["expect"]["message"] for c in doc["assess_cases"])
    for fragment in ("No creatinine", "not estimated on dialysis", "not estimated during pregnancy", "not estimated for people under 18",
                     "Add your birth month", "does not suggest one", "which is stage G3aT", "(female formula"):
        assert fragment in messages, fragment
