"""Content checks for the patient handbook (handbook/), per docs/dev/research/08-handbook-site.md §4.9.

Runs offline. Needs PyYAML (in handbook/requirements.lock); skipped where it is not installed.
Failures are rules a page must keep; ``warnings.warn`` marks the advisory checks (stale reviews,
reading level, wording), which show in the pytest summary without failing.
"""
from __future__ import annotations

import datetime as dt
import importlib.util
import re
import sys
import warnings
from pathlib import Path

import pytest

import yaml  # requirements-dev.lock and the handbook venv (a MkDocs dependency) both install PyYAML

ROOT = Path(__file__).resolve().parents[1]
HANDBOOK = ROOT / "handbook"
DOCS = HANDBOOK / "docs"
MKDOCS_YML = HANDBOOK / "mkdocs.yml"
SOURCES_YML = HANDBOOK / "sources.yml"
SLUGS_YML = HANDBOOK / "data" / "slugs.yml"
TOPICS_PY = ROOT / "app" / "guidance" / "topics.py"
NO_DOSING_INCLUDE = '--8<-- "includes/no-dosing.md"'
GENERATED_MARKER = "<!-- GENERATED by scripts/build_handbook.py; do not edit -->"

REQUIRED_KEYS = ("title", "description", "slug", "audience", "applies_to", "status", "reviewed_by",
                 "reviewed_on", "last_checked", "sources")
AUDIENCES = {"patient", "caregiver", "clinician", "app-user", "self-hoster"}
APPLIES_TO = {"G1-G2", "G3a", "G3b", "G4", "G5", "HD", "HHD", "PD", "Tx", "all"}
STATUSES = {"draft", "reviewed"}
MEDICAL_DIRS = ("ckd/", "stages/", "labs/", "eat/", "t1d/", "medicines/", "prepare/", "living/")
MEDICAL_PAGES = ("get-help-now.md",)
DOSE_DIRS = ("t1d/", "medicines/")
SOURCE_KINDS = {"guideline", "consensus", "study", "review", "patient-info", "government", "label", "data",
                "project", "tool"}

# Medicine names next to a milligram amount mean dosing. Hypo treatment (grams of carbohydrate) and
# nutrient milligrams (potassium, sodium, ...) are not medicines and are allowed.
DRUGS = (
    "insulin", "glargine", "detemir", "degludec", "lispro", "aspart", "glulisine", "glucagon",
    "finerenone", "kerendia", "lisinopril", "enalapril", "ramipril", "captopril", "losartan", "valsartan",
    "irbesartan", "candesartan", "telmisartan", "olmesartan", "spironolactone", "eplerenone",
    "empagliflozin", "dapagliflozin", "canagliflozin", "sotagliflozin", "ertugliflozin", "metformin",
    "semaglutide", "liraglutide", "dulaglutide", "tirzepatide", "ibuprofen", "naproxen", "aspirin",
    "acetaminophen", "paracetamol", "tacrolimus", "cyclosporine", "ciclosporin", "mycophenolate",
    "prednisone", "prednisolone", "sevelamer", "lanthanum", "calcium acetate", "cinacalcet", "patiromer",
    "zirconium", "epoetin", "darbepoetin", "trimethoprim", "furosemide", "torsemide", "bumetanide",
    "hydrochlorothiazide", "chlorthalidone", "sodium bicarbonate", "gabapentin", "pregabalin",
    "ropinirole", "pramipexole", "levothyroxine", "atorvastatin", "rosuvastatin",
)
DRUG_RE = "|".join(re.escape(d) for d in DRUGS)
MG_NEAR_DRUG = re.compile(rf"(?:\b(?:{DRUG_RE})\b[^.\n]{{0,40}}\b\d+(?:\.\d+)?\s*(?:mg|mcg|µg)\b)|"
                          rf"(?:\b\d+(?:\.\d+)?\s*(?:mg|mcg|µg)\b[^.\n]{{0,25}}\b(?:{DRUG_RE})\b)", re.I)
UNITS_IN_DOSE_DIRS = re.compile(r"\b\d+(?:\.\d+)?\s*(?:units?|U|IU)\b")
INSULIN_UNITS = re.compile(r"(?:\b\d+(?:\.\d+)?\s*(?:units?|U|IU)\b[^.\n]{0,40}\binsulin\b)|"
                           r"(?:\binsulin\b[^.\n]{0,40}\b\d+(?:\.\d+)?\s*(?:units?|U|IU)\b)", re.I)
TAKE_AMOUNT = re.compile(r"\btake\s+\d+(?:\.\d+)?\s*(?:mg|mcg|µg|micrograms?|milligrams?|units?|IU)\b", re.I)
DOSE_OK = "<!-- dose-ok:"
# "ESRD" is Medicare's legal term: allowed on the costs page, on pages that state the rule itself, and in
# the glossary, which must define the abbreviation people see on Medicare forms.
ESRD_OK = {"living/costs-and-benefits.md", "reference/sources.md", "reference/about.md",
           "reference/glossary.md", "self-hosting/building-the-handbook.md"}
# Slugs that cannot equal the file stem because the stem is already another page's slug.
SLUG_EXCEPTIONS = {"ckd/stages.md": "ckd-stages"}  # "stages" is stages/index.md

REF_LINK = re.compile(r"\]\[([^\]]+)\]")
FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)


# ----------------------------------------------------------------------------- helpers

class _Loader(yaml.SafeLoader):
    """Safe loader that tolerates MkDocs tags (!ENV, !relative) in mkdocs.yml."""


def _tag(loader, suffix, node):  # pragma: no cover - trivial
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node)
    return loader.construct_scalar(node)


_Loader.add_multi_constructor("!", _tag)


def _pages() -> list[Path]:
    return sorted(p for p in DOCS.rglob("*.md")
                  if not p.name.startswith("_") and "_drafts" not in p.parts)


def _rel(p: Path) -> str:
    return p.relative_to(DOCS).as_posix()


def _split(p: Path) -> tuple[dict, str]:
    text = p.read_text(encoding="utf-8")
    m = FRONT_MATTER.match(text)
    if not m:
        return {}, text
    return yaml.safe_load(m.group(1)) or {}, text[m.end():]


def _strip_code(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    return re.sub(r"`[^`\n]*`", "", text)


def _strip_comments(text: str) -> str:
    return re.sub(r"<!--.*?-->", "", text, flags=re.S)


def _cited(body: str) -> list[str]:
    return REF_LINK.findall(_strip_code(_strip_comments(body)))


def _sources() -> dict:
    data = yaml.safe_load(SOURCES_YML.read_text(encoding="utf-8"))
    return {str(k): v for k, v in data.items()}


def _is_medical(rel: str) -> bool:
    return rel.startswith(MEDICAL_DIRS) or rel in MEDICAL_PAGES


def _as_date(value):
    if isinstance(value, dt.date):
        return value
    if isinstance(value, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        return dt.date.fromisoformat(value)
    return None


def _nav_files(node) -> list[str]:
    out: list[str] = []
    if isinstance(node, str):
        out.append(node)
    elif isinstance(node, list):
        for item in node:
            out += _nav_files(item)
    elif isinstance(node, dict):
        for value in node.values():
            out += _nav_files(value)
    return out


def _load_build_script():
    spec = importlib.util.spec_from_file_location("build_handbook", ROOT / "scripts" / "build_handbook.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module  # dataclasses resolve annotations through sys.modules
    spec.loader.exec_module(module)
    return module


PAGES = _pages()
PAGE_IDS = [_rel(p) for p in PAGES]


# ----------------------------------------------------------------------------- front matter

@pytest.mark.parametrize("page", PAGES, ids=PAGE_IDS)
def test_front_matter_schema(page):
    meta, body = _split(page)
    rel = _rel(page)
    assert meta, f"{rel}: missing YAML front matter"
    missing = [k for k in REQUIRED_KEYS if k not in meta]
    assert not missing, f"{rel}: front matter is missing {missing}"
    assert isinstance(meta["title"], str) and meta["title"].strip(), f"{rel}: empty title"
    assert isinstance(meta["description"], str) and len(meta["description"]) >= 20, f"{rel}: description too short"
    assert re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", str(meta["slug"])), f"{rel}: slug must be kebab-case"
    assert isinstance(meta["audience"], list) and meta["audience"], f"{rel}: audience must be a non-empty list"
    assert set(meta["audience"]) <= AUDIENCES, f"{rel}: unknown audience {set(meta['audience']) - AUDIENCES}"
    assert isinstance(meta["applies_to"], list) and meta["applies_to"], f"{rel}: applies_to must be a list"
    assert set(meta["applies_to"]) <= APPLIES_TO, f"{rel}: unknown applies_to {set(meta['applies_to']) - APPLIES_TO}"
    assert meta["status"] in STATUSES, f"{rel}: status must be draft or reviewed"
    assert _as_date(meta["last_checked"]), f"{rel}: last_checked must be an ISO date"
    assert isinstance(meta["sources"], list), f"{rel}: sources must be a list"
    if meta["status"] == "reviewed":
        assert str(meta.get("reviewed_by") or "").strip(), f"{rel}: a reviewed page needs reviewed_by"
        assert _as_date(meta.get("reviewed_on")), f"{rel}: a reviewed page needs reviewed_on (ISO date)"
    elif meta.get("reviewed_on") not in (None, ""):
        assert _as_date(meta["reviewed_on"]), f"{rel}: reviewed_on must be an ISO date or null"
    if "figures_as_of" in meta:
        assert _as_date(meta["figures_as_of"]), f"{rel}: figures_as_of must be an ISO date"
    h1 = re.search(r"^# (.+)$", body, re.M)
    assert h1, f"{rel}: needs an H1 heading"


def test_slugs_are_unique():
    seen: dict[str, str] = {}
    for page in PAGES:
        meta, _ = _split(page)
        slug = str(meta.get("slug"))
        assert slug not in seen, f"slug {slug!r} is used by {seen.get(slug)} and {_rel(page)}"
        seen[slug] = _rel(page)
        expected = page.parent.name if page.name == "index.md" else page.stem
        if page == DOCS / "index.md":
            expected = "start-here"
        elif page.parent == DOCS / "eat" / "menus" and page.name != "index.md":
            expected = f"menu-{page.stem}"  # menu-g1-g2 vs the stage page g1-g2
        expected = SLUG_EXCEPTIONS.get(_rel(page), expected)
        if slug != expected:
            warnings.warn(f"{_rel(page)}: slug {slug!r} differs from the file name {expected!r}")


# ----------------------------------------------------------------------------- sources

def test_sources_yml_entries_are_complete():
    sources = _sources()
    assert len(sources) >= 50
    for sid, entry in sources.items():
        for key in ("cite", "url", "licence", "checked", "kind"):
            assert entry.get(key) not in (None, ""), f"sources.yml {sid}: missing {key}"
        assert str(entry["url"]).startswith("https://"), f"sources.yml {sid}: url must be https"
        for extra in entry.get("also", []) or []:
            assert str(extra).startswith("https://"), f"sources.yml {sid}: also-url must be https"
        assert _as_date(entry["checked"]), f"sources.yml {sid}: checked must be an ISO date"
        assert entry["kind"] in SOURCE_KINDS, f"sources.yml {sid}: unknown kind {entry['kind']}"


# Sources taken out of the bibliography because the work is gone. A page, the generator data or sources.yml must
# not bring one back; cite the replacement instead (handbook/REVIEW.md records each replacement).
RETIRED_SOURCES = {
    "DG47": "University of Michigan renal diet handout: medicine.umich.edu redirects to the medical school's home page "
            "(then 403) since 2026-10-05; cite SAT-labels (sodium per meal) and AKF-meal (potassium per meal)",
}


def test_retired_sources_stay_retired():
    sources = {k.lower() for k in _sources()}
    for sid, why in RETIRED_SOURCES.items():
        assert sid.lower() not in sources, f"sources.yml defines retired source {sid}: {why}"
    data = [HANDBOOK / "data" / name for name in ("recipes.yml", "menus.yml") if (HANDBOOK / "data" / name).exists()]
    for path in [*PAGES, *data, HANDBOOK / "includes" / "sources.md"]:
        text = path.read_text(encoding="utf-8")
        for sid, why in RETIRED_SOURCES.items():
            assert not re.search(rf"(?<![\w-]){re.escape(sid)}(?![\w-])", text), f"{path.relative_to(ROOT)} cites retired {sid}: {why}"


def test_recipe_review_lines_cite_the_sources_that_state_them():
    """The 600 mg per-meal line for recipes (scripts/build_handbook.py RECIPE_LIMITS) is the number the two sources
    give: Satellite Healthcare for sodium, AKF Kidney Kitchen for potassium (lower end of 600–700 mg)."""
    build = _load_build_script()
    meal = build.RECIPE_LIMITS["meal"]
    sources = _sources()
    assert meal["sodium_mg"] == 600 and "less than 600 mg per meal" in sources["SAT-labels"]["note"]
    assert meal["potassium_mg"] == 600 and "600-700mg of potassium per meal" in sources["AKF-meal"]["note"]
    recipes = yaml.safe_load((HANDBOOK / "data" / "recipes.yml").read_text(encoding="utf-8"))
    assert {"SAT-labels", "AKF-meal"} <= set(recipes["sources"])


@pytest.mark.parametrize("page", PAGES, ids=PAGE_IDS)
def test_every_cited_id_exists_and_is_listed(page):
    meta, body = _split(page)
    rel = _rel(page)
    known = {k.lower(): k for k in _sources()}
    listed = [str(s) for s in meta.get("sources") or []]
    for sid in listed:
        assert sid.lower() in known, f"{rel}: front matter cites unknown source id {sid!r}"
    cited = _cited(body)
    for sid in cited:
        assert sid.lower() in known, f"{rel}: body cites unknown source id [{sid}] (add it to handbook/sources.yml)"
    listed_lower = {s.lower() for s in listed}
    unlisted = sorted({s for s in cited if s.lower() not in listed_lower})
    assert not unlisted, f"{rel}: cited but not in front matter sources: {unlisted}"
    unused = sorted(set(listed) - {s for s in cited} - {known[s.lower()] for s in cited if s.lower() in known})
    if unused:
        warnings.warn(f"{rel}: listed in front matter but never cited: {unused}")


@pytest.mark.parametrize("page", [p for p in PAGES if _is_medical(_rel(p))],
                         ids=[r for r in PAGE_IDS if _is_medical(r)])
def test_medical_pages_have_three_sources(page):
    _, body = _split(page)
    rel = _rel(page)
    m = re.search(r"^## Sources\s*$(.*?)(?=^## |\Z)", body, re.M | re.S)
    assert m, f"{rel}: medical pages need a '## Sources' section"
    ids = {s.lower() for s in _cited(m.group(1))}
    assert len(ids) >= 3, f"{rel}: '## Sources' needs at least 3 reference links, found {sorted(ids)}"


def test_unused_sources_only_warn():
    sources = _sources()
    used = set()
    for page in PAGES:
        _, body = _split(page)
        used |= {s.lower() for s in _cited(body)}
    unused = sorted(sid for sid in sources if sid.lower() not in used)
    if unused:
        warnings.warn(f"{len(unused)} sources.yml ids are not cited yet: {', '.join(unused[:20])}…")


# ----------------------------------------------------------------------------- navigation

def test_every_page_is_in_nav_and_every_nav_entry_exists():
    config = yaml.load(MKDOCS_YML.read_text(encoding="utf-8"), Loader=_Loader)
    nav = _nav_files(config["nav"])
    assert len(nav) == len(set(nav)), "a page appears twice in nav"
    missing_files = [n for n in nav if not (DOCS / n).is_file()]
    assert not missing_files, f"nav entries without a file: {missing_files}"
    not_in_nav = sorted(set(PAGE_IDS) - set(nav))
    assert not not_in_nav, f"pages missing from nav in handbook/mkdocs.yml: {not_in_nav}"


def test_section_landing_pages_exist_for_every_plan_section():
    for folder in ("ckd", "stages", "labs", "eat", "t1d", "app", "self-hosting", "eat/menus", "eat/recipes"):
        assert (DOCS / folder / "index.md").is_file(), f"{folder}/index.md is missing"
    for page in ("index.md", "get-help-now.md", "reference/sources.md", "reference/about.md",
                 "reference/licences.md", "reference/glossary.md", "reference/units.md"):
        assert (DOCS / page).is_file(), f"{page} is missing"


# ----------------------------------------------------------------------------- app links

def test_slugs_used_by_the_app_exist():
    slugs = yaml.safe_load(SLUGS_YML.read_text(encoding="utf-8"))
    assert slugs, "handbook/data/slugs.yml is empty"
    by_slug = {}
    for page in PAGES:
        meta, _ = _split(page)
        by_slug[str(meta.get("slug"))] = page
    for slug, path in slugs.items():
        candidates = [DOCS / f"{path}.md", DOCS / path / "index.md"]
        page = next((c for c in candidates if c.is_file()), None)
        assert page, f"app slug {slug!r}: no page at handbook/docs/{path}.md or {path}/index.md"
        meta, _ = _split(page)
        assert meta.get("slug") == slug, f"app slug {slug!r}: {_rel(page)} has slug {meta.get('slug')!r}"


def test_app_topic_pages_point_at_existing_pages():
    """app/guidance/topics.py (note 06 TOPIC_PAGES) links to /learn/<path>/; every path must exist."""
    text = TOPICS_PY.read_text(encoding="utf-8")
    paths = re.findall(r"/learn/([a-z0-9/_-]+?)/?[\"']", text)
    for path in paths:
        if not path:
            continue
        ok = (DOCS / f"{path}.md").is_file() or (DOCS / path / "index.md").is_file()
        assert ok, f"app/guidance/topics.py links to /learn/{path}/ but there is no such handbook page"


# ----------------------------------------------------------------------------- privacy and CSP

@pytest.mark.parametrize("page", PAGES, ids=PAGE_IDS)
def test_no_scripts_iframes_inline_styles_or_external_media(page):
    _, body = _split(page)
    rel = _rel(page)
    text = _strip_code(body)
    assert not re.search(r"<script\b", text, re.I), f"{rel}: raw <script> is not allowed (CSP)"
    assert not re.search(r"<iframe\b", text, re.I), f"{rel}: <iframe> is not allowed"
    assert not re.search(r"\bstyle\s*=", text, re.I), f"{rel}: inline style= is not allowed (CSP)"
    assert not re.search(r"<link\b", text, re.I), f"{rel}: <link> tags are not allowed"
    assert not re.search(r"<(?:img|video|audio|source|embed|object)\b[^>]*\b(?:src|data)\s*=\s*[\"']?(?:https?:)?//", text, re.I), \
        f"{rel}: external media are not allowed (the LAN copy must load nothing from the internet)"
    assert not re.search(r"!\[[^\]]*\]\(\s*(?:https?:)?//", text), f"{rel}: external images are not allowed"


def test_theme_overrides_have_no_inline_scripts_or_styles():
    for f in (HANDBOOK / "overrides").rglob("*.html"):
        text = f.read_text(encoding="utf-8")
        assert not re.search(r"<script\b", text, re.I), f"{f}: no scripts in overrides (CSP hashes)"
        assert not re.search(r"\bstyle\s*=", text, re.I), f"{f}: no inline styles in overrides (CSP)"


def test_mkdocs_config_keeps_the_privacy_guard():
    config = yaml.load(MKDOCS_YML.read_text(encoding="utf-8"), Loader=_Loader)
    assert config["theme"]["font"] is False, "theme.font must be false (no Google Fonts)"
    plugins = {next(iter(p)) if isinstance(p, dict) else p: (p[next(iter(p))] if isinstance(p, dict) else {})
               for p in config["plugins"]}
    assert "privacy" in plugins and plugins["privacy"].get("assets_fetch") is False
    assert config.get("strict") is True
    assert "repo_url" not in config, "repo_url makes the reader's browser call api.github.com"
    assert "analytics" not in (config.get("extra") or {})
    assert "offline" not in plugins


# ----------------------------------------------------------------------------- safety lints

def _lines(body: str):
    for n, line in enumerate(body.splitlines(), 1):
        if DOSE_OK in line:
            continue
        yield n, line


@pytest.mark.parametrize("page", PAGES, ids=PAGE_IDS)
def test_no_insulin_or_medicine_doses(page):
    _, body = _split(page)
    rel = _rel(page)
    body = _strip_comments(body)
    for n, line in _lines(body):
        assert not INSULIN_UNITS.search(line), f"{rel}:{n}: looks like an insulin dose: {line.strip()[:120]}"
        assert not TAKE_AMOUNT.search(line), f"{rel}:{n}: looks like a medicine dose ('take N mg'): {line.strip()[:120]}"
        if rel.startswith(DOSE_DIRS):
            assert not UNITS_IN_DOSE_DIRS.search(line), f"{rel}:{n}: 'N units' is not allowed here: {line.strip()[:120]}"
            assert not MG_NEAR_DRUG.search(line), f"{rel}:{n}: milligrams next to a medicine name: {line.strip()[:120]}"


@pytest.mark.parametrize("page", [p for p in PAGES if _rel(p).startswith(DOSE_DIRS)],
                         ids=[r for r in PAGE_IDS if r.startswith(DOSE_DIRS)])
def test_dose_pages_carry_the_no_dosing_box(page):
    _, body = _split(page)
    assert NO_DOSING_INCLUDE in body, f"{_rel(page)}: pages under t1d/ and medicines/ must include {NO_DOSING_INCLUDE}"


def test_no_dosing_include_says_lows_come_first():
    text = (HANDBOOK / "includes" / "no-dosing.md").read_text(encoding="utf-8").lower()
    assert "never gives insulin or medicine doses" in text
    assert "low blood glucose is always treated straight away" in text


def test_dose_lint_catches_examples():
    assert INSULIN_UNITS.search("give 4 units of insulin")
    assert INSULIN_UNITS.search("insulin glargine 10 U at night")
    assert TAKE_AMOUNT.search("Take 500 mg twice a day")
    assert MG_NEAR_DRUG.search("finerenone 10 mg once daily")
    assert MG_NEAR_DRUG.search("400 mg of ibuprofen")
    assert UNITS_IN_DOSE_DIRS.search("reduce by 2 units")
    assert not MG_NEAR_DRUG.search("orange juice is about 250 mg potassium")
    assert not TAKE_AMOUNT.search("take 15 g of fast carbohydrate")
    assert not INSULIN_UNITS.search("switch to US units or International units")


def test_get_help_now_names_emergency_numbers_and_tiers():
    _, body = _split(DOCS / "get-help-now.md")
    for needle in ("911", "## Call 911 now", "## Call your care team today", "## Mention at your next visit",
                   "6.5 mmol/L", "3.0 mmol/L", "glucagon", "kh-wallet"):
        assert needle in body, f"get-help-now.md must mention {needle!r}"


def test_wallet_card_is_shared_and_keeps_the_action_levels():
    """get-help-now and reference/wallet-card print the same card (includes/help-card.md)."""
    card = (HANDBOOK / "includes" / "help-card.md").read_text(encoding="utf-8")
    for needle in ("911", "potassium 6.5", "potassium 6.0–6.4", "ketones 3.0", "ketones 1.6–2.9", "glucagon",
                   "keep the bag", "10–15 min"):
        assert needle in card, f"includes/help-card.md must mention {needle!r}"
    for page in ("get-help-now.md", "reference/wallet-card.md"):
        _, body = _split(DOCS / page)
        assert '--8<-- "includes/help-card.md"' in body and 'class="kh-wallet"' in body, \
            f"{page} must print the shared wallet card inside a kh-wallet box"


def test_pregnancy_page_refers_to_specialists():
    _, body = _split(DOCS / "living" / "sex-fertility-pregnancy.md")
    assert "maternal-fetal medicine" in body and "referral page" in body.lower()


# ----------------------------------------------------------------------------- generated files

def test_generated_files_are_fresh_and_menus_pass():
    bh = _load_build_script()
    files, results, problems = bh.build_all()
    assert not problems, "menu checks failed:\n" + "\n".join(problems)
    stale = [str(p.relative_to(ROOT)) for p, content in files.items()
             if not p.exists() or p.read_text(encoding="utf-8") != content]
    assert not stale, f"generated files are stale, run python scripts/build_handbook.py: {stale}"
    for path in files:
        assert GENERATED_MARKER in path.read_text(encoding="utf-8"), f"{path}: missing the GENERATED marker"
    assert len(results) >= 4
    for r in results:
        assert len(r.days) == 7, f"menu {r.spec['id']} must have 7 days"


def test_menus_use_only_builtin_foods_and_safe_flags():
    bh = _load_build_script()
    foods = bh.load_foods()
    menus = yaml.safe_load((HANDBOOK / "data" / "menus.yml").read_text(encoding="utf-8"))
    for spec in menus["menus"]:
        for day in spec["days"]:
            for meal in day["meals"]:
                for item in meal["items"]:
                    food = foods.get(int(item["fdc_id"]))
                    assert food, f"menu {spec['id']} {day['name']}: fdc_id {item['fdc_id']} not in data/foods.json"
                    flags = set(food.get("flags", []))
                    assert "avoid_ckd" not in flags, f"{food['name']} must never be on a menu"
                    assert "phosphate_additive" not in flags, f"{food['name']} has a phosphate additive"


def test_targets_table_applies_the_diabetes_protein_floor():
    text = (DOCS / "eat" / "_targets-table.md").read_text(encoding="utf-8")
    row = next(line for line in text.splitlines() if line.startswith("| G4 |"))
    assert "0.8 g/kg (about 56 g)" in row, row


# ----------------------------------------------------------------------------- advisory (warnings only)

def _syllables(word: str) -> int:
    word = word.lower()
    groups = re.findall(r"[aeiouy]+", word)
    n = len(groups)
    if word.endswith("e") and n > 1 and not word.endswith(("le", "ee")):
        n -= 1
    return max(1, n)


def _fk_grade(text: str) -> float | None:
    text = _strip_code(_strip_comments(text))
    text = re.sub(r"^\s*\|.*$", "", text, flags=re.M)               # tables
    text = re.sub(r"^\s*(?:!!!|\?\?\?|===|--8<--).*$", "", text, flags=re.M)
    text = re.sub(r"\[([^\]]*)\]\[[^\]]*\]", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"[#*_>`-]", " ", text)
    sentences = [s for s in re.split(r"[.!?:;]+\s", text) if re.search(r"[A-Za-z]", s)]
    words = re.findall(r"[A-Za-z][A-Za-z']*", text)
    if len(words) < 80 or not sentences:
        return None
    syl = sum(_syllables(w) for w in words)
    return 0.39 * len(words) / len(sentences) + 11.8 * syl / len(words) - 15.59


def test_advisory_checks_only_warn():
    today = dt.date.today()
    hard_reading = []
    for page in PAGES:
        meta, body = _split(page)
        rel = _rel(page)
        last = _as_date(meta.get("reviewed_on")) or _as_date(meta.get("last_checked"))
        if last and (today - last).days > 365:
            warnings.warn(f"{rel}: last checked or reviewed {last}, over a year ago")
        figures = _as_date(meta.get("figures_as_of"))
        if figures and figures < dt.date(today.year, 1, 1):
            warnings.warn(f"{rel}: figures_as_of {figures} is from before this year")
        if "renal" in str(meta.get("title", "")).lower():
            warnings.warn(f"{rel}: use 'kidney' rather than 'renal' in titles (KDIGO nomenclature)")
        prose = REF_LINK.sub("]", _strip_code(_strip_comments(body)))
        if re.search(r"(?<!not )\bESRD\b", prose) and rel not in ESRD_OK:
            warnings.warn(f"{rel}: 'ESRD' outside living/costs-and-benefits (say 'kidney failure')")
        if {"patient", "caregiver"} & set(meta.get("audience") or []):
            grade = _fk_grade(body)
            if grade is not None and grade > 9:
                hard_reading.append(f"{rel} ({grade:.1f})")
    if hard_reading:
        warnings.warn("reading grade above 9 (aim for 8): " + ", ".join(hard_reading))
