#!/usr/bin/env node
// Parity check of the browser twins against the server (ARCHITECTURE.md, "Frontend modules").
//
//   node tests/js/run_vectors.mjs            # exit 0 when every vector matches, 1 otherwise
//
// 1. Rules: app/static/js/engine/rules.js against tests/data/rules_vectors.json (app/nutrients.py).
// 2. Settings: app/static/js/engine/settings.js against tests/data/settings_vectors.json
//    (app/settings_registry.py + app/settings_store.py, generated by tests/data/gen_settings_vectors.py):
//    the registry table, value validation, and the precedence views of GET /api/me/settings and
//    GET /api/admin/settings, which the Settings view and the demo API (js/mock/settings.js) use.
//
// 3. Targets: app/static/js/engine/targets.js against tests/data/targets_vectors.json (app/targets.py +
//    app/target_rules.py, generated by tests/data/gen_targets_vectors.py): the rule tables, reference
//    weight, energy equation, every suggestion case (notes word for word) and the v0.2 wrapper.
// 4. Kidney function: app/static/js/engine/kidney_function.js against tests/data/kidney_function_vectors.json
//    (app/units.py + app/kidney_function.py): units, conversions, eGFR, categories, ages and the card.
//
// Loads app/static/js/engine/rules.js (a plain browser script) into a fresh V8 context whose only
// global is a bare object: the script falls back from `window` to `globalThis` and sets
// globalThis.KH.rules, so no DOM or bundler is needed. Then it replays tests/data/rules_vectors.json,
// which tests/data/gen_rules_vectors.py generates from app/nutrients.py (pytest checks that the file
// is current). No dependencies beyond Node 18+.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ENGINE = ['app/static/js/engine/rules.js'];
const VECTORS = join(ROOT, 'tests', 'data', 'rules_vectors.json');
const SETTINGS_ENGINE = 'app/static/js/engine/settings.js';
const SETTINGS_VECTORS = join(ROOT, 'tests', 'data', 'settings_vectors.json');
const TARGETS_ENGINE = ['app/static/js/engine/rules.js', 'app/static/js/engine/kidney_function.js', 'app/static/js/engine/targets.js'];
const TARGETS_VECTORS = join(ROOT, 'tests', 'data', 'targets_vectors.json');
const KIDNEY_VECTORS = join(ROOT, 'tests', 'data', 'kidney_function_vectors.json');

function loadEngine() {
  const context = vm.createContext({ console });
  for (const rel of ENGINE) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.rules) throw new Error('rules.js did not define KH.rules');
  return KH.rules;
}

// Values cross the V8 context boundary; compare plain JSON copies.
const plain = (v) => JSON.parse(JSON.stringify(v));

function loadSettings() {
  const context = vm.createContext({ console });
  vm.runInContext(readFileSync(join(ROOT, SETTINGS_ENGINE), 'utf8'), context, { filename: SETTINGS_ENGINE });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.settings) throw new Error('settings.js did not define KH.settings');
  return KH.settings;
}

// Returns [checks, failures].
function settingsVectors() {
  const S = loadSettings();
  const doc = JSON.parse(readFileSync(SETTINGS_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  // Registry: the same keys in the same order, each with the same description.
  expect('settings registry keys', S.DEFS.map((d) => d.key), doc.registry.map((r) => r.key));
  for (const want of doc.registry) {
    const def = S.BY_KEY[want.key];
    if (!def) { failures.push({ label: `registry ${want.key}`, got: null, want }); checks += 1; continue; }
    const got = {};
    for (const k of Object.keys(want)) got[k] = def[k] === undefined ? null : def[k];
    expect(`registry ${want.key}`, got, want);
  }
  for (const c of doc.validation_cases) {
    const def = S.BY_KEY[c.key];
    if (!def) continue;
    const r = S.validate(def, c.input);
    expect(`validate ${c.key} ${JSON.stringify(c.input)}`, r.error !== undefined ? { error: r.error } : { value: r.value },
      c.error !== undefined ? { error: c.error } : { value: c.value });
  }
  for (const c of doc.precedence_cases) {
    const ctx = { env: c.env, instance: c.instance, user: c.user };
    expect(`precedence "${c.name}": user view`, S.userView(ctx), c.user_view);
    expect(`precedence "${c.name}": admin view`, S.adminView(ctx), c.admin_view);
  }
  return [checks, failures, doc];
}

// Targets and kidney function share one context (targets.js needs rules.js and kidney_function.js).
function loadTargets() {
  const context = vm.createContext({ console });
  for (const rel of TARGETS_ENGINE) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.targets || !KH.kidney) throw new Error('targets.js / kidney_function.js did not define KH.targets and KH.kidney');
  return KH;
}
const closeTo = (a, b) => typeof a === 'number' && typeof b === 'number' && Math.abs(a - b) <= 1e-9 * Math.max(1, Math.abs(b));

// Returns [checks, failures, summary].
function targetsVectors(KH) {
  const T = KH.targets;
  const doc = JSON.parse(readFileSync(TARGETS_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  const tables = T.tables();
  for (const name of Object.keys(doc.tables)) expect(`tables.${name}`, tables[name], doc.tables[name]);
  expect('table names', Object.keys(tables).sort(), Object.keys(doc.tables).sort());
  for (const c of doc.reference_weight_cases) {
    const r = T.referenceWeight(c.weight_kg, c.height_cm);
    expect(`reference_weight(${c.weight_kg}, ${c.height_cm})`, { weight_kg: r.weight_kg, basis: r.basis }, c.expect);
  }
  for (const c of doc.eer_cases) {
    checks += 1;
    const got = T.eerKcal(c.sex, c.activity, c.age, c.height_cm, c.weight_kg);
    if (!closeTo(got, c.kcal)) failures.push({ label: `eer ${c.sex} ${c.activity} ${c.age}`, got, want: c.kcal });
  }
  // The API returns {id, ...rules[key]} with id "P-2" for the keys "P-2d" and "P-2n"; the vectors keep the key.
  const catalogueKey = (rule) => {
    const { id, ...rest } = rule;
    const keys = id === 'P-2' ? ['P-2d', 'P-2n'] : [id];
    return keys.find((k) => isDeepStrictEqual(plain(rest), plain(T.RULES[k]))) || `${id} (not in the catalogue)`;
  };
  for (const c of doc.cases) {
    let got;
    try {
      got = T.suggestFromRecords(c.profile, c.labs, c.today, c.settings);
      got = { ...got, rules: got.rules.map(catalogueKey) };
    } catch (e) {
      if (e instanceof T.OutOfScope) got = { error: { code: e.code, message: e.message } };
      else if (e instanceof T.InvalidInput) got = { invalid: e.message };
      else got = { exception: String(e && e.stack || e) };
    }
    const want = c.expect;
    if ('targets' in want && 'targets' in got) {
      for (const k of Object.keys(want)) expect(`${c.id}: ${k}`, got[k], want[k]);
      expect(`${c.id}: keys`, Object.keys(got).sort(), Object.keys(want).sort());
    } else expect(`${c.id}`, got, want);
  }
  for (const c of doc.wrapper_cases) expect(`suggest_targets(${c.args.map((a) => JSON.stringify(a)).join(', ')})`, T.suggestTargets(...c.args), c.expect);
  return [checks, failures, `${doc.cases.length} cases, ${doc.wrapper_cases.length} wrapper cases, ${doc.eer_cases.length} EER cases`];
}

function kidneyVectors(KH) {
  const KF = KH.kidney;
  const doc = JSON.parse(readFileSync(KIDNEY_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  expect('unit_table', KF.unitTable(), doc.unit_table);
  expect('unit_systems', KF.UNIT_SYSTEMS, doc.unit_systems);
  for (const c of doc.conversion_cases) {
    const value = c.value === 'Infinity' ? Infinity : c.value;
    let got;
    try { got = KF.convert(c.analyte, value, c.unit); } catch (e) { got = e instanceof KF.UnitError ? { error: e.message } : { exception: String(e) }; }
    expect(`convert(${c.analyte}, ${c.value}, ${c.unit})`, got, c.expect);
  }
  for (const c of doc.egfr_cases) {
    let got;
    try {
      const v = c.equation === 'cr' ? KF.egfrCr(c.creatinine, c.age, c.sex)
        : c.equation === 'cr_cys' ? KF.egfrCrCys(c.creatinine, c.cystatin_c, c.age, c.sex) : KF.egfrCys(c.cystatin_c, c.age, c.sex);
      got = { unrounded: v, rounded: KF.roundEgfr(v), category: KF.gfrCategory(v) };
    } catch (e) { got = e instanceof KF.KidneyFunctionError ? { error: e.message } : { exception: String(e) }; }
    const label = `egfr ${c.equation} ${JSON.stringify(c)}`;
    if ('unrounded' in c.expect && 'unrounded' in got) {
      checks += 1;
      if (!closeTo(got.unrounded, c.expect.unrounded)) failures.push({ label: `${label}: unrounded`, got: got.unrounded, want: c.expect.unrounded });
      expect(`${label}: rounded`, [got.rounded, got.category], [c.expect.rounded, c.expect.category]);
    } else expect(label, got, c.expect);
  }
  for (const c of doc.category_cases) expect(`gfr_category(${c.egfr})`, KF.gfrCategory(c.egfr), c.category);
  for (const c of doc.albuminuria_cases) expect(`albuminuria_category(${c.value}, ${c.unit})`, KF.albuminuriaCategory(c.value, c.unit), c.category);
  for (const c of doc.age_cases) expect(`age_on(${c.birth_month}, ${c.today}, ${c.last_day})`, KF.ageOn(c.birth_month, c.today, { lastDay: c.last_day }), c.age);
  for (const c of doc.assess_cases) expect(`assess "${c.name}"`, KF.assess({ labs: c.labs, today: c.today, ...c.profile }), c.expect);
  return [checks, failures, `${doc.conversion_cases.length} conversions, ${doc.egfr_cases.length} eGFR cases, ${doc.assess_cases.length} cards`];
}

function report(name, file, [checks, failures, summary]) {
  if (failures.length) {
    for (const f of failures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${failures.length} of ${checks} checks failed (${file})`);
    return 1;
  }
  console.log(`${name} vectors: ${checks} checks passed (${summary})`);
  return 0;
}

function main() {
  const rules = loadEngine();
  const doc = JSON.parse(readFileSync(VECTORS, 'utf8'));
  const keys = doc.nutrient_keys;
  if (!isDeepStrictEqual(keys, plain(rules.NUTRIENT_KEYS))) {
    console.error(`nutrient keys differ: vectors ${keys} engine ${rules.NUTRIENT_KEYS}`);
    return 1;
  }
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };

  for (const c of doc.food_cases) {
    const f = doc.foods[c.food];
    const scaled = Object.fromEntries(keys.map((k) => [k, f.nutrients[k] == null ? null : Number(f.nutrients[k]) * c.servings]));
    const label = `${f.name} x${c.servings} (${c.scope})`;
    const warnings = rules.evaluateWarnings(scaled, f.flags, f.kidney_notes, c.scope);
    expect(`${label}: warnings`, warnings, c.warnings);
    expect(`${label}: kidney_rating`, rules.ratingFromWarnings(warnings), c.kidney_rating);
    const rounded = rules.roundNutrients(scaled);
    expect(`${label}: rounded`, keys.map((k) => rounded[k]), c.rounded);
  }
  doc.boundary_cases.forEach((c, i) => {
    const label = `boundary ${i} ${JSON.stringify(c.nutrients)} ${JSON.stringify(c.flags)} (${c.scope})`;
    const warnings = rules.evaluateWarnings(c.nutrients, c.flags, c.kidney_notes, c.scope);
    expect(`${label}: warnings`, warnings, c.warnings);
    expect(`${label}: kidney_rating`, rules.ratingFromWarnings(warnings), c.kidney_rating);
  });
  for (const c of doc.round_cases) expect(`round_value(${c.key}, ${c.value})`, rules.roundValue(c.key, c.value), c.expected);

  const [sChecks, sFailures, sDoc] = settingsVectors();
  let status = 0;
  if (failures.length) {
    for (const f of failures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${failures.length} of ${checks} checks failed (tests/data/rules_vectors.json vs app/static/js/engine/rules.js)`);
    status = 1;
  } else {
    console.log(`rules vectors: ${checks} checks passed (${doc.food_cases.length} food cases, ${doc.boundary_cases.length} boundary cases, ${doc.round_cases.length} rounding cases)`);
  }
  if (sFailures.length) {
    for (const f of sFailures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${sFailures.length} of ${sChecks} checks failed (tests/data/settings_vectors.json vs ${SETTINGS_ENGINE})`);
    status = 1;
  } else {
    console.log(`settings vectors: ${sChecks} checks passed (${sDoc.registry.length} keys, ${sDoc.validation_cases.length} validation cases, ${sDoc.precedence_cases.length} precedence cases)`);
  }
  const targetsKH = loadTargets();
  status |= report('targets', 'tests/data/targets_vectors.json vs app/static/js/engine/targets.js', targetsVectors(targetsKH));
  status |= report('kidney function', 'tests/data/kidney_function_vectors.json vs app/static/js/engine/kidney_function.js', kidneyVectors(targetsKH));
  return status;
}

process.exitCode = main();
