#!/usr/bin/env node
// Parity check of the browser twins against the server (ARCHITECTURE.md, "Frontend modules").
//
//   node tests/js/run_vectors.mjs            # exit 0 when every vector matches, 1 otherwise
//   node tests/js/run_vectors.mjs --guidance FILE   # replay only a guidance vector file (same format as
//                                                   # tests/data/guidance_vectors.json, e.g. a fuzz run)
//
// 1. Rules: app/static/js/engine/rules.js against tests/data/rules_vectors.json (app/nutrients.py).
// 2. Settings: app/static/js/engine/settings.js against tests/data/settings_vectors.json
//    (app/settings_registry.py + app/settings_store.py, generated by tests/data/gen_settings_vectors.py):
//    the registry table, value validation, and the precedence views of GET /api/me/settings and
//    GET /api/admin/settings, which the Settings view and the demo API (js/mock/settings.js) use.
//
// 3. Targets: app/static/js/engine/targets.js against tests/data/targets_vectors.json (app/targets.py +
//    app/target_rules.py, generated by tests/data/gen_targets_vectors.py): the rule tables, reference
//    weight, energy equation, every suggestion case (notes word for word) and the v0.2 wrapper.
// 4. Kidney function: app/static/js/engine/kidney_function.js against tests/data/kidney_function_vectors.json
//    (app/units.py + app/kidney_function.py): units, conversions, eGFR, categories, ages and the card.
// 5. Guidance: app/static/js/engine/guidance/*.js against tests/data/guidance_vectors.json (app/guidance/,
//    generated by tests/data/gen_guidance_vectors.py): the rules version and hash, then every case (meal room,
//    what fits now, swaps, low-treatment options, plan-day, day and period insights, the AI prefilter) replayed
//    from the same plain-JSON inputs and compared with the engine's answer exactly, explain blocks included.
// 6. Barcodes: app/static/js/engine/{gtin,textclean,additives,off}.js against tests/data/barcode_vectors.json
//    (app/gtin.py, app/textclean.py, app/additives.py, app/off.py; tests/data/gen_barcode_vectors.py), and the
//    demo's POST /api/foods/barcode (js/mock/barcode.js over js/mock/core.js + foods.js) rebuilding the
//    server's answer for each of its three recorded Open Food Facts products.
//
// Loads app/static/js/engine/rules.js (a plain browser script) into a fresh V8 context whose only
// global is a bare object: the script falls back from `window` to `globalThis` and sets
// globalThis.KH.rules, so no DOM or bundler is needed. Then it replays tests/data/rules_vectors.json,
// which tests/data/gen_rules_vectors.py generates from app/nutrients.py (pytest checks that the file
// is current). No dependencies beyond Node 18+.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isDeepStrictEqual } from 'node:util';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const ENGINE = ['app/static/js/engine/rules.js'];
const VECTORS = join(ROOT, 'tests', 'data', 'rules_vectors.json');
const SETTINGS_ENGINE = 'app/static/js/engine/settings.js';
const SETTINGS_VECTORS = join(ROOT, 'tests', 'data', 'settings_vectors.json');
const TARGETS_ENGINE = ['app/static/js/engine/rules.js', 'app/static/js/engine/kidney_function.js', 'app/static/js/engine/targets.js'];
const TARGETS_VECTORS = join(ROOT, 'tests', 'data', 'targets_vectors.json');
const KIDNEY_VECTORS = join(ROOT, 'tests', 'data', 'kidney_function_vectors.json');
// Load order matters (each part uses the ones before it); index.html lists them in the same order.
const GUIDANCE_PARTS = ['rules', 'messages', 'budget', 'score', 'fits', 'swaps', 'planner', 'insights', 'hypo'];
const GUIDANCE_ENGINE = ['app/static/js/engine/rules.js', ...GUIDANCE_PARTS.map((p) => `app/static/js/engine/guidance/${p}.js`)];
const GUIDANCE_VECTORS = join(ROOT, 'tests', 'data', 'guidance_vectors.json');
const BARCODE_ENGINE = ['rules', 'textclean', 'gtin', 'additives', 'off'].map((p) => `app/static/js/engine/${p}.js`);
const BARCODE_MOCK = ['core', 'foods', 'barcode'].map((p) => `app/static/js/mock/${p}.js`);
const BARCODE_VECTORS = join(ROOT, 'tests', 'data', 'barcode_vectors.json');

function loadEngine() {
  const context = vm.createContext({ console });
  for (const rel of ENGINE) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.rules) throw new Error('rules.js did not define KH.rules');
  return KH.rules;
}

// Values cross the V8 context boundary; compare plain JSON copies.
const plain = (v) => JSON.parse(JSON.stringify(v));
// The same, keeping the sign of zero: Python writes -0.0 (for example a delta of -0.04 g rounded to one decimal),
// JSON.parse reads it as -0, and isDeepStrictEqual tells -0 from 0.
const NEG_ZERO = '\u0000-0';
const plainSigned = (v) => JSON.parse(JSON.stringify(v, (k, x) => (Object.is(x, -0) ? NEG_ZERO : x)), (k, x) => (x === NEG_ZERO ? -0 : x));

function loadSettings() {
  const context = vm.createContext({ console });
  vm.runInContext(readFileSync(join(ROOT, SETTINGS_ENGINE), 'utf8'), context, { filename: SETTINGS_ENGINE });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.settings) throw new Error('settings.js did not define KH.settings');
  return KH.settings;
}

// Returns [checks, failures].
function settingsVectors() {
  const S = loadSettings();
  const doc = JSON.parse(readFileSync(SETTINGS_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  // Registry: the same keys in the same order, each with the same description.
  expect('settings registry keys', S.DEFS.map((d) => d.key), doc.registry.map((r) => r.key));
  for (const want of doc.registry) {
    const def = S.BY_KEY[want.key];
    if (!def) { failures.push({ label: `registry ${want.key}`, got: null, want }); checks += 1; continue; }
    const got = {};
    for (const k of Object.keys(want)) got[k] = def[k] === undefined ? null : def[k];
    expect(`registry ${want.key}`, got, want);
  }
  for (const c of doc.validation_cases) {
    const def = S.BY_KEY[c.key];
    if (!def) continue;
    const r = S.validate(def, c.input);
    expect(`validate ${c.key} ${JSON.stringify(c.input)}`, r.error !== undefined ? { error: r.error } : { value: r.value },
      c.error !== undefined ? { error: c.error } : { value: c.value });
  }
  for (const c of doc.precedence_cases) {
    const ctx = { env: c.env, instance: c.instance, user: c.user };
    expect(`precedence "${c.name}": user view`, S.userView(ctx), c.user_view);
    expect(`precedence "${c.name}": admin view`, S.adminView(ctx), c.admin_view);
  }
  return [checks, failures, doc];
}

// Targets and kidney function share one context (targets.js needs rules.js and kidney_function.js).
function loadTargets() {
  const context = vm.createContext({ console });
  for (const rel of TARGETS_ENGINE) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.targets || !KH.kidney) throw new Error('targets.js / kidney_function.js did not define KH.targets and KH.kidney');
  return KH;
}
const closeTo = (a, b) => typeof a === 'number' && typeof b === 'number' && Math.abs(a - b) <= 1e-9 * Math.max(1, Math.abs(b));

// Returns [checks, failures, summary].
function targetsVectors(KH) {
  const T = KH.targets;
  const doc = JSON.parse(readFileSync(TARGETS_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  const tables = T.tables();
  for (const name of Object.keys(doc.tables)) expect(`tables.${name}`, tables[name], doc.tables[name]);
  expect('table names', Object.keys(tables).sort(), Object.keys(doc.tables).sort());
  for (const c of doc.reference_weight_cases) {
    const r = T.referenceWeight(c.weight_kg, c.height_cm);
    expect(`reference_weight(${c.weight_kg}, ${c.height_cm})`, { weight_kg: r.weight_kg, basis: r.basis }, c.expect);
  }
  for (const c of doc.eer_cases) {
    checks += 1;
    const got = T.eerKcal(c.sex, c.activity, c.age, c.height_cm, c.weight_kg);
    if (!closeTo(got, c.kcal)) failures.push({ label: `eer ${c.sex} ${c.activity} ${c.age}`, got, want: c.kcal });
  }
  // The API returns {id, ...rules[key]} with id "P-2" for the keys "P-2d" and "P-2n"; the vectors keep the key.
  const catalogueKey = (rule) => {
    const { id, ...rest } = rule;
    const keys = id === 'P-2' ? ['P-2d', 'P-2n'] : [id];
    return keys.find((k) => isDeepStrictEqual(plain(rest), plain(T.RULES[k]))) || `${id} (not in the catalogue)`;
  };
  for (const c of doc.cases) {
    let got;
    try {
      got = T.suggestFromRecords(c.profile, c.labs, c.today, c.settings);
      got = { ...got, rules: got.rules.map(catalogueKey) };
    } catch (e) {
      if (e instanceof T.OutOfScope) got = { error: { code: e.code, message: e.message } };
      else if (e instanceof T.InvalidInput) got = { invalid: e.message };
      else got = { exception: String(e && e.stack || e) };
    }
    const want = c.expect;
    if ('targets' in want && 'targets' in got) {
      for (const k of Object.keys(want)) expect(`${c.id}: ${k}`, got[k], want[k]);
      expect(`${c.id}: keys`, Object.keys(got).sort(), Object.keys(want).sort());
    } else expect(`${c.id}`, got, want);
  }
  for (const c of doc.wrapper_cases) expect(`suggest_targets(${c.args.map((a) => JSON.stringify(a)).join(', ')})`, T.suggestTargets(...c.args), c.expect);
  return [checks, failures, `${doc.cases.length} cases, ${doc.wrapper_cases.length} wrapper cases, ${doc.eer_cases.length} EER cases`];
}

function kidneyVectors(KH) {
  const KF = KH.kidney;
  const doc = JSON.parse(readFileSync(KIDNEY_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  expect('unit_table', KF.unitTable(), doc.unit_table);
  expect('unit_systems', KF.UNIT_SYSTEMS, doc.unit_systems);
  for (const c of doc.conversion_cases) {
    const value = c.value === 'Infinity' ? Infinity : c.value;
    let got;
    try { got = KF.convert(c.analyte, value, c.unit); } catch (e) { got = e instanceof KF.UnitError ? { error: e.message } : { exception: String(e) }; }
    expect(`convert(${c.analyte}, ${c.value}, ${c.unit})`, got, c.expect);
  }
  for (const c of doc.egfr_cases) {
    let got;
    try {
      const v = c.equation === 'cr' ? KF.egfrCr(c.creatinine, c.age, c.sex)
        : c.equation === 'cr_cys' ? KF.egfrCrCys(c.creatinine, c.cystatin_c, c.age, c.sex) : KF.egfrCys(c.cystatin_c, c.age, c.sex);
      got = { unrounded: v, rounded: KF.roundEgfr(v), category: KF.gfrCategory(v) };
    } catch (e) { got = e instanceof KF.KidneyFunctionError ? { error: e.message } : { exception: String(e) }; }
    const label = `egfr ${c.equation} ${JSON.stringify(c)}`;
    if ('unrounded' in c.expect && 'unrounded' in got) {
      checks += 1;
      if (!closeTo(got.unrounded, c.expect.unrounded)) failures.push({ label: `${label}: unrounded`, got: got.unrounded, want: c.expect.unrounded });
      expect(`${label}: rounded`, [got.rounded, got.category], [c.expect.rounded, c.expect.category]);
    } else expect(label, got, c.expect);
  }
  for (const c of doc.category_cases) expect(`gfr_category(${c.egfr})`, KF.gfrCategory(c.egfr), c.category);
  for (const c of doc.albuminuria_cases) expect(`albuminuria_category(${c.value}, ${c.unit})`, KF.albuminuriaCategory(c.value, c.unit), c.category);
  for (const c of doc.age_cases) expect(`age_on(${c.birth_month}, ${c.today}, ${c.last_day})`, KF.ageOn(c.birth_month, c.today, { lastDay: c.last_day }), c.age);
  for (const c of doc.assess_cases) expect(`assess "${c.name}"`, KF.assess({ labs: c.labs, today: c.today, ...c.profile }), c.expect);
  return [checks, failures, `${doc.conversion_cases.length} conversions, ${doc.egfr_cases.length} eGFR cases, ${doc.assess_cases.length} cards`];
}

function loadGuidance() {
  const context = vm.createContext({ console });
  for (const rel of GUIDANCE_ENGINE) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  if (!KH || !KH.guidanceEngine || !KH.guidanceEngine.planDay) throw new Error('js/engine/guidance/*.js did not define KH.guidanceEngine');
  return KH.guidanceEngine;
}

// The replayer of tests/data/gen_guidance_vectors.py (context_from / call): plain JSON in, engine answer out.
function guidanceVectors(GE, file = GUIDANCE_VECTORS) {
  const doc = JSON.parse(readFileSync(file, 'utf8'));
  const own = file === GUIDANCE_VECTORS;
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plainSigned(got), want)) failures.push({ label, got: plainSigned(got), want });
  };
  if (own) {
    expect('rules_version', GE.R.RULES_VERSION, doc.rules_version);
    expect('rules_hash', GE.R.RULES_HASH, doc.rules_hash);
  }
  const REAL_ID0 = 101;
  const allFoods = new Map(doc.foods.map((r) => [r.id, GE.makeFood(r)]));
  const foodsFor = (inp) => {
    if (inp.food_set === 'all') return allFoods;
    const fixture = inp.food_set === 'fixture';
    return new Map([...allFoods].filter(([id]) => (id < REAL_ID0) === fixture));
  };
  const history = (rows, foods) => rows.map((h) => GE.historyEntry({ ...h, flags: foods.get(h.food_id).flags }));
  const contextFrom = (inp) => {
    const foods = foodsFor(inp);
    const day = inp.day.map((e) => GE.dayEntry({ id: e.id, meal: e.meal, status: e.status, food: foods.get(e.food_id), name: e.name,
      servings: e.servings, nutrients: { ...e.nutrients }, purpose: e.purpose }));
    const hist = history(inp.history, foods);
    return GE.makeContext({ date: inp.date, profile: inp.profile, prefs: inp.prefs, foods, day, history: hist,
      history60: inp.history60 != null ? history(inp.history60, foods) : null,
      saved_meals: inp.saved_meals.map((m) => ({ id: m.id, name: m.name, meal_hint: m.meal_hint, items: m.items.map(([f, q]) => [f, q]) })),
      combos: inp.combos.map((c) => ({ ...c, items: c.items.map(([f, q]) => [f, q]) })), tunables: inp.tunables });
  };
  const finite = (v) => (v === Infinity ? null : v);
  const call = (inp, spec) => {
    const fn = spec.fn;
    if (fn === 'prefilter') return GE.prefilter(spec.text, spec.dose_g == null ? GE.R.HYPO_DOSE_G : spec.dose_g);
    const ctx = contextFrom(inp);
    if (fn === 'period_insights') {
      return GE.periodInsights(ctx.profile, ctx.prefs, spec.start, spec.end, history(spec.entries, allFoods), history(spec.previous || [], allFoods));
    }
    if (fn === 'meal_room') {
      const room = GE.mealRoom(ctx, spec.meal, spec.open_meals || null);
      const dayLeft = {};
      for (const [k, v] of Object.entries(room.day_left)) dayLeft[k] = finite(v);
      return { open_meals: [...room.open_meals], room: GE.roomJson(room), meal_has: { ...room.meal_has }, meal_high_k: room.meal_high_k,
        day_high_k: room.day_high_k, usage_weight: { ...room.usage_weight }, day_left: dayLeft };
    }
    if (fn === 'what_fits') return GE.whatFits(ctx, spec.meal, spec.limit == null ? GE.R.DEFAULT_LIMIT : spec.limit, !!spec.explain);
    if (fn === 'find_swaps') return GE.findSwaps(ctx, spec.meal, ctx.foods.get(spec.food_id), spec.servings, spec.purpose || null, GE.R.SWAP_MAX, !!spec.explain);
    if (fn === 'hypo_options') return GE.hypoOptions(ctx);
    if (fn === 'plan_day') {
      return GE.planDay(ctx, spec.meals || null, { useSavedMeals: spec.use_saved_meals !== false, useUsual: spec.use_usual !== false,
        useStarters: spec.use_starters !== false, variant: spec.variant || 0 });
    }
    if (fn === 'day_insights') return GE.dayInsights(ctx);
    throw new Error(`unknown fn ${fn}`);
  };
  const counts = {};
  for (const c of doc.cases) {
    counts[c.call.fn] = (counts[c.call.fn] || 0) + 1;
    let got;
    try { got = call(c.input, c.call); } catch (e) { got = { exception: String(e && e.stack || e) }; }
    expect(`${c.id} (${c.call.fn})`, got, c.output);
  }
  return [checks, failures, `${doc.cases.length} cases: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}`];
}

function loadBarcode() {
  const context = vm.createContext({ console, URL });
  vm.runInContext('globalThis.window = globalThis;', context);
  for (const rel of [...BARCODE_ENGINE, ...BARCODE_MOCK]) vm.runInContext(readFileSync(join(ROOT, rel), 'utf8'), context, { filename: rel });
  const KH = vm.runInContext('globalThis.KH', context);
  for (const part of ['gtin', 'textclean', 'additives', 'off', 'mock']) if (!KH[part]) throw new Error(`barcode twins did not define KH.${part}`);
  return KH;
}

// A demo API with only the tables the barcode route reads, signed in as person 1 who agreed to Open Food Facts.
function barcodeMock(KH) {
  const api = Object.create(KH.mock.MockApi.prototype);
  Object.assign(api, { _lastUs: 0, _foods: [], _foodById: new Map(), _nextFoodId: 1, _entries: [], _templates: [] });
  const settings = { 'food.off_enabled': true, 'food.off_consent': true, 'food.usda_branded_barcode': true };
  api._currentUser = () => ({ id: 1 });
  api._effectiveSetting = (key) => ({ value: settings[key] });
  return api;
}

function barcodeVectors(KH) {
  const doc = JSON.parse(readFileSync(BARCODE_VECTORS, 'utf8'));
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };
  const G = KH.gtin;
  for (const c of doc.check_digit_cases) expect(`check_digit(${c.body})`, G.checkDigit(c.body), c.digit);
  for (const c of doc.gtin_cases) {
    let got;
    try {
      const g14 = G.normalize(c.code, c.format);
      got = { code: c.code, format: c.format, normalize: g14, classify: G.classify(g14), off_code: G.offCode(g14), usda_candidates: G.usdaCandidates(g14) };
    } catch (e) {
      got = e instanceof G.GtinError ? { code: c.code, format: c.format, error: { reason: e.reason, message: e.message } } : { exception: String(e) };
    }
    expect(`gtin ${JSON.stringify(c.code)} ${c.format}`, got, c);
  }
  for (const c of doc.textclean_cases) {
    expect(`clean_text(${JSON.stringify(c.value)}, ${c.max_len}, ${c.keep_newlines})`,
      KH.textclean.cleanText(c.value, { maxLen: c.max_len, keepNewlines: c.keep_newlines }), c.result);
  }
  for (const c of doc.additive_cases) {
    let got;
    try { got = KH.additives.scan(c.tags, c.text, c.name); } catch (e) { got = { exception: String(e && e.stack || e) }; }
    expect(`scan(${JSON.stringify(c.tags)}, ${JSON.stringify(c.text).slice(0, 80)}, ${JSON.stringify(c.name)})`, got, c.result);
  }
  for (const c of doc.quality_cases) expect(`quality_items(${JSON.stringify(c.codes)})`, KH.off.qualityItems(c.codes), c.items);
  // The demo's embedded rows are the generated ones (tests/test_barcode_vectors.py checks the file too).
  expect('js/mock/barcode.js DEMO_PRODUCTS', KH.mock.DEMO_PRODUCTS,
    doc.demo_products.map((p) => ({ fixture: p.fixture, code: p.code, format: p.format, row: p.row })));
  const api = barcodeMock(KH);
  for (const p of doc.demo_products) {
    let got;
    try { got = api.handle('POST', '/api/foods/barcode', { code: p.code, format: p.format }); delete got.food.id; } catch (e) {
      got = { exception: String(e && (e.detail || e.stack) || e) };
    }
    expect(`demo POST /api/foods/barcode ${p.fixture}`, got, p.result);
  }
  const summary = `${doc.gtin_cases.length} GTIN, ${doc.textclean_cases.length} text, ${doc.additive_cases.length} additive, `
    + `${doc.quality_cases.length} quality cases, ${doc.demo_products.length} demo products`;
  return [checks, failures, summary];
}

function report(name, file, [checks, failures, summary]) {
  if (failures.length) {
    for (const f of failures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${failures.length} of ${checks} checks failed (${file})`);
    return 1;
  }
  console.log(`${name} vectors: ${checks} checks passed (${summary})`);
  return 0;
}

function main() {
  const gi = process.argv.indexOf('--guidance');
  if (gi >= 0) {
    const file = process.argv[gi + 1];
    if (!file) { console.error('--guidance needs a file'); return 2; }
    return report('guidance', file, guidanceVectors(loadGuidance(), file));
  }
  const rules = loadEngine();
  const doc = JSON.parse(readFileSync(VECTORS, 'utf8'));
  const keys = doc.nutrient_keys;
  if (!isDeepStrictEqual(keys, plain(rules.NUTRIENT_KEYS))) {
    console.error(`nutrient keys differ: vectors ${keys} engine ${rules.NUTRIENT_KEYS}`);
    return 1;
  }
  const failures = [];
  let checks = 0;
  const expect = (label, got, want) => {
    checks += 1;
    if (!isDeepStrictEqual(plain(got), want)) failures.push({ label, got: plain(got), want });
  };

  for (const c of doc.food_cases) {
    const f = doc.foods[c.food];
    const scaled = Object.fromEntries(keys.map((k) => [k, f.nutrients[k] == null ? null : Number(f.nutrients[k]) * c.servings]));
    const label = `${f.name} x${c.servings} (${c.scope})`;
    const warnings = rules.evaluateWarnings(scaled, f.flags, f.kidney_notes, c.scope);
    expect(`${label}: warnings`, warnings, c.warnings);
    expect(`${label}: kidney_rating`, rules.ratingFromWarnings(warnings), c.kidney_rating);
    const rounded = rules.roundNutrients(scaled);
    expect(`${label}: rounded`, keys.map((k) => rounded[k]), c.rounded);
  }
  doc.boundary_cases.forEach((c, i) => {
    const label = `boundary ${i} ${JSON.stringify(c.nutrients)} ${JSON.stringify(c.flags)} (${c.scope})`;
    const warnings = rules.evaluateWarnings(c.nutrients, c.flags, c.kidney_notes, c.scope);
    expect(`${label}: warnings`, warnings, c.warnings);
    expect(`${label}: kidney_rating`, rules.ratingFromWarnings(warnings), c.kidney_rating);
  });
  for (const c of doc.round_cases) expect(`round_value(${c.key}, ${c.value})`, rules.roundValue(c.key, c.value), c.expected);

  const [sChecks, sFailures, sDoc] = settingsVectors();
  let status = 0;
  if (failures.length) {
    for (const f of failures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${failures.length} of ${checks} checks failed (tests/data/rules_vectors.json vs app/static/js/engine/rules.js)`);
    status = 1;
  } else {
    console.log(`rules vectors: ${checks} checks passed (${doc.food_cases.length} food cases, ${doc.boundary_cases.length} boundary cases, ${doc.round_cases.length} rounding cases)`);
  }
  if (sFailures.length) {
    for (const f of sFailures.slice(0, 20)) console.error(`MISMATCH ${f.label}\n   js:     ${JSON.stringify(f.got)}\n   python: ${JSON.stringify(f.want)}`);
    console.error(`\n${sFailures.length} of ${sChecks} checks failed (tests/data/settings_vectors.json vs ${SETTINGS_ENGINE})`);
    status = 1;
  } else {
    console.log(`settings vectors: ${sChecks} checks passed (${sDoc.registry.length} keys, ${sDoc.validation_cases.length} validation cases, ${sDoc.precedence_cases.length} precedence cases)`);
  }
  const targetsKH = loadTargets();
  status |= report('targets', 'tests/data/targets_vectors.json vs app/static/js/engine/targets.js', targetsVectors(targetsKH));
  status |= report('kidney function', 'tests/data/kidney_function_vectors.json vs app/static/js/engine/kidney_function.js', kidneyVectors(targetsKH));
  status |= report('guidance', 'tests/data/guidance_vectors.json vs app/static/js/engine/guidance/*.js', guidanceVectors(loadGuidance()));
  status |= report('barcode', 'tests/data/barcode_vectors.json vs app/static/js/engine/{gtin,textclean,additives,off}.js + js/mock/barcode.js', barcodeVectors(loadBarcode()));
  return status;
}

process.exitCode = main();
