#!/usr/bin/env python3
"""Generate the handbook's derived pages from the data the app uses, and check them.

Spec: docs/dev/research/08-handbook-site.md §4.5 and §5.5. Dev and CI only (runs in the handbook
venv: ``pip install --require-hashes -r handbook/requirements.lock``; needs PyYAML).

Usage
=====

    python scripts/build_handbook.py            # --write (default): regenerate every generated file
    python scripts/build_handbook.py --check    # regenerate in memory; exit 1 if a file is stale or a menu fails
    python scripts/build_handbook.py --totals   # print every menu day's totals and the checks, change nothing

Generated files (each starts with, or right after its front matter carries, the GENERATED marker):

* ``handbook/includes/sources.md``     reference-link definitions for every id in ``handbook/sources.yml``
  (appended to every page by pymdownx.snippets, so pages can write ``[KDIGO 2024][K24]``)
* ``handbook/docs/reference/sources.md``  the rendered bibliography
* ``handbook/docs/eat/_targets-table.md``  targets by stage, from ``docs/research/targets_by_stage.json``
* ``handbook/docs/eat/menus/<id>.md``   7-day sample menus, from ``handbook/data/menus.yml`` and the
  builtin foods in ``data/foods.json`` (by ``fdc_id`` and servings)
* ``handbook/docs/eat/menus/_overview.md``  the menu summary table included by ``eat/menus/index.md``
* ``handbook/docs/eat/grocery-lists.md``  printable weekly shopping checklists for every menu
* ``handbook/docs/eat/recipes/<id>.md``  original recipes with per-serving nutrients, from
  ``handbook/data/recipes.yml`` (ingredients by ``fdc_id`` and grams: builtin foods, plus a few SR Legacy
  seasonings whose per-100 g values are stored in that file)
* ``handbook/docs/eat/recipes/_overview.md``  the recipe table included by ``eat/recipes/index.md``

Synced assets (``--write`` copies them; ``--check`` only warns when they drift, because their sources
are owned elsewhere): ``docs/assets/icon.svg`` from ``app/static/icons/icon.svg`` when that file exists,
and ``docs/assets/licences/{material,material-design-icons,fontawesome}-LICENSE.txt`` from the installed
mkdocs-material distribution (the theme, and the two icon sets the site inlines).

Targets mirror ``app.nutrients.suggest_targets()`` for the reference person in ``menus.yml`` (70 kg,
170 cm, type 1 diabetes; BMI 24.2, so the reference weight is the actual weight): the stage row of
``targets_by_stage.json`` × weight, rounded half-up, with the ARCHITECTURE.md v0.3 item 10 diabetes
floor (protein never below 0.8 g/kg at G3a–G5 without dialysis). The script does not import ``app/``
so the handbook builds without the app's dependencies.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import shutil
import sys
from dataclasses import dataclass, field
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - the handbook venv always has PyYAML
    sys.exit("build_handbook.py needs PyYAML: pip install --require-hashes -r handbook/requirements.lock")

ROOT = Path(__file__).resolve().parents[1]
HANDBOOK = ROOT / "handbook"
DOCS = HANDBOOK / "docs"
SOURCES_YML = HANDBOOK / "sources.yml"
MENUS_YML = HANDBOOK / "data" / "menus.yml"
RECIPES_YML = HANDBOOK / "data" / "recipes.yml"
FOODS_JSON = ROOT / "data" / "foods.json"
TARGETS_JSON = ROOT / "docs" / "research" / "targets_by_stage.json"
APP_ICON = ROOT / "app" / "static" / "icons" / "icon.svg"

MARKER = "<!-- GENERATED by scripts/build_handbook.py; do not edit -->"
NUTRIENTS = ("calories_kcal", "carbs_g", "protein_g", "potassium_mg", "phosphorus_mg", "sodium_mg",
             "fluid_ml", "fiber_g", "fat_g", "calcium_mg")
MAIN_MEALS = ("breakfast", "lunch", "dinner")
MEAL_TITLES = {"breakfast": "Breakfast", "lunch": "Lunch", "dinner": "Dinner", "snack": "Snack"}
CATEGORY_ORDER = ["Meat, Poultry & Eggs", "Fish & Seafood", "Legumes, Nuts & Seeds", "Dairy & Alternatives",
                  "Grains & Breads", "Vegetables", "Fruits", "Condiments & Sauces", "Beverages",
                  "Sweets & Snacks", "Prepared & Fast Food", "Diabetes supplies"]
NOT_SHOPPED = {173647}  # tap water: counted in the menus' fluid, not bought
DIABETES_FLOOR_STAGES = {"3a", "3b", "4", "5"}  # ARCHITECTURE.md v0.3 item 10 (note 05 fact-check H1)
STAGE_LABELS = {("1", "none"): "G1", ("2", "none"): "G2", ("3a", "none"): "G3a", ("3b", "none"): "G3b",
                ("4", "none"): "G4", ("5", "none"): "G5, no dialysis", ("5", "hemodialysis"): "Hemodialysis",
                ("5", "peritoneal"): "Peritoneal dialysis"}


# ----------------------------------------------------------------------------- small helpers

def half_up(value: float, places: int = 0) -> float:
    q = Decimal(1).scaleb(-places)
    return float(Decimal(repr(value)).quantize(q, rounding=ROUND_HALF_UP))


def fmt_int(value: float) -> str:
    return f"{int(half_up(value)):,}"


def fmt_1(value: float) -> str:
    return f"{half_up(value, 1):.1f}"


def yaml_scalar(value: str) -> str:
    """Quote a front-matter string when YAML would otherwise misread it."""
    if value == "" or re.search(r"[:#'\"\[\]{},&*!|>%@`]", value) or value != value.strip():
        return json.dumps(value, ensure_ascii=False)
    return value


_ISO_DATE = re.compile(r"\d{4}-\d{2}-\d{2}")


def front_matter(meta: dict) -> str:
    lines = ["---"]
    for key, value in meta.items():
        if isinstance(value, list):
            lines.append(f"{key}: [{', '.join(str(v) for v in value)}]")
        elif value is None:
            lines.append(f"{key}: null")
        elif isinstance(value, bool):
            lines.append(f"{key}: {'true' if value else 'false'}")
        else:
            text = str(value)
            if not _ISO_DATE.fullmatch(text):
                text = yaml_scalar(text)
            lines.append(f"{key}: {text}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def with_fact_check(meta: dict, fact_checked) -> dict:
    """Add ``fact_checked`` (the date of the last clinical fact-check, from the data file) after
    ``last_checked`` so generated pages carry the same front matter as hand-written ones."""
    if not fact_checked:
        return meta
    out: dict = {}
    for key, value in meta.items():
        out[key] = value
        if key == "last_checked":
            out["fact_checked"] = str(fact_checked)
    return out


def md_cell(text: str) -> str:
    return str(text).replace("|", "\\|")


# ----------------------------------------------------------------------------- data loading

def load_yaml(path: Path):
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def load_sources(path: Path = SOURCES_YML) -> dict:
    data = load_yaml(path)
    if not isinstance(data, dict):
        raise SystemExit(f"{path}: expected a mapping of id -> entry")
    return {str(k): v for k, v in data.items()}


def load_foods(path: Path = FOODS_JSON) -> dict[int, dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {int(f["fdc_id"]): f for f in data["foods"]}


def load_target_rows(path: Path = TARGETS_JSON) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


# ----------------------------------------------------------------------------- targets

@dataclass
class Targets:
    label: str
    protein_min_per_kg: float
    protein_max_per_kg: float
    protein_min_g: int
    protein_max_g: int
    potassium_mg: int | None
    phosphorus_mg: int | None
    sodium_mg: int | None
    fluid_ml: int | None
    kcal_per_kg: float
    calories_kcal: int
    carbs_g: int
    carbs_per_meal_g: int
    calcium_mg: int | None


def find_row(rows: list[dict], stage: str, dialysis: str) -> dict:
    for row in rows:
        if str(row["stage"]) == str(stage) and row["dialysis"] == dialysis:
            return row
    raise SystemExit(f"targets_by_stage.json has no row for stage {stage!r}, dialysis {dialysis!r}")


def targets_for(row: dict, weight_kg: float, diabetes: str = "type1") -> Targets:
    pmin, pmax = float(row["protein_g_per_kg_min"]), float(row["protein_g_per_kg_max"])
    if diabetes != "none" and row["dialysis"] == "none" and str(row["stage"]) in DIABETES_FLOOR_STAGES:
        pmin = max(pmin, 0.8)
        pmax = max(pmax, pmin)
    kcal = int(half_up(float(row["calories_kcal_per_kg"]) * weight_kg, -1))  # nearest 10, as note 05
    carbs = int(half_up(kcal * 0.45 / 4))
    per_meal = max(15, int(half_up(carbs / 4 / 5)) * 5)
    return Targets(
        label=STAGE_LABELS.get((str(row["stage"]), row["dialysis"]), f"{row['stage']} {row['dialysis']}"),
        protein_min_per_kg=pmin, protein_max_per_kg=pmax,
        protein_min_g=int(half_up(pmin * weight_kg)), protein_max_g=int(half_up(pmax * weight_kg)),
        potassium_mg=row.get("potassium_mg"), phosphorus_mg=row.get("phosphorus_mg"),
        sodium_mg=row.get("sodium_mg"), fluid_ml=row.get("fluid_ml"),
        kcal_per_kg=float(row["calories_kcal_per_kg"]), calories_kcal=kcal, carbs_g=carbs,
        carbs_per_meal_g=per_meal, calcium_mg=row.get("calcium_mg"))


def render_targets_table(rows: list[dict], weight_kg: float = 70.0) -> str:
    order = [("1", "none"), ("2", "none"), ("3a", "none"), ("3b", "none"), ("4", "none"), ("5", "none"),
             ("5", "hemodialysis"), ("5", "peritoneal")]
    out = [MARKER, "",
           f"| Stage | Protein per kg (for {weight_kg:g} kg) | Potassium mg ¹ | Phosphorus mg ² | Sodium mg | "
           f"Fluid mL | Energy per kg (for {weight_kg:g} kg) | Calcium mg ³ |",
           "|---|---|---|---|---|---|---|---|"]
    merged: list[tuple[str, Targets]] = []
    for key in order:
        t = targets_for(find_row(rows, *key), weight_kg)
        label = t.label
        if merged and key in {("2", "none")} and merged[-1][0] == "G1" and _same(merged[-1][1], t):
            merged[-1] = ("G1–G2", t)
            continue
        merged.append((label, t))
    for label, t in merged:
        if t.protein_min_g == t.protein_max_g:
            protein = f"{t.protein_min_per_kg:.1f} g/kg (about {t.protein_min_g} g)"
        else:
            protein = (f"{t.protein_min_per_kg:.1f}–{t.protein_max_per_kg:.1f} g/kg "
                       f"({t.protein_min_g}–{t.protein_max_g} g)")
        fluid = "no set limit" if t.fluid_ml is None else f"{t.fluid_ml:,} ⁴"
        out.append(f"| {label} | {protein} | {_lim(t.potassium_mg)} | {_lim(t.phosphorus_mg)} | "
                   f"< {t.sodium_mg:,} | {fluid} | {t.kcal_per_kg:g} kcal/kg (about {t.calories_kcal:,} kcal) | "
                   f"{_lim(t.calcium_mg)} |")
    out += [
        "",
        "¹ A **review ceiling**, not a prescription: only restrict potassium if your blood potassium is high; "
        "your care team sets the number. ",
        "² Used when blood phosphate runs high; phosphate additives count most (see the Phosphorus page). ",
        "³ Total from food, supplements and calcium-based binders. ",
        "⁴ Hemodialysis: 1,000 mL plus your measured urine output (1,500 mL assumes about 500 mL of urine). "
        "Peritoneal dialysis: set from your urine output and ultrafiltration.",
        "",
        "Protein: with diabetes, never below 0.8 g/kg before dialysis (ADA 2026 Rec 11.3; KDIGO 2022 and 2024). "
        "Without diabetes, KDOQI 2020 allows 0.6–0.8 g/kg only under close clinical supervision. "
        f"\"Per kg\" means per kg of a reference weight your team chooses; the {weight_kg:g} kg column is an example. "
        "Energy: KDOQI 2020 gives 25–35 kcal/kg; on peritoneal dialysis subtract the calories absorbed from the "
        "dialysis fluid (often 400 or more a day).",
        "",
    ]
    return "\n".join(out)


def _same(a: Targets, b: Targets) -> bool:
    return (a.protein_min_g, a.protein_max_g, a.potassium_mg, a.phosphorus_mg, a.sodium_mg, a.fluid_ml,
            a.calories_kcal, a.calcium_mg) == (b.protein_min_g, b.protein_max_g, b.potassium_mg, b.phosphorus_mg,
                                               b.sodium_mg, b.fluid_ml, b.calories_kcal, b.calcium_mg)


def _lim(value) -> str:
    return "–" if value is None else f"≤ {int(value):,}"


# ----------------------------------------------------------------------------- sources

def render_sources_include(sources: dict) -> str:
    lines = [MARKER, "<!-- Reference-link definitions for every id in handbook/sources.yml. -->", ""]
    for sid, entry in sources.items():
        title = str(entry.get("short") or entry["cite"]).replace('"', "'")
        lines.append(f'[{sid}]: {entry["url"]} "{title}"')
    return "\n".join(lines) + "\n"


KIND_TITLES = [
    ("guideline", "Guidelines"), ("consensus", "Consensus statements"), ("study", "Studies"),
    ("review", "Reviews"), ("label", "Product labels"), ("government", "Government and regulators"),
    ("patient-info", "Patient information from charities and providers"), ("data", "Food data"),
    ("tool", "Tools and standards"), ("project", "This project"),
]


def render_reference_sources(sources: dict, last_checked: str) -> str:
    meta = {
        "title": "Sources",
        "description": "Every source the handbook cites, with its link, licence and the date it was last checked.",
        "slug": "sources", "audience": ["clinician", "patient", "caregiver"], "applies_to": ["all"],
        "status": "draft", "reviewed_by": "", "reviewed_on": None, "last_checked": last_checked, "sources": [],
    }
    out = [front_matter(meta), MARKER, "", "# Sources", "",
           "Pages cite these by id, for example `[KDIGO 2024 CKD guideline][K24]`. The list is generated from "
           "`handbook/sources.yml`; to add or correct a source, edit that file "
           "(see [Building the handbook](../self-hosting/building-the-handbook.md)). "
           "**Licence** says what the handbook may do with each source: KDIGO guidelines are CC BY-NC-ND, so we "
           "cite and paraphrase them and never adapt their tables or figures; pages from kidney charities and "
           "dialysis providers are linked and paraphrased, never copied.", ""]
    for kind, title in KIND_TITLES:
        items = [(sid, e) for sid, e in sources.items() if e.get("kind") == kind]
        if not items:
            continue
        out += [f"## {title}", ""]
        for sid, e in items:
            extra = ""
            if e.get("also"):
                extra = " Also: " + ", ".join(f"<{u}>" for u in e["also"]) + "."
            dg = ""
            if e.get("dg"):
                dg = " Diet-guide source " + ", ".join(str(n) for n in e["dg"]) + "."
            note = f" *{e['note']}*" if e.get("note") else ""
            out.append(f"- **{sid}**: {e['cite']} <{e['url']}>{extra}  ")
            out.append(f"  Licence: {e['licence']}. Checked {e['checked']}.{dg}{note}")
        out.append("")
    unknown = [sid for sid, e in sources.items() if e.get("kind") not in dict(KIND_TITLES)]
    if unknown:
        raise SystemExit(f"sources.yml: unknown kind for {unknown}")
    return "\n".join(out)


# ----------------------------------------------------------------------------- amounts

_FRACTIONS = [(1 / 8, "⅛"), (1 / 4, "¼"), (1 / 3, "⅓"), (1 / 2, "½"), (2 / 3, "⅔"), (3 / 4, "¾")]
_SERVING_RE = re.compile(r"^(?P<qty>\d+-\d+/\d+|\d+/\d+|\d+(?:\.\d+)?)\s+(?P<rest>.*?)\s*\((?P<g>[\d.]+) g\)$")
_PLURAL = {"slice": "slices", "cup": "cups", "tortilla": "tortillas", "muffin": "muffins", "bagel": "bagels",
           "roll": "rolls", "stalk": "stalks", "clove": "cloves", "pepper": "peppers", "fruit": "fruits",
           "container": "containers", "packet": "packets", "piece": "pieces", "bar": "bars", "pop": "pops",
           "bottle": "bottles", "can": "cans", "glass": "glasses", "tube": "tubes", "tablet": "tablets",
           "cookie": "cookies", "pie": "pies", "bowl": "bowls", "serving": "servings", "egg": "eggs",
           "pancake": "pancakes", "waffle": "waffles", "cake": "cakes", "cracker": "crackers", "wafer": "wafers",
           "rectangle": "rectangles", "breast": "breasts", "fillet": "fillets", "ear": "ears", "spear": "spears"}
_SINGULAR = {v: k for k, v in _PLURAL.items()}
_SINGULAR.update({"cherries": "cherry", "halves": "half", "dates": "date", "prunes": "prune"})


def nice_number(x: float) -> str:
    whole = int(x + 1e-9)
    frac = x - whole
    if frac < 0.02:
        return str(whole)
    if frac > 0.98:
        return str(whole + 1)
    for value, glyph in _FRACTIONS:
        if abs(frac - value) < 0.02:
            return (str(whole) if whole else "") + glyph
    return f"{x:.1f}".rstrip("0").rstrip(".")


def parse_qty(text: str) -> float:
    if "-" in text:
        whole, frac = text.split("-", 1)
        return float(whole) + parse_qty(frac)
    if "/" in text:
        num, den = text.split("/", 1)
        return float(num) / float(den)
    return float(text)


def amount_text(food: dict, servings: float) -> str:
    """Household amount for `servings` of `food` ("2½ oz cooked (71 g)", "1½ cups (237 g)")."""
    grams = float(food["serving_g"]) * servings
    g_txt = f"{int(half_up(grams)):,} g"
    category = food.get("category", "")
    m = _SERVING_RE.match(food["serving_desc"])
    if not m:
        return f"{nice_number(servings)} × {food['serving_desc']}"
    qty = parse_qty(m.group("qty"))
    rest = m.group("rest")
    unit, _, extra = rest.partition(",")
    unit, extra = unit.strip(), extra.strip()
    words = unit.split()
    is_egg = "egg" in food["name"].lower()
    if (category in ("Meat, Poultry & Eggs", "Fish & Seafood") and not is_egg) or unit == "oz":
        oz = round(grams / 28.3495 * 2) / 2
        return f"{nice_number(oz)} oz ({g_txt})"
    amount = qty * servings
    if words:
        last = words[-1]
        if amount > 1 + 1e-9 and last in _PLURAL:
            words[-1] = _PLURAL[last]
        elif amount <= 1 + 1e-9 and last in _SINGULAR:
            words[-1] = _SINGULAR[last]
    unit_txt = " ".join(words)
    keep_extra = extra and (abs(servings - 1) < 1e-9 or not re.search(r"\d", extra))
    text = f"{nice_number(amount)} {unit_txt}".strip()
    if keep_extra:
        text += f", {extra}"
    return f"{text} ({g_txt})"


# ----------------------------------------------------------------------------- menus

@dataclass
class ItemResult:
    food: dict
    servings: float
    note: str
    totals: dict


@dataclass
class MealResult:
    meal: str
    label: str
    items: list[ItemResult]
    totals: dict


@dataclass
class DayResult:
    name: str
    label: str
    note: str
    dialysis_day: bool | None
    meals: list[MealResult]
    totals: dict
    problems: list[str] = field(default_factory=list)


@dataclass
class MenuResult:
    spec: dict
    targets: Targets
    limits: dict
    days: list[DayResult]
    problems: list[str] = field(default_factory=list)


def _zero() -> dict:
    return {k: 0.0 for k in NUTRIENTS}


def _add(acc: dict, other: dict) -> None:
    for k in NUTRIENTS:
        acc[k] += other.get(k, 0.0)


def item_totals(food: dict, servings: float) -> dict:
    n = food["nutrients"]
    return {k: float(n.get(k) or 0.0) * servings for k in NUTRIENTS}


def menu_limits(spec: dict, t: Targets, weight_kg: float) -> dict:
    """The numbers every day of this menu is checked against."""
    tol = float(spec.get("protein_about_tolerance_pct", 5)) / 100
    pmin = float(t.protein_min_g)
    pmax = float(t.protein_max_g)
    if t.protein_min_g == t.protein_max_g:  # "about X g/day" (note 05 §4.8): at least X, at most X + tol
        pmax = pmin * (1 + tol)
    energy = spec.get("energy_kcal") or [25 * weight_kg, 35 * weight_kg]
    per_meal = int(spec["carbs_per_meal_g"])
    meal_tol = float(spec.get("carb_tolerance_g", 10))
    if meal_tol > 10:
        raise SystemExit(f"menu {spec['id']}: carb_tolerance_g must be at most 10 (note 08 §4.5)")
    return {
        "protein_g": (pmin, pmax),
        "potassium_mg": t.potassium_mg if spec.get("potassium_limit", True) else None,
        "phosphorus_mg": t.phosphorus_mg if spec.get("phosphorus_limit", True) else None,
        "sodium_mg": t.sodium_mg,
        "fluid_ml": t.fluid_ml,
        "calories_kcal": (float(energy[0]), float(energy[1])),
        "carbs_per_meal_g": (per_meal - meal_tol, per_meal + meal_tol),
        "snack_carbs_g": tuple(spec.get("snack_carbs_g", [10, 30])),
        # ADA 2026 Rec 5.24: at least 14 g fibre per 1,000 kcal (used by the stage 1-2 menu)
        "fiber_per_1000_kcal": spec.get("fiber_min_per_1000_kcal"),
    }


# Menu rules beyond the targets (menus.yml `rules:`), with the text shown on the menu page.
RULE_TEXT = {
    "no_phosphate_additive": "no foods with phosphate additives",
    "no_grapefruit": "no grapefruit, pomelo or Seville orange (they change the blood levels of some transplant medicines)",
    "transplant_food_safety": ("no foods that need extra care with a weakened immune system (smoked fish, deli meats, "
                               "hot dogs, raw shellfish); everything is cooked through"),
}
# Grapefruit and its relatives raise the blood levels of tacrolimus, cyclosporine and others (FDA consumer update).
GRAPEFRUIT_WORDS = ("grapefruit", "pomelo", "seville", "tangelo")
# Foods a transplant menu leaves out (FoodSafety.gov; USDA-FDA "Food safety for transplant recipients"):
# refrigerated smoked seafood, deli and luncheon meats and hot dogs unless reheated until steaming, raw shellfish.
TRANSPLANT_UNSAFE = {171985, 173863, 172941, 174614, 172013, 174582, 174575, 167914, 171980, 171975}


def evaluate_menu(spec: dict, foods: dict[int, dict], rows: list[dict], person: dict) -> MenuResult:
    weight = float(person["weight_kg"])
    row = find_row(rows, str(spec["targets_row"]["stage"]), spec["targets_row"]["dialysis"])
    t = targets_for(row, weight, person.get("diabetes", "type1"))
    if spec.get("targets_label"):  # e.g. the transplant menu uses the stage 1-2 row
        t.label = str(spec["targets_label"])
    limits = menu_limits(spec, t, weight)
    unknown_rules = set(spec.get("rules", [])) - set(RULE_TEXT)
    if unknown_rules:
        raise SystemExit(f"menu {spec['id']}: unknown rules {sorted(unknown_rules)}")
    rules = set(spec.get("rules", []))
    result = MenuResult(spec=spec, targets=t, limits=limits, days=[])
    if len(spec.get("days", [])) != 7:
        result.problems.append(f"menu {spec['id']}: expected 7 days, found {len(spec.get('days', []))}")
    for day in spec.get("days", []):
        d = DayResult(name=day["name"], label=day.get("label", ""), note=day.get("note", ""),
                      dialysis_day=day.get("dialysis_day"), meals=[], totals=_zero())
        for meal in day["meals"]:
            mr = MealResult(meal=meal["meal"], label=meal.get("label") or MEAL_TITLES[meal["meal"]], items=[],
                            totals=_zero())
            if meal["meal"] not in MEAL_TITLES:
                d.problems.append(f"unknown meal {meal['meal']!r}")
            for item in meal["items"]:
                fdc = int(item["fdc_id"])
                food = foods.get(fdc)
                if food is None:
                    d.problems.append(f"fdc_id {fdc} is not in data/foods.json")
                    continue
                servings = float(item["servings"])
                if servings <= 0:
                    d.problems.append(f"{food['name']}: servings must be > 0")
                flags = set(food.get("flags", []))
                if "avoid_ckd" in flags:
                    d.problems.append(f"{food['name']} is flagged avoid_ckd")
                if "hypo_treatment" in flags:
                    d.problems.append(f"{food['name']} is a hypo treatment; keep rescue foods out of menus")
                if "no_phosphate_additive" in rules and "phosphate_additive" in flags:
                    d.problems.append(f"{food['name']} has a phosphate additive")
                if "no_grapefruit" in rules and any(w in food["name"].lower() for w in GRAPEFRUIT_WORDS):
                    d.problems.append(f"{food['name']}: no grapefruit or its relatives on this menu")
                if "transplant_food_safety" in rules and fdc in TRANSPLANT_UNSAFE:
                    d.problems.append(f"{food['name']} needs extra food-safety care after a transplant")
                tot = item_totals(food, servings)
                mr.items.append(ItemResult(food=food, servings=servings, note=item.get("note", ""), totals=tot))
                _add(mr.totals, tot)
            d.meals.append(mr)
            _add(d.totals, mr.totals)
        _check_day(d, limits)
        result.days.append(d)
    if spec.get("dialysis_days"):
        kinds = {d.dialysis_day for d in result.days}
        if kinds != {True, False}:
            result.problems.append(f"menu {spec['id']}: needs both dialysis-day and non-dialysis-day variants")
    return result


def _check_day(d: DayResult, limits: dict) -> None:
    tot = d.totals
    lo, hi = limits["protein_g"]
    if not (lo - 1e-9 <= tot["protein_g"] <= hi + 1e-9):
        d.problems.append(f"protein {tot['protein_g']:.1f} g outside {lo:g}–{hi:g}")
    for key in ("potassium_mg", "phosphorus_mg", "sodium_mg", "fluid_ml"):
        cap = limits.get(key)
        if cap is not None and tot[key] > cap + 1e-9:
            d.problems.append(f"{key} {tot[key]:.0f} over {cap}")
    lo, hi = limits["calories_kcal"]
    if not (lo <= tot["calories_kcal"] <= hi):
        d.problems.append(f"energy {tot['calories_kcal']:.0f} kcal outside {lo:.0f}–{hi:.0f}")
    fib = limits.get("fiber_per_1000_kcal")
    if fib and tot["fiber_g"] + 1e-9 < float(fib) * tot["calories_kcal"] / 1000:
        d.problems.append(f"fibre {tot['fiber_g']:.1f} g under {fib:g} g per 1,000 kcal "
                          f"({float(fib) * tot['calories_kcal'] / 1000:.1f} g)")
    clo, chi = limits["carbs_per_meal_g"]
    slo, shi = limits["snack_carbs_g"]
    seen = set()
    for m in d.meals:
        c = m.totals["carbs_g"]
        if m.meal in MAIN_MEALS:
            seen.add(m.meal)
            if not (clo - 1e-9 <= c <= chi + 1e-9):
                d.problems.append(f"{m.label} carbohydrate {c:.1f} g outside {clo:g}–{chi:g}")
        elif m.meal == "snack" and c > 0.5 and not (slo - 1e-9 <= c <= shi + 1e-9):
            # a drinks-only "snack" (water, tea) has no carbohydrate and needs no insulin plan
            d.problems.append(f"{m.label} carbohydrate {c:.1f} g outside {slo:g}–{shi:g}")
    missing = set(MAIN_MEALS) - seen
    if missing:
        d.problems.append(f"missing meals: {', '.join(sorted(missing))}")


def _fluid(v: float) -> str:
    return fmt_int(v) if v > 0.5 else "–"


def render_menu_page(res: MenuResult, person: dict, last_checked: str, fact_checked=None) -> str:
    spec, t, lim = res.spec, res.targets, res.limits
    meta = with_fact_check({
        "title": spec["title"], "description": spec["description"], "slug": f"menu-{spec['id']}",
        "audience": ["patient", "caregiver"], "applies_to": spec["applies_to"], "status": "draft",
        "reviewed_by": "", "reviewed_on": None, "last_checked": last_checked, "sources": spec["sources"],
    }, fact_checked)
    pmin, pmax = lim["protein_g"]
    if t.protein_min_g == t.protein_max_g:
        protein_goal = f"about {t.protein_min_g} g ({t.protein_min_per_kg:.1f} g/kg); days stay within {pmin:g}–{fmt_1(pmax)} g"
    else:
        protein_goal = f"{t.protein_min_g}–{t.protein_max_g} g ({t.protein_min_per_kg:.1f}–{t.protein_max_per_kg:.1f} g/kg)"
    elo, ehi = lim["calories_kcal"]
    clo, chi = lim["carbs_per_meal_g"]
    out = [front_matter(meta), MARKER, "", f"# {spec['title']}", "",
           '--8<-- "includes/starting-points.md"', "",
           spec["intro"].strip(), "",
           "## The numbers this menu is built to", "",
           f"Built for a reference adult: {person['weight_kg']:g} kg, {person['height_cm']:g} cm, type 1 diabetes, "
           f"using the app's starting targets for **{t.label}** (see [Eating well](../index.md#your-numbers)). "
           "Every day below was checked against these numbers by `scripts/build_handbook.py`.", "",
           "| Per day | Built to |", "|---|---|",
           f"| Protein | {protein_goal} |"]
    for key, label in (("potassium_mg", "Potassium"), ("phosphorus_mg", "Phosphorus"), ("sodium_mg", "Sodium")):
        if lim.get(key) is not None:
            out.append(f"| {label} | at most {lim[key]:,} mg |")
    if lim.get("fluid_ml") is not None:
        out.append(f"| Fluid (drinks and foods that are liquid at room temperature) | at most {lim['fluid_ml']:,} mL |")
    for key, label in (("potassium_mg", "Potassium"), ("phosphorus_mg", "Phosphorus")):
        if lim.get(key) is None:
            out.append(f"| {label} | no limit (shown for information) |")
    out.append(f"| Energy from food | {elo:,.0f}–{ehi:,.0f} kcal |")
    out.append(f"| Carbohydrate | about {spec['carbs_per_meal_g']} g at each main meal (every meal "
               f"{clo:g}–{chi:g} g); snacks {lim['snack_carbs_g'][0]:g}–{lim['snack_carbs_g'][1]:g} g |")
    if lim.get("fiber_per_1000_kcal"):
        out.append(f"| Fibre | at least {lim['fiber_per_1000_kcal']:g} g per 1,000 kcal |")
    out.append("")
    if spec.get("rules"):
        out += ["Also: " + "; ".join(RULE_TEXT[r] for r in spec["rules"]) + ".", ""]
    out += ["## Week at a glance", "",
            "| Day | Energy kcal | Carb g | Protein g | Potassium mg | Phosphorus mg | Sodium mg | Fluid mL | Fibre g |",
            "|---|---|---|---|---|---|---|---|---|"]
    for d in res.days:
        tt = d.totals
        name = d.name + (f" ({d.label})" if d.label else "")
        out.append(f"| {name} | {fmt_int(tt['calories_kcal'])} | {fmt_int(tt['carbs_g'])} | {fmt_1(tt['protein_g'])} | "
                   f"{fmt_int(tt['potassium_mg'])} | {fmt_int(tt['phosphorus_mg'])} | {fmt_int(tt['sodium_mg'])} | "
                   f"{_fluid(tt['fluid_ml'])} | {fmt_1(tt['fiber_g'])} |")
    out.append("")
    out += ["Amounts are what goes on the plate; meat and fish are cooked weights. Values are USDA FoodData "
            "Central (SR Legacy) figures from the app's food list, so every food can be found in the app by name "
            "and logged as shown. Brands vary: when a food has a label, the label wins.", ""]
    for d in res.days:
        heading = d.name + (f": {d.label}" if d.label else "")
        out += [f"## {heading}", ""]
        if d.note:
            out += [d.note.strip(), ""]
        out += ['<div class="kh-numbers" markdown>', "",
                "| Meal | Food | Amount | Carb g | Protein g | Potassium mg | Phosphorus mg | Sodium mg | Fluid mL |",
                "|---|---|---|---|---|---|---|---|---|"]
        for m in d.meals:
            first = True
            for it in m.items:
                show_note = it.note and it.note.lower() not in it.food["name"].lower()
                name = it.food["name"] + (f" ({it.note})" if show_note else "")
                tt = it.totals
                out.append(f"| {('**' + m.label + '**') if first else ''} | {md_cell(name)} | "
                           f"{md_cell(amount_text(it.food, it.servings))} | {fmt_int(tt['carbs_g'])} | "
                           f"{fmt_1(tt['protein_g'])} | {fmt_int(tt['potassium_mg'])} | "
                           f"{fmt_int(tt['phosphorus_mg'])} | {fmt_int(tt['sodium_mg'])} | {_fluid(tt['fluid_ml'])} |")
                first = False
            mt = m.totals
            out.append(f"| | *{m.label} total* | | *{fmt_int(mt['carbs_g'])}* | *{fmt_1(mt['protein_g'])}* | "
                       f"*{fmt_int(mt['potassium_mg'])}* | *{fmt_int(mt['phosphorus_mg'])}* | "
                       f"*{fmt_int(mt['sodium_mg'])}* | *{_fluid(mt['fluid_ml'])}* |")
        tt = d.totals
        out.append(f"| **Day** | **{fmt_int(tt['calories_kcal'])} kcal** | | **{fmt_int(tt['carbs_g'])}** | "
                   f"**{fmt_1(tt['protein_g'])}** | **{fmt_int(tt['potassium_mg'])}** | "
                   f"**{fmt_int(tt['phosphorus_mg'])}** | **{fmt_int(tt['sodium_mg'])}** | **{_fluid(tt['fluid_ml'])}** |")
        out += ["", "</div>", ""]
    if spec.get("swaps"):
        out += ["## Swaps that keep the numbers", ""]
        out += [f"- {s}" for s in spec["swaps"]]
        out.append("")
    out += ["## Make it yours", ""]
    out += [f"- {s}" for s in spec.get("make_it_yours", [])]
    out += ["", "## Sources", ""]
    out += [f"- {s}" for s in spec["source_lines"]]
    out.append("")
    return "\n".join(out)


def render_menus_overview(results: list[MenuResult]) -> str:
    out = [MARKER, "",
           "| Menu | Protein g/day | Potassium mg/day | Phosphorus mg/day | Sodium mg/day | Fluid mL/day | "
           "Carb g per main meal |",
           "|---|---|---|---|---|---|---|"]
    for r in results:
        days = r.days
        def rng(key, fmt=fmt_int):
            vals = [d.totals[key] for d in days]
            return f"{fmt(min(vals))}–{fmt(max(vals))}"
        meals = [m.totals["carbs_g"] for d in days for m in d.meals if m.meal in MAIN_MEALS]
        fluid = rng("fluid_ml") if r.limits.get("fluid_ml") is not None else "no limit (" + rng("fluid_ml") + ")"
        out.append(f"| [{r.spec['short_title']}]({r.spec['id']}.md) | {rng('protein_g', fmt_1)} | {rng('potassium_mg')} | "
                   f"{rng('phosphorus_mg')} | {rng('sodium_mg')} | {fluid} | "
                   f"{fmt_int(min(meals))}–{fmt_int(max(meals))} |")
    out += ["", "Ranges are the lowest and highest day of each 7-day menu.", ""]
    return "\n".join(out)


def render_grocery_lists(results: list[MenuResult], menus: dict, last_checked: str) -> str:
    sources = menus["grocery"]["sources"]
    order = ["G1-G2", "G3a", "G3b", "G4", "G5", "HD", "HHD", "PD", "Tx"]
    stages = {s for r in results for s in r.spec["applies_to"]}
    meta = with_fact_check({
        "title": "Grocery lists for the sample menus",
        "description": "Printable weekly shopping checklists for each 7-day sample menu, with staples and what to check on labels.",
        "slug": "grocery-lists", "audience": ["patient", "caregiver"],
        "applies_to": [s for s in order if s in stages], "status": "draft", "reviewed_by": "",
        "reviewed_on": None, "last_checked": last_checked, "sources": sources,
    }, menus.get("fact_checked"))
    out = [front_matter(meta), MARKER, "", "# Grocery lists for the sample menus", "",
           menus["grocery"]["intro"].strip(), ""]
    for r in results:
        out += [f"## {r.spec['short_title']}", "",
                f"For one person for 7 days of the [{r.spec['short_title']}](menus/{r.spec['id']}.md) menu. "
                "Amounts are what the menu serves; buy a little more for cooking loss "
                "(raw meat and fish shrink by about a quarter when cooked).", ""]
        totals: dict[int, float] = {}
        for d in r.days:
            for m in d.meals:
                for it in m.items:
                    fdc = int(it.food["fdc_id"])
                    totals[fdc] = totals.get(fdc, 0.0) + it.servings
        foods = {int(it.food["fdc_id"]): it.food for d in r.days for m in d.meals for it in m.items}
        by_cat: dict[str, list[tuple[str, str]]] = {}
        for fdc, servings in totals.items():
            food = foods[fdc]
            if fdc in NOT_SHOPPED:
                continue
            by_cat.setdefault(food["category"], []).append((food["name"], amount_text(food, servings)))
        for cat in CATEGORY_ORDER:
            if cat not in by_cat:
                continue
            out += [f"**{cat}**", ""]
            out += [f"- [ ] {md_cell(name)}: {md_cell(amount)}" for name, amount in sorted(by_cat[cat])]
            out.append("")
    out += ["## Staples for every menu", ""]
    out += [f"- [ ] {s}" for s in menus["grocery"]["staples"]]
    out += ["", '!!! tip "Check the label for"', ""]
    out += [f"    - {s}" for s in menus["grocery"]["check_label"]]
    out += ["", "## Sources", ""]
    out += [f"- {s}" for s in menus["grocery"]["source_lines"]]
    out.append("")
    return "\n".join(out)


# ----------------------------------------------------------------------------- recipes

# Per-serving rules for recipes (handbook/data/recipes.yml), by course. Every recipe must stay under the
# sodium line; the tags are checked against the potassium, phosphorus and protein lines.
#   meal:  600 mg sodium or potassium per meal is the renal-diet review line (University of Michigan
#          handout, DG47); 300 mg phosphorus is a third of the stage 5 starting ceiling of 900 mg a day.
#   snack: 140 mg sodium is FDA "low sodium" (DG37a); 200 mg potassium is NKF's "high" line (DG5);
#          100 mg phosphorus is AKF's "low" line (DG46b).
RECIPE_LIMITS = {
    "meal": {"sodium_mg": 600, "potassium_mg": 600, "phosphorus_mg": 300, "protein_g": 20, "fluid_ml": 120},
    "snack": {"sodium_mg": 140, "potassium_mg": 200, "phosphorus_mg": 100, "protein_g": 0, "fluid_ml": 120},
}
COURSES = {"breakfast": "meal", "lunch": "meal", "dinner": "meal", "snack": "snack", "dessert": "snack"}
COURSE_TITLES = {"breakfast": "Breakfasts", "lunch": "Lunches", "dinner": "Dinners", "snack": "Snacks and desserts",
                 "dessert": "Snacks and desserts"}
RECIPE_TAGS = {
    "lower-potassium": "Lower potassium",
    "lower-phosphorus": "Lower phosphorus",
    "dialysis-friendly": "Dialysis-friendly",
    "freezer": "Freezes well",
    "make-ahead": "Make ahead",
    "vegetarian": "Vegetarian",
}


@dataclass
class IngredientResult:
    name: str
    text: str
    grams: float
    in_app: bool
    totals: dict


@dataclass
class RecipeResult:
    spec: dict
    ingredients: list[IngredientResult]
    total: dict
    per_serving: dict
    seasoning_k_mg: float
    problems: list[str] = field(default_factory=list)


def evaluate_recipe(spec: dict, foods: dict[int, dict], extras: dict[int, dict]) -> RecipeResult:
    serves = float(spec["serves"])
    course = COURSES.get(spec.get("course", ""))
    problems: list[str] = []
    if course is None:
        problems.append(f"recipe {spec['id']}: course must be one of {sorted(COURSES)}")
        course = "meal"
    ingredients: list[IngredientResult] = []
    total = _zero()
    seasoning_k = 0.0
    for item in spec["ingredients"]:
        fdc, grams = int(item["fdc_id"]), float(item["grams"])
        if grams <= 0:
            problems.append(f"recipe {spec['id']}: {item.get('text')}: grams must be > 0")
        food = foods.get(fdc)
        if food is not None:
            per_g = {k: float(food["nutrients"].get(k) or 0.0) / float(food["serving_g"]) for k in NUTRIENTS}
            flags = set(food.get("flags", []))
            for bad in ("avoid_ckd", "phosphate_additive"):
                if bad in flags:
                    problems.append(f"recipe {spec['id']}: {food['name']} is flagged {bad}")
            name, in_app = food["name"], True
        elif fdc in extras:
            per_g = {k: float(extras[fdc]["per_100g"].get(k) or 0.0) / 100 for k in NUTRIENTS}
            name, in_app = extras[fdc]["name"], False
        else:
            problems.append(f"recipe {spec['id']}: fdc_id {fdc} is in neither data/foods.json nor extra_foods")
            continue
        tot = {k: per_g[k] * grams for k in NUTRIENTS}
        if item.get("counts_as_fluid") is False:  # milk or water cooked into a solid food (batter, rice)
            tot["fluid_ml"] = 0.0
        if not in_app:
            seasoning_k += tot["potassium_mg"]
        _add(total, tot)
        ingredients.append(IngredientResult(name=name, text=str(item["text"]), grams=grams, in_app=in_app, totals=tot))
    per = {k: v / serves for k, v in total.items()}
    lim = RECIPE_LIMITS[course]
    if per["sodium_mg"] > lim["sodium_mg"] + 1e-9:
        problems.append(f"recipe {spec['id']}: sodium {per['sodium_mg']:.0f} mg per serving is over {lim['sodium_mg']}")
    tags = set(spec.get("tags", []))
    unknown = tags - set(RECIPE_TAGS)
    if unknown:
        problems.append(f"recipe {spec['id']}: unknown tags {sorted(unknown)}")
    lower_k = per["potassium_mg"] <= lim["potassium_mg"] + 1e-9
    lower_p = per["phosphorus_mg"] <= lim["phosphorus_mg"] + 1e-9
    if "lower-potassium" in tags and not lower_k:
        problems.append(f"recipe {spec['id']}: tagged lower-potassium but has {per['potassium_mg']:.0f} mg")
    if "lower-phosphorus" in tags and not lower_p:
        problems.append(f"recipe {spec['id']}: tagged lower-phosphorus but has {per['phosphorus_mg']:.0f} mg")
    if "dialysis-friendly" in tags:
        if not (lower_k and lower_p and per["protein_g"] + 1e-9 >= lim["protein_g"]
                and per["fluid_ml"] <= lim["fluid_ml"] + 1e-9):
            problems.append(f"recipe {spec['id']}: tagged dialysis-friendly but misses a line "
                            f"(K {per['potassium_mg']:.0f}, P {per['phosphorus_mg']:.0f}, protein "
                            f"{per['protein_g']:.1f} g, fluid {per['fluid_ml']:.0f} mL)")
    if "vegetarian" in tags and any(f.get("category") in ("Meat, Poultry & Eggs", "Fish & Seafood")
                                    and "egg" not in f["name"].lower()
                                    for f in (foods.get(int(i["fdc_id"])) or {} for i in spec["ingredients"])):
        problems.append(f"recipe {spec['id']}: tagged vegetarian but has meat or fish")
    for key in ("title", "description", "steps", "carb_note"):
        if not spec.get(key):
            problems.append(f"recipe {spec['id']}: missing {key}")
    return RecipeResult(spec=spec, ingredients=ingredients, total=total, per_serving=per,
                        seasoning_k_mg=seasoning_k / serves, problems=problems)


def _choices(carbs: float) -> str:
    half = half_up(carbs / 15 * 2) / 2
    return nice_number(half)


def _grams_text(g: float) -> str:
    return f"{fmt_1(g)} g" if g < 10 else f"{fmt_int(g)} g"


def render_recipe_page(res: RecipeResult, data: dict, last_checked: str) -> str:
    spec, per = res.spec, res.per_serving
    course = COURSES[spec["course"]]
    lim = RECIPE_LIMITS[course]
    meta = with_fact_check({
        "title": spec["title"], "description": spec["description"], "slug": spec["id"],
        "audience": ["patient", "caregiver"], "applies_to": spec.get("applies_to", data["applies_to"]),
        "status": "draft", "reviewed_by": "", "reviewed_on": None, "last_checked": last_checked,
        "sources": list(dict.fromkeys(list(data["sources"]) + list(spec.get("sources", [])))),
    }, data.get("fact_checked"))
    tags = " · ".join(RECIPE_TAGS[t] for t in spec.get("tags", []))
    serves = nice_number(float(spec["serves"]))
    out = [front_matter(meta), MARKER, "", f"# {spec['title']}", "",
           spec["intro"].strip(), "",
           f"**Serves {serves}** · {spec['time']}" + (f" · {tags}" if tags else ""), "",
           '!!! abstract "Carbohydrate per serving"',
           f"    **{fmt_int(per['carbs_g'])} g carbohydrate** (about {_choices(per['carbs_g'])} carb choices of 15 g). "
           + spec["carb_note"].strip(), "",
           "## Per serving", "",
           '<div class="kh-numbers" markdown>', "",
           "| Energy | Carb | Protein | Potassium | Phosphorus | Sodium | Fluid | Fibre |",
           "|---|---|---|---|---|---|---|---|",
           f"| {fmt_int(per['calories_kcal'])} kcal | {fmt_int(per['carbs_g'])} g | {fmt_1(per['protein_g'])} g | "
           f"{fmt_int(per['potassium_mg'])} mg | {fmt_int(per['phosphorus_mg'])} mg | {fmt_int(per['sodium_mg'])} mg | "
           f"{fmt_int(per['fluid_ml']) + ' mL' if per['fluid_ml'] > 0.5 else 'none'} | {fmt_1(per['fiber_g'])} g |", "",
           "</div>", "",
           f"Checked by `scripts/build_handbook.py`: sodium at most {lim['sodium_mg']} mg per serving"
           + (f"; \"lower potassium\" means at most {lim['potassium_mg']} mg and \"lower phosphorus\" at most "
              f"{lim['phosphorus_mg']} mg per serving" ) + ". See [how recipes are checked](index.md#how-the-recipes-are-checked).", ""]
    if res.seasoning_k_mg >= 0.5:
        out += [f"Ingredients that are not in the app's food list (herbs, spices and a few others) add about "
                f"{fmt_int(res.seasoning_k_mg)} mg potassium per serving; they are counted above.", ""]
    out += ["## Ingredients", "",
            "| Ingredient | Amount | Grams |", "|---|---|---|"]
    for ing in res.ingredients:
        out.append(f"| {md_cell(ing.name)} | {md_cell(ing.text)} | {_grams_text(ing.grams)} |")
    out += ["", "## Steps", ""]
    out += [f"{n}. {s.strip()}" for n, s in enumerate(spec["steps"], 1)]
    out.append("")
    if spec.get("kidney_notes"):
        out += ["## Why it works for kidneys", ""]
        out += [f"- {s.strip()}" for s in spec["kidney_notes"]]
        out.append("")
    if spec.get("variations"):
        out += ["## Make it fit you", ""]
        out += [f"- {s.strip()}" for s in spec["variations"]]
        out.append("")
    app_foods = [i for i in res.ingredients if i.in_app and i.grams / float(spec["serves"]) >= 1]
    out += ["## Log it in the app", "",
            "Log one serving as these foods from the app's food list (grams per serving), or save them once as a "
            "meal ([Planning and menus](../../app/planning-and-menus.md)):", ""]
    out += [f"- {md_cell(i.name)}: {_grams_text(i.grams / float(spec['serves']))}" for i in app_foods]
    out += ["", "## Sources", ""]
    out += [f"- {s}" for s in data["source_lines"]]
    out += [f"- {s}" for s in spec.get("source_lines", [])]
    out.append("")
    return "\n".join(out)


def render_recipes_overview(results: list[RecipeResult]) -> str:
    out = [MARKER, ""]
    seen: list[str] = []
    for course in ("breakfast", "lunch", "dinner", "snack"):
        title = COURSE_TITLES[course]
        if title in seen:
            continue
        seen.append(title)
        group = [r for r in results if COURSE_TITLES[r.spec["course"]] == title]
        if not group:
            continue
        out += [f"**{title}**", "",
                '<div class="kh-numbers" markdown>', "",
                "| Recipe | Serves | Carb g | Protein g | Potassium mg | Phosphorus mg | Sodium mg | Tags |",
                "|---|---|---|---|---|---|---|---|"]
        for r in group:
            p = r.per_serving
            tags = ", ".join(RECIPE_TAGS[t] for t in r.spec.get("tags", []))
            out.append(f"| [{r.spec['title']}]({r.spec['id']}.md) | {nice_number(float(r.spec['serves']))} | "
                       f"{fmt_int(p['carbs_g'])} | {fmt_1(p['protein_g'])} | {fmt_int(p['potassium_mg'])} | "
                       f"{fmt_int(p['phosphorus_mg'])} | {fmt_int(p['sodium_mg'])} | {tags} |")
        out += ["", "</div>", ""]
    out += ["Numbers are per serving.", ""]
    return "\n".join(out)


def build_recipes(foods: dict[int, dict], sources: dict) -> tuple[dict[Path, str], list[RecipeResult], list[str]]:
    if not RECIPES_YML.exists():
        return {}, [], []
    data = load_yaml(RECIPES_YML)
    extras = {int(e["fdc_id"]): e for e in data.get("extra_foods", [])}
    problems: list[str] = []
    for fdc in extras:
        if fdc in foods:
            problems.append(f"recipes.yml: extra food {fdc} is already in data/foods.json; use that entry")
    results = [evaluate_recipe(spec, foods, extras) for spec in data["recipes"]]
    ids = [r.spec["id"] for r in results]
    if len(ids) != len(set(ids)):
        problems.append("recipes.yml: duplicate recipe ids")
    for r in results:
        problems += r.problems
        for sid in list(data["sources"]) + list(r.spec.get("sources", [])):
            if sid not in sources:
                problems.append(f"recipe {r.spec['id']}: unknown source id {sid}")
    last_checked = str(data["last_checked"])
    files = {DOCS / "eat" / "recipes" / "_overview.md": render_recipes_overview(results)}
    for r in results:
        files[DOCS / "eat" / "recipes" / f"{r.spec['id']}.md"] = render_recipe_page(r, data, last_checked)
    return files, results, problems


# ----------------------------------------------------------------------------- orchestration

def build_all() -> tuple[dict[Path, str], list[MenuResult], list[str]]:
    """Every generated file's content, the evaluated menus and any problems."""
    sources = load_sources()
    menus = load_yaml(MENUS_YML)
    foods = load_foods()
    rows = load_target_rows()
    person = menus["reference_person"]
    problems: list[str] = []
    h = float(person["height_cm"]) / 100
    bmi = float(person["weight_kg"]) / (h * h)
    if not (18.5 <= bmi <= 25):
        problems.append(f"reference person BMI {bmi:.1f} is outside 18.5–25; the reference weight would differ "
                        "from the actual weight (ARCHITECTURE.md 'Suggested targets')")
    last_checked = str(menus["last_checked"])
    results = [evaluate_menu(spec, foods, rows, person) for spec in menus["menus"]]
    for r in results:
        problems += r.problems
        for d in r.days:
            problems += [f"menu {r.spec['id']} {d.name}: {p}" for p in d.problems]
    for spec in menus["menus"]:
        for sid in spec["sources"]:
            if sid not in sources:
                problems.append(f"menu {spec['id']}: unknown source id {sid}")
    files = {
        HANDBOOK / "includes" / "sources.md": render_sources_include(sources),
        DOCS / "reference" / "sources.md": render_reference_sources(sources, last_checked),
        DOCS / "eat" / "_targets-table.md": render_targets_table(rows, float(person["weight_kg"])),
        DOCS / "eat" / "menus" / "_overview.md": render_menus_overview(results),
        DOCS / "eat" / "grocery-lists.md": render_grocery_lists(results, menus, last_checked),
    }
    for r in results:
        files[DOCS / "eat" / "menus" / f"{r.spec['id']}.md"] = render_menu_page(
            r, person, last_checked, menus.get("fact_checked"))
    recipe_files, _, recipe_problems = build_recipes(foods, sources)
    files.update(recipe_files)
    problems += recipe_problems
    return files, results, problems


def synced_assets() -> dict[Path, bytes]:
    """Assets copied from elsewhere: only present when their source is available here."""
    assets: dict[Path, bytes] = {}
    if APP_ICON.exists():
        assets[DOCS / "assets" / "icon.svg"] = APP_ICON.read_bytes()
    try:
        from importlib.metadata import distribution
        dist = distribution("mkdocs-material")
        # The theme's own licence, plus the licences of the two icon sets the site inlines
        # (mkdocs.yml: material/weather-* palette toggles, fontawesome/brands/github).
        wanted = {
            "LICENSE": "material-LICENSE.txt",                          # in *.dist-info
            "templates/.icons/material/LICENSE": "material-design-icons-LICENSE.txt",
            "templates/.icons/fontawesome/LICENSE.txt": "fontawesome-LICENSE.txt",
        }
        for f in dist.files or []:
            path = str(f).replace("\\", "/")
            for suffix, target in wanted.items():
                if suffix == "LICENSE":
                    match = f.name == "LICENSE" and ".dist-info" in path
                else:
                    match = path.endswith("material/" + suffix)
                if match:
                    assets[DOCS / "assets" / "licences" / target] = Path(dist.locate_file(f)).read_bytes()
    except Exception:  # mkdocs-material not installed: keep the committed copies
        pass
    return assets


def print_totals(results: list[MenuResult]) -> None:
    for r in results:
        lim = r.limits
        pl, ph = lim["protein_g"]
        print(f"\n== {r.spec['id']}: {r.spec['short_title']} ({r.targets.label}) ==")
        print(f"   limits: protein {pl:g}-{ph:.1f} g, K <= {lim['potassium_mg']}, P <= {lim['phosphorus_mg']}, "
              f"Na <= {lim['sodium_mg']}, fluid <= {lim['fluid_ml']}, kcal {lim['calories_kcal'][0]:.0f}-"
              f"{lim['calories_kcal'][1]:.0f}, main-meal carbs {lim['carbs_per_meal_g'][0]:g}-{lim['carbs_per_meal_g'][1]:g} g")
        print(f"   {'day':<34} {'kcal':>5} {'carb':>5} {'prot':>5} {'K':>5} {'P':>5} {'Na':>5} {'fluid':>5} {'fibre':>5}  meal carbs (B/L/D | snacks)  status")
        for d in r.days:
            t = d.totals
            mains = "/".join(fmt_int(m.totals["carbs_g"]) for m in d.meals if m.meal in MAIN_MEALS)
            snacks = ",".join(fmt_int(m.totals["carbs_g"]) for m in d.meals if m.meal == "snack")
            name = (d.name + (f" ({d.label})" if d.label else ""))[:34]
            status = "OK" if not d.problems else "FAIL: " + "; ".join(d.problems)
            print(f"   {name:<34} {t['calories_kcal']:5.0f} {t['carbs_g']:5.0f} {t['protein_g']:5.1f} "
                  f"{t['potassium_mg']:5.0f} {t['phosphorus_mg']:5.0f} {t['sodium_mg']:5.0f} {t['fluid_ml']:5.0f} "
                  f"{t['fiber_g']:5.1f}  {mains:<11} | {snacks:<10}  {status}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate files (default)")
    mode.add_argument("--check", action="store_true", help="exit 1 if a generated file is stale or a menu fails")
    mode.add_argument("--totals", action="store_true", help="print menu day totals and checks; write nothing")
    args = ap.parse_args(argv)

    files, results, problems = build_all()
    if args.totals:
        print_totals(results)
        _, recipes, _ = build_recipes(load_foods(), load_sources())
        if recipes:
            print("\n== recipes (per serving) ==")
            print(f"   {'recipe':<40} {'kcal':>5} {'carb':>5} {'prot':>5} {'K':>5} {'P':>5} {'Na':>5} {'fluid':>5} {'fibre':>5}  status")
            for r in recipes:
                p = r.per_serving
                status = "OK" if not r.problems else "FAIL: " + "; ".join(r.problems)
                print(f"   {r.spec['id'][:40]:<40} {p['calories_kcal']:5.0f} {p['carbs_g']:5.1f} {p['protein_g']:5.1f} "
                      f"{p['potassium_mg']:5.0f} {p['phosphorus_mg']:5.0f} {p['sodium_mg']:5.0f} {p['fluid_ml']:5.0f} "
                      f"{p['fiber_g']:5.1f}  {status}")
        for p in problems:
            print("PROBLEM:", p)
        return 1 if problems else 0

    status = 0
    if problems:
        for p in problems:
            print("menu check failed:", p, file=sys.stderr)
        status = 1

    stale = []
    for path, content in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
            diff = difflib.unified_diff((current or "").splitlines(), content.splitlines(),
                                        f"{path.relative_to(ROOT)} (committed)", "(regenerated)", lineterm="", n=1)
            print("\n".join(list(diff)[:40]), file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print("wrote", path.relative_to(ROOT))
    for path, data in synced_assets().items():
        if path.exists() and path.read_bytes() == data:
            continue
        if args.check:
            print(f"warning: {path.relative_to(ROOT)} differs from its source; run scripts/build_handbook.py",
                  file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print("synced", path.relative_to(ROOT))
    if stale:
        print(f"{len(stale)} generated file(s) are stale: run python scripts/build_handbook.py", file=sys.stderr)
        status = 1
    if args.check and status == 0:
        print(f"handbook generated files are up to date ({len(files)} files, {len(results)} menus checked)")
    return status


if __name__ == "__main__":
    sys.exit(main())
