"""Curated builtin food list for the kidney-health food log.

Each entry is a dict consumed by ``scripts/build_food_db.py``:

    {
        "fdc_id": 173944,            # USDA SR Legacy fdc_id (food.csv). Looked up, never guessed.
        "name": "Banana, raw",       # display name shown in the app
        "category": "Fruits",        # one of CATEGORIES (ARCHITECTURE.md, exact string)
        "serving_desc": "1 medium",  # household measure; the builder appends " (118 g)"
        "serving_g": 118,            # grams in one serving (from food_portion.csv when available)
        "flags": [],                 # subset of FLAGS (ARCHITECTURE.md, exact strings)
        "kidney_notes": "...",       # one practical sentence for limit/avoid foods, else None
        "role": "veg_fruit",         # optional: meal-guidance role override (one of ROLES), rarely needed
    }

Items that SR Legacy does not carry (glucose tablets, salt substitute, ...) use
``"manual_id": N`` plus ``"manual_nutrients": {...}`` (per serving, label-derived)
instead of ``fdc_id``.  The builder writes them with ``fdc_id = -N`` so the
backend's upsert-by-fdc_id still works and the id can never collide with USDA.

Flag meanings (see ARCHITECTURE.md "Per-serving thresholds"):
  phosphate_additive  - contains added phosphates (phosphoric acid, sodium/calcium
                        phosphates, pyrophosphate leavening); ~90-100 % absorbed
  high_gi             - fast-acting carbohydrate (type 1: spikes glucose)
  counts_as_fluid     - the serving's water counts toward a fluid limit
  avoid_ckd           - unsafe with reduced kidney function (always a high warning)
  hypo_treatment      - ~15 g fast carbs that are also low in potassium/phosphorus
  low_potassium_fruit - renal-diet "safe" fruit in the listed portion
  processed           - packaged / restaurant food, sodium and additives likely
  ingredient          - only ever added to other food (flour, salt, oil, butter, vinegar ...): meal
                        guidance never suggests it on its own (docs/dev/research/06-meal-guidance.md F9)
  alcohol             - an alcoholic drink: meal guidance never suggests it, because alcohol can cause
                        delayed lows with insulin (ADA Standards of Care 2026 §5, recommendations 5.18-5.19)

Meal-guidance roles (``role``): the guidance engine derives a role from the category and the numbers
(app/guidance/rules.py ``role_of``); ``role`` overrides it for the few foods the rule gets wrong
(coleslaw is a vegetable side, not an "extra").
"""

CATEGORIES = [
    "Fruits",
    "Vegetables",
    "Grains & Breads",
    "Dairy & Alternatives",
    "Meat, Poultry & Eggs",
    "Fish & Seafood",
    "Legumes, Nuts & Seeds",
    "Beverages",
    "Sweets & Snacks",
    "Condiments & Sauces",
    "Prepared & Fast Food",
    "Diabetes supplies",
]

FLAGS = [
    "phosphate_additive",
    "potassium_additive",  # v0.3 (note 03 R5); no builtin food needs it today
    "high_gi",
    "counts_as_fluid",
    "avoid_ckd",
    "hypo_treatment",
    "low_potassium_fruit",
    "processed",
    "ingredient",
    "alcohol",
]

# Must equal app/guidance/rules.py ROLES (tests/guidance/test_data.py checks it).
ROLES = ["protein", "mixed", "starch", "veg_fruit", "drink", "extra"]

# Short aliases keep the table below readable.
FRUIT = "Fruits"
VEG = "Vegetables"
GRAIN = "Grains & Breads"
DAIRY = "Dairy & Alternatives"
MEAT = "Meat, Poultry & Eggs"
FISH = "Fish & Seafood"
LEGUME = "Legumes, Nuts & Seeds"
BEV = "Beverages"
SWEET = "Sweets & Snacks"
COND = "Condiments & Sauces"
PREP = "Prepared & Fast Food"
T1D = "Diabetes supplies"

PA = "phosphate_additive"
GI = "high_gi"
FL = "counts_as_fluid"
AVOID = "avoid_ckd"
HYPO = "hypo_treatment"
LOWK = "low_potassium_fruit"
PROC = "processed"
ING = "ingredient"
ALC = "alcohol"


def f(fdc_id, name, category, serving_desc, serving_g, flags=(), notes=None, role=None):
    entry = {
        "fdc_id": fdc_id,
        "name": name,
        "category": category,
        "serving_desc": serving_desc,
        "serving_g": serving_g,
        "flags": list(flags),
        "kidney_notes": notes,
    }
    if role is not None:
        entry["role"] = role
    return entry


def manual(manual_id, name, category, serving_desc, serving_g, nutrients, flags=(), notes=None):
    """Entry with label-derived nutrients (no USDA record). Missing keys default to 0."""
    return {
        "manual_id": manual_id,
        "name": name,
        "category": category,
        "serving_desc": serving_desc,
        "serving_g": serving_g,
        "manual_nutrients": nutrients,
        "flags": list(flags),
        "kidney_notes": notes,
    }


CURATED_FOODS = [
    # ------------------------------------------------------------------ Fruits
    f(171688, "Apple, raw, with skin", FRUIT, "1 medium", 182, [LOWK]),
    f(171695, "Applesauce, unsweetened", FRUIT, "1/2 cup", 122, [LOWK]),
    # Berries and grapes are served at the 1/2 cup of the handbook's food lists (handbook/docs/eat/food-lists.md;
    # formerly docs/diet-guide.md section 3): a full cup of
    # strawberries, blackberries or grapes is over 200 mg potassium, which would contradict the
    # low_potassium_fruit badge ("a large serving of a low-potassium food becomes a high one").
    f(171711, "Blueberries, raw", FRUIT, "1/2 cup", 74, [LOWK]),
    f(167762, "Strawberries, raw", FRUIT, "1/2 cup, halves", 76, [LOWK]),
    f(167755, "Raspberries, raw", FRUIT, "1/2 cup", 61.5, [LOWK]),
    f(173946, "Blackberries, raw", FRUIT, "1/2 cup", 72, [LOWK]),
    f(171722, "Cranberries, raw", FRUIT, "1 cup, whole", 100, [LOWK]),
    f(174683, "Grapes, red or green, raw", FRUIT, "1/2 cup, about 15", 75.5, [LOWK],
      "Low potassium at 1/2 cup (about 15 grapes); a full bowl is 300+ mg."),
    f(169124, "Pineapple, raw", FRUIT, "1 cup, chunks", 165, [LOWK]),
    f(169126, "Pineapple, canned in juice", FRUIT, "1/2 cup", 125, [LOWK]),
    f(169930, "Peaches, canned in juice", FRUIT, "1/2 cup", 124, [LOWK]),
    f(169928, "Peach, raw", FRUIT, "1 medium", 150, [],
      "A fresh peach has about twice the potassium of canned peaches in juice; keep to one small one."),
    f(169118, "Pear, raw", FRUIT, "1 small", 148, [LOWK],
      "One small pear stays under 200 mg potassium; a medium one is about 206 mg."),
    f(169936, "Pears, canned in juice", FRUIT, "1/2 cup", 124, [LOWK]),
    f(169949, "Plum, raw", FRUIT, "1 fruit", 66, [LOWK]),
    f(167765, "Watermelon, raw", FRUIT, "1 cup, diced", 152, [LOWK],
      "Low potassium per cup, but it is mostly water: count it toward fluid if you have a fluid limit and stop at 1 cup."),
    f(171719, "Cherries, sweet, raw", FRUIT, "10 cherries", 82, [LOWK]),
    f(169105, "Tangerine (mandarin), raw", FRUIT, "1 medium", 88, [],
      "Moderate potassium; one small tangerine is the usual citrus swap for an orange."),
    f(168195, "Clementine, raw", FRUIT, "1 fruit", 74, []),
    f(173033, "Grapefruit, raw", FRUIT, "1/2 medium", 128, [],
      "Moderate potassium; grapefruit also interacts with several medicines (statins, some transplant and blood-pressure drugs), so ask your pharmacist."),
    f(169097, "Orange, raw", FRUIT, "1 fruit", 131, [],
      "High potassium (~240 mg); a tangerine, or a cup of berries or grapes, is the renal-diet swap."),
    f(173944, "Banana, raw", FRUIT, "1 medium", 118, [],
      "High potassium (~420 mg); a renal dietitian usually suggests apples, berries or grapes instead."),
    f(169092, "Cantaloupe, raw", FRUIT, "1 cup, cubes", 160, [],
      "High potassium (~430 mg per cup); watermelon or pineapple is the lower-potassium melon choice."),
    f(169911, "Honeydew melon, raw", FRUIT, "1 cup, diced", 170, [],
      "High potassium (~390 mg per cup); swap for watermelon or pineapple."),
    f(168153, "Kiwifruit, raw", FRUIT, "1 fruit", 69, [],
      "Moderate potassium (~215 mg); one small kiwi is fine occasionally, berries are the safer everyday pick."),
    f(169910, "Mango, raw", FRUIT, "1 cup, pieces", 165, [],
      "Moderate-high potassium and 23 g sugar per cup; stick to 1/2 cup or swap for pineapple."),
    f(169926, "Papaya, raw", FRUIT, "1 cup, pieces", 145, [],
      "Moderate-high potassium (~260 mg per cup); pineapple or canned peaches are lower."),
    f(169914, "Nectarine, raw", FRUIT, "1 medium", 142, [],
      "Moderate-high potassium (~285 mg); a plum or canned peaches in juice are lower."),
    f(171697, "Apricots, raw", FRUIT, "2 apricots", 70, [],
      "Moderate potassium fresh, and very high once dried; keep to two fresh ones."),
    f(173021, "Figs, raw", FRUIT, "2 medium", 100, [],
      "Moderate-high potassium (~230 mg); dried figs are far worse, so keep to fresh and small."),
    f(169134, "Pomegranate arils", FRUIT, "1/2 cup", 87, [],
      "Moderate potassium (~205 mg per 1/2 cup); berries are the lower-potassium swap."),
    f(171705, "Avocado, raw", FRUIT, "1/4 avocado", 50, [],
      "Very high potassium (~240 mg in just a quarter); use a thin smear or swap for cream cheese or hummus."),
    f(173941, "Apricots, dried", FRUIT, "10 halves", 35, [],
      "Dried fruit concentrates potassium (~400 mg in 10 halves); have fresh fruit or a few grapes instead."),
    f(168165, "Raisins", FRUIT, "1 small box, 1.5 oz", 43, [GI],
      "Dried fruit concentrates potassium (~320 mg per small box) and sugar; fresh grapes are the swap."),
    f(168162, "Prunes (dried plums)", FRUIT, "5 prunes", 48, [],
      "Very high potassium (~350 mg) and phosphorus; if you need them for constipation, ask your dietitian about an alternative."),
    f(168191, "Dates, medjool", FRUIT, "2 dates", 48, [GI],
      "Very high potassium (~330 mg for two) and sugar; a few grapes or a small hard candy are the swaps."),
    f(169130, "Plantain, raw", FRUIT, "1/2 cup, sliced", 74, [],
      "Very high potassium (~370 mg per 1/2 cup); white rice or pasta are the lower-potassium starch swaps."),
    f(171715, "Star fruit (carambola)", FRUIT, "1 medium", 91, [AVOID],
      "AVOID with kidney disease: star fruit contains a neurotoxin (caramboxin) that failing kidneys cannot clear; it can cause hiccups, confusion, seizures and death."),
    f(174667, "Fruit cocktail, canned in water", FRUIT, "1/2 cup", 119, []),

    # -------------------------------------------------------------- Vegetables
    f(170397, "Cauliflower, boiled", VEG, "1/2 cup", 62, []),
    f(169986, "Cauliflower, raw", VEG, "1 cup, chopped", 107, []),
    f(169976, "Cabbage, boiled", VEG, "1/2 cup, shredded", 75, []),
    f(169975, "Cabbage, raw", VEG, "1 cup, shredded", 70, []),
    f(169141, "Green beans, boiled", VEG, "1/2 cup", 63, []),
    f(169967, "Broccoli, boiled", VEG, "1/2 cup, chopped", 78, [],
      "Moderate potassium (~230 mg per 1/2 cup); cauliflower, cabbage or green beans are lower."),
    f(170379, "Broccoli, raw", VEG, "1 cup, chopped", 91, [],
      "Moderate-high potassium (~290 mg per cup raw); boiling and draining removes some."),
    f(170393, "Carrot, raw", VEG, "1 medium", 61, []),
    f(170394, "Carrots, boiled", VEG, "1/2 cup, slices", 78, []),
    f(169988, "Celery, raw", VEG, "1 stalk, medium", 40, []),
    f(168409, "Cucumber, with peel, raw", VEG, "1/2 cup, slices", 52, []),
    f(169248, "Lettuce, iceberg", VEG, "1 cup, shredded", 72, []),
    f(169247, "Lettuce, romaine", VEG, "1 cup, shredded", 47, []),
    f(170000, "Onion, raw", VEG, "1/2 cup, chopped", 80, []),
    f(170108, "Bell pepper, red, raw", VEG, "1/2 cup, chopped", 75, []),
    f(170427, "Bell pepper, green, raw", VEG, "1/2 cup, chopped", 75, []),
    f(169276, "Radishes, raw", VEG, "1/2 cup, slices", 58, []),
    f(168576, "Jalapeno pepper, raw", VEG, "1 pepper", 14, []),
    f(169230, "Garlic, raw", VEG, "1 clove", 3, []),
    f(169292, "Zucchini, boiled", VEG, "1/2 cup, sliced", 90, [],
      "Moderate potassium (~235 mg per 1/2 cup); summer squash is similar, so keep portions small."),
    f(168390, "Asparagus, boiled", VEG, "4 spears", 60, []),
    f(169229, "Eggplant, boiled", VEG, "1 cup, cubes", 99, []),
    f(169999, "Corn, sweet, boiled", VEG, "1 ear, medium", 103, [],
      "Moderate-high potassium (~220 mg) and about 20 g carbs per ear; count it as a starch."),
    f(169251, "Mushrooms, white, raw", VEG, "1 cup, pieces", 70, [],
      "Moderate potassium (~220 mg per cup) and phosphorus; keep to 1/2 cup."),
    f(170420, "Peas, green, boiled", VEG, "1/2 cup", 80, [],
      "Moderate potassium (~220 mg) and phosphorus per 1/2 cup; green beans are the lower swap."),
    f(170440, "Potato, boiled, peeled", VEG, "1/2 cup", 78, [],
      "High potassium even peeled (~255 mg per 1/2 cup); leach it: peel, dice small, soak in a large pot of water 2-4 h, then boil in fresh water, and keep to 1/2 cup."),
    f(170093, "Potato, baked, with skin", VEG, "1 medium", 173, [],
      "Very high potassium (~925 mg); the skin is worst. Swap for white rice, pasta, or a small portion of leached boiled potato."),
    f(170493, "Mashed potatoes, with milk", VEG, "1/2 cup", 105, [],
      "High potassium (~300 mg per 1/2 cup) plus milk phosphorus; make it with leached potatoes and rice milk or swap for rice."),
    f(169264, "French fries, frozen, oven-heated", VEG, "10 fries", 76, [PROC],
      "High potassium (~360 mg) and salted; a small portion of white rice or pasta is the swap."),
    f(168483, "Sweet potato, baked", VEG, "1/2 cup", 100, [],
      "Very high potassium (~475 mg per 1/2 cup); white rice, pasta or leached white potato are lower."),
    f(170457, "Tomato, raw", VEG, "1 medium", 123, [],
      "High potassium (~290 mg); a few cherry tomatoes or roasted red pepper give colour with less potassium."),
    f(170054, "Tomato sauce, canned", VEG, "1/2 cup", 123, [PROC],
      "Very high potassium (~400 mg per 1/2 cup) and sodium; use a little tomato paste thinned with water, or a garlic-and-oil sauce."),
    f(170459, "Tomato paste, no salt added", VEG, "1 tbsp", 16, [],
      "Concentrated potassium (~160 mg per tbsp); a tablespoon for flavour is fine, a cup is not."),
    f(168462, "Spinach, raw", VEG, "1 cup", 30, [],
      "Fine raw in a salad (~165 mg potassium per cup); cooked spinach packs 5x more into the same space."),
    f(168463, "Spinach, boiled", VEG, "1/2 cup", 90, [],
      "Very high potassium (~420 mg per 1/2 cup); swap for cabbage, green beans or a raw spinach salad."),
    f(169238, "Kale, boiled", VEG, "1 cup", 118, [],
      "Moderate potassium (~170 mg per cup); cabbage is the lower leafy swap."),
    f(169971, "Brussels sprouts, boiled", VEG, "1/2 cup", 78, [],
      "Moderate-high potassium (~245 mg per 1/2 cup); cauliflower or cabbage are lower."),
    f(169146, "Beets, boiled", VEG, "1/2 cup, slices", 85, [],
      "Moderate-high potassium (~260 mg per 1/2 cup); carrots or radishes are lower."),
    f(169296, "Butternut squash, baked", VEG, "1/2 cup, cubes", 103, [],
      "High potassium (~290 mg per 1/2 cup); summer squash or carrots are lower."),
    f(168450, "Pumpkin, canned", VEG, "1/2 cup", 123, [],
      "Moderate-high potassium (~250 mg per 1/2 cup); keep to a small portion."),
    f(168386, "Artichoke, boiled", VEG, "1 medium", 120, [],
      "High potassium (~345 mg per artichoke); asparagus or green beans are lower."),
    f(169261, "Okra, boiled", VEG, "1/2 cup, slices", 80, []),
    f(170058, "Turnips, boiled", VEG, "1/2 cup, cubes", 78, []),
    f(170472, "Mixed vegetables, frozen, boiled", VEG, "1/2 cup", 91, []),
    f(168558, "Pickle, dill", VEG, "1 spear", 35, [PROC],
      "Very high sodium (~280 mg per small spear, ~1100 mg for a large pickle); cucumber slices with vinegar and dill are the swap."),
    f(169279, "Sauerkraut, canned", VEG, "1/2 cup", 71, [PROC],
      "Very high sodium (~470 mg per 1/2 cup); rinse well or swap for boiled cabbage with vinegar."),
    f(169094, "Olives, ripe, canned", VEG, "10 large", 44, [PROC],
      "Brined, so high sodium (~320 mg for 10); a few are fine, a handful is not."),

    # -------------------------------------------------------- Grains & Breads
    f(174924, "Bread, white", GRAIN, "1 slice", 29, [GI]),
    f(172688, "Bread, whole-wheat", GRAIN, "1 slice", 32, [],
      "Whole grains carry more phosphorus and potassium than white; white or sourdough bread is the usual renal swap (talk to your dietitian about fibre)."),
    f(168013, "Bread, multigrain", GRAIN, "1 slice", 26, [],
      "Seeds and whole grains add phosphorus and potassium; white or light rye bread is lower."),
    f(172684, "Bread, rye", GRAIN, "1 slice", 32, []),
    f(172680, "Bread, raisin", GRAIN, "1 slice", 26, []),
    f(174915, "Pita bread, white", GRAIN, "1 large, 6-1/2 in", 60, []),
    f(174899, "Bagel, plain", GRAIN, "1 bagel", 99, [GI],
      "One bagel is about 50 g carbs (3+ carb choices) and ~420 mg sodium; half a bagel is a more realistic portion."),
    f(172796, "Hamburger or hot dog bun", GRAIN, "1 roll", 44, []),
    f(173242, "Tortilla, flour", GRAIN, "1 tortilla, 8 in", 49, [PA, PROC],
      "Most store-bought flour tortillas use phosphate leavening (sodium acid pyrophosphate); corn tortillas are the lower-phosphorus choice."),
    f(173241, "Tortilla, corn", GRAIN, "1 tortilla, 6 in", 26, []),
    f(175063, "English muffin, plain", GRAIN, "1 muffin", 57, []),
    f(174987, "Croissant, butter", GRAIN, "1 medium", 57, []),
    f(171845, "Naan bread, plain", GRAIN, "1 piece", 90, []),
    f(174910, "Cornbread, from recipe", GRAIN, "1 piece", 65, [],
      "Baking powder, milk and cornmeal make this moderately high in phosphorus; keep to one small piece."),
    f(172765, "Muffin, blueberry, commercial", GRAIN, "1 medium", 113, [PA, PROC],
      "Commercial muffins use phosphate leavening and are ~55 g carbs; a slice of white toast with jam is the swap."),
    f(175009, "Pancakes, from recipe", GRAIN, "2 pancakes, 4 in", 76, [],
      "Baking powder and milk add phosphorus (~120 mg for two); use a low-sodium, phosphate-free baking powder and rice milk."),
    f(175006, "Pancakes, from complete mix", GRAIN, "2 pancakes, 4 in", 76, [PA, PROC],
      "Pancake mixes rely on phosphate leavening (highly absorbed phosphorus) and are salty; homemade with rice milk is the swap."),
    f(175038, "Waffles, frozen", GRAIN, "2 waffles", 70, [PA, PROC],
      "Frozen waffles list sodium/calcium phosphates for leavening; homemade or a slice of white toast is lower in phosphorus."),
    f(172669, "Biscuit, refrigerated dough, baked", GRAIN, "1 biscuit", 51, [PA, PROC],
      "Canned biscuit dough is leavened with sodium acid pyrophosphate and is salty (~510 mg sodium); a white roll is the swap."),
    f(168878, "Rice, white, long-grain, cooked", GRAIN, "1 cup", 158, []),
    f(169704, "Rice, brown, cooked", GRAIN, "1 cup", 202, [],
      "Brown rice has about 3x the phosphorus and twice the potassium of white rice; white rice is the renal-diet grain."),
    f(169737, "Pasta, cooked", GRAIN, "1 cup", 124, []),
    f(168910, "Pasta, whole-wheat, cooked", GRAIN, "1 cup", 117, [],
      "Whole-wheat pasta roughly doubles the phosphorus of regular pasta; regular pasta is the swap."),
    f(168919, "Egg noodles, cooked", GRAIN, "1 cup", 160, []),
    f(169700, "Couscous, cooked", GRAIN, "1 cup", 157, []),
    f(168917, "Quinoa, cooked", GRAIN, "1 cup", 185, [],
      "High in both potassium (~320 mg) and phosphorus (~280 mg) per cup; white rice or couscous is the swap."),
    f(170285, "Barley, pearled, cooked", GRAIN, "1 cup", 157, []),
    f(173905, "Oatmeal, cooked (regular or quick oats)", GRAIN, "1 cup", 234, [],
      "Oats are moderately high in phosphorus (~180 mg per cup); cream of wheat, grits or cream of rice are the lower-phosphorus hot cereals."),
    f(171662, "Oatmeal, instant, fortified, prepared", GRAIN, "1 packet, prepared", 177, [PROC],
      "Flavoured instant oats are fortified and salted; check the label for added phosphates, or choose cream of wheat."),
    f(171657, "Cream of wheat, cooked", GRAIN, "1 cup", 251, []),
    f(171655, "Grits, cooked", GRAIN, "1 cup", 257, []),
    f(174648, "Corn flakes cereal", GRAIN, "1 cup", 28, [GI]),
    f(173887, "Crisp rice cereal", GRAIN, "1-1/4 cup", 33, [GI]),
    f(173884, "Toasted oat cereal (Cheerios-type)", GRAIN, "1 cup", 28, [],
      "Oat cereals carry more phosphorus than corn or rice cereals; fine occasionally."),
    f(173911, "Shredded wheat cereal", GRAIN, "1 cup", 49, [],
      "Whole-wheat cereal is high in phosphorus (~190 mg per cup); corn flakes or crisp rice are the low-phosphorus swaps."),
    f(171650, "Raisin bran cereal", GRAIN, "1 cup", 59, [],
      "Bran plus raisins: very high potassium (~360 mg) and phosphorus (~230 mg) per cup; swap for corn flakes or crisp rice."),
    f(167715, "Bran cereal (shredded wheat and bran)", GRAIN, "1-1/4 cup", 59, [],
      "Bran cereals are among the highest-phosphorus breakfast foods (~250 mg per serving); corn flakes, crisp rice or cream of wheat are the swaps."),
    f(172746, "Saltine crackers", GRAIN, "5 crackers", 15, []),
    f(174982, "Snack crackers (buttery round)", GRAIN, "5 crackers", 16, [PA, PROC],
      "Buttery snack crackers usually list calcium phosphate leavening and salt; unsalted saltines or rice cakes are lower."),
    f(172749, "Crackers, whole-wheat", GRAIN, "6 crackers", 28, [],
      "Whole-grain crackers are higher in phosphorus and potassium; saltines or rice cakes are the swap."),
    f(170250, "Rice cakes, plain, unsalted", GRAIN, "2 cakes", 18, []),
    f(168894, "Flour, all-purpose", GRAIN, "1/4 cup", 31, [ING]),

    # ---------------------------------------------------- Dairy & Alternatives
    f(171265, "Milk, whole", DAIRY, "1 cup", 244, [FL],
      "A cup of milk is ~320 mg potassium and ~205 mg phosphorus; many renal plans allow 1/2 cup a day or swap to rice milk."),
    f(171267, "Milk, 2% reduced fat", DAIRY, "1 cup", 244, [FL],
      "A cup of milk is ~340 mg potassium and ~225 mg phosphorus; keep to 1/2 cup or swap to unenriched rice milk."),
    f(171269, "Milk, skim (nonfat)", DAIRY, "1 cup", 245, [FL],
      "Skim milk has slightly more potassium and phosphorus per cup than whole; the fat is not the renal issue, the minerals are."),
    f(170880, "Chocolate milk, 2%", DAIRY, "1 cup", 250, [FL, GI],
      "Milk minerals plus cocoa: ~420 mg potassium and ~250 mg phosphorus, and 24 g sugar; rice milk with a little vanilla is the swap."),
    f(170874, "Buttermilk, low fat", DAIRY, "1 cup", 245, [FL],
      "Same potassium and phosphorus load as milk, with extra sodium."),
    f(170886, "Yogurt, plain, low fat", DAIRY, "1 container, 6 oz", 170, [],
      "Yogurt is concentrated milk: ~390 mg potassium and ~240 mg phosphorus per 6 oz; a 4 oz portion or a non-dairy yogurt is the swap."),
    f(170894, "Greek yogurt, plain, nonfat", DAIRY, "1 container, 6 oz", 170, [],
      "Straining removes some potassium and phosphorus, but 6 oz is still ~17 g protein and ~230 mg phosphorus; count it as a protein portion."),
    f(171285, "Yogurt, fruit, low fat", DAIRY, "1 container, 6 oz", 170, [GI],
      "Milk minerals plus ~30 g sugar; a small plain yogurt with fresh berries is the swap."),
    f(173414, "Cheese, cheddar", DAIRY, "1 oz", 28, [],
      "Hard cheeses are high in phosphorus (~130 mg per oz) and salt; 1 oz a day is a common limit, cream cheese is lower."),
    f(170847, "Cheese, mozzarella, part skim", DAIRY, "1 oz", 28, [],
      "Moderate phosphorus (~130 mg per oz); fine in a 1 oz portion."),
    f(171251, "Cheese, Swiss", DAIRY, "1 slice, 1 oz", 28, [],
      "Lower in sodium than most cheeses but higher in phosphorus (~160 mg per oz); keep to one slice."),
    f(172182, "Cottage cheese, 2%", DAIRY, "1/2 cup", 113, [],
      "High sodium (~350 mg per 1/2 cup) and phosphorus; ricotta or a no-salt-added cottage cheese is the swap."),
    f(171248, "Ricotta cheese, part skim", DAIRY, "1/2 cup", 124, [],
      "Moderate phosphorus (~225 mg per 1/2 cup); keep the portion small."),
    f(173418, "Cream cheese", DAIRY, "1 tbsp", 14.5, []),
    f(170853, "Cheese, American, processed", DAIRY, "1 slice, 1 oz", 28, [PA, PROC],
      "Processed cheese is made with sodium phosphate emulsifiers (almost fully absorbed) and is very salty; natural Swiss or cream cheese is the swap."),
    f(171247, "Parmesan cheese, grated", DAIRY, "1 tbsp", 5, [],
      "Very concentrated in sodium and phosphorus per gram; a tablespoon sprinkle is fine, a pile is not."),
    f(173420, "Feta cheese", DAIRY, "1 oz", 28, [],
      "Brined, so high sodium (~320 mg per oz); a small crumble goes a long way."),
    f(171255, "Half and half", DAIRY, "1 tbsp", 15, []),
    f(170859, "Heavy whipping cream", DAIRY, "1 tbsp", 15, []),
    f(171257, "Sour cream", DAIRY, "1 tbsp", 12, []),
    f(173410, "Butter, salted", DAIRY, "1 tbsp", 14.2, [ING]),
    f(173430, "Butter, unsalted", DAIRY, "1 tbsp", 14.2, [ING]),
    f(171261, "Non-dairy creamer, liquid", DAIRY, "1 tbsp", 15, [PA, PROC],
      "Most non-dairy creamers contain dipotassium phosphate; a splash of real half and half is the lower-phosphorus choice."),
    f(171942, "Rice milk, unsweetened", DAIRY, "1 cup", 240, [FL],
      "The classic renal milk swap: low potassium and phosphorus (check the label for added phosphate 'enrichment')."),
    f(174832, "Almond milk, unsweetened", DAIRY, "1 cup", 262, [FL],
      "Low potassium and phosphorus naturally, but many brands add calcium or potassium phosphate; read the ingredient list."),
    f(175215, "Soy milk, unsweetened", DAIRY, "1 cup", 243, [FL],
      "Higher in potassium and phosphorus than rice or almond milk, and often fortified with phosphate; rice milk is the lower swap."),

    # --------------------------------------------------- Meat, Poultry & Eggs
    f(171477, "Chicken breast, roasted, skinless", MEAT, "1/2 breast", 86, []),
    f(172388, "Chicken thigh, roasted, skinless", MEAT, "3 oz", 85, []),
    f(173612, "Chicken drumstick, roasted, with skin", MEAT, "3 oz", 85, []),
    f(173630, "Chicken wings, roasted", MEAT, "3 oz", 85, []),
    f(171450, "Chicken, roasted, meat and skin", MEAT, "3 oz", 85, []),
    f(171475, "Chicken breast, batter-fried", MEAT, "3 oz", 85, [PROC],
      "Batter adds sodium and phosphate leavening; roasted or grilled chicken is the swap."),
    f(171117, "Ground chicken, cooked", MEAT, "3 oz", 85, []),
    # 171496 (whole-bird breast, meat only) is the record the handbook's food lists quote
    # (handbook/docs/eat/food-lists.md; formerly docs/diet-guide.md section 3)
    # (K 212, P 196, Na 84, 26 g protein per 3 oz), so the handbook's Eat row and the app agree.
    f(171496, "Turkey breast, roasted", MEAT, "3 oz", 85, []),
    f(174492, "Ground turkey, 93% lean, patty", MEAT, "3 oz", 85, []),
    f(174032, "Ground beef, 85% lean, patty", MEAT, "3 oz", 85, []),
    f(174031, "Ground beef, 90% lean, patty", MEAT, "3 oz", 85, []),
    f(173118, "Beef, top sirloin steak, broiled", MEAT, "3 oz", 85, []),
    f(171817, "Beef, chuck pot roast, braised", MEAT, "3 oz", 85, []),
    f(170634, "Beef, eye of round roast", MEAT, "3 oz", 85, []),
    f(168240, "Pork loin chop, broiled", MEAT, "3 oz", 85, []),
    f(168250, "Pork tenderloin, roasted", MEAT, "3 oz", 85, []),
    f(167914, "Bacon, cooked", MEAT, "2 slices", 16, [PA, PROC],
      "Cured with salt and usually sodium phosphate; two slices is the limit, or choose an uncured, no-phosphate brand."),
    f(167871, "Ham, extra lean, roasted", MEAT, "3 oz", 85, [PA, PROC],
      "Cured ham is ~1000 mg sodium per 3 oz and is typically injected with sodium phosphate; fresh roasted pork is the swap."),
    f(173863, "Deli ham, sliced", MEAT, "2 oz", 57, [PA, PROC],
      "Deli meats are salty and phosphate-injected; slice your own roasted chicken, turkey or pork instead."),
    f(172941, "Deli turkey breast, sliced", MEAT, "2 oz", 57, [PA, PROC],
      "Even 'lean' deli turkey is brined with salt and sodium phosphate; home-roasted turkey breast is the swap."),
    f(174578, "Pork sausage, cooked", MEAT, "2 links", 46, [PROC],
      "Sausage is high in sodium and often phosphate-cured; fresh ground pork or turkey seasoned at home is the swap."),
    f(174614, "Hot dog, beef", MEAT, "1 frankfurter", 48, [PA, PROC],
      "Hot dogs combine ~410 mg sodium with sodium phosphate; a grilled chicken thigh or a fresh pork patty is the swap."),
    f(172013, "Bologna, beef and pork", MEAT, "1 slice", 28, [PA, PROC],
      "Processed luncheon meat: salt, sodium phosphate and nitrite; roast your own meat for sandwiches."),
    f(174582, "Salami, dry", MEAT, "3 slices", 27, [PROC],
      "Very high sodium (~500 mg in three slices); a slice of fresh roast beef is the swap."),
    f(174575, "Pepperoni", MEAT, "1 oz, about 14 slices", 28, [PROC],
      "Very salty cured meat (~450 mg sodium per oz); use a few slices for flavour, not a layer."),
    f(170200, "Corned beef, cooked", MEAT, "3 oz", 85, [PROC],
      "Brine-cured: ~830 mg sodium per 3 oz; fresh brisket or pot roast is the swap."),
    f(167536, "Beef jerky", MEAT, "1 oz", 28, [PROC],
      "Very high sodium (~500 mg per oz) and concentrated phosphorus; unsalted popcorn or a hard-boiled egg white is the snack swap."),
    f(168626, "Beef liver, braised", MEAT, "3 oz", 85, [],
      "Organ meats are extremely high in phosphorus (~420 mg per 3 oz); choose lean muscle meat instead."),
    f(171287, "Egg, whole, raw", MEAT, "1 large", 50, []),
    f(173424, "Egg, hard-boiled", MEAT, "1 large", 50, [],
      "The yolk holds the phosphorus (~85 mg per egg); egg whites are the renal favourite and still give the protein."),
    f(172187, "Egg, scrambled", MEAT, "1 large", 61, []),
    f(172183, "Egg white, raw", MEAT, "1 large", 33, []),
    f(173462, "Egg substitute, liquid", MEAT, "1/4 cup", 60, []),

    # ---------------------------------------------------------- Fish & Seafood
    f(175168, "Salmon, Atlantic, farmed, cooked", FISH, "3 oz", 85, [],
      "Excellent protein but ~325 mg potassium and ~215 mg phosphorus per 3 oz; a 3 oz portion is the point to stop."),
    f(173692, "Salmon, sockeye, cooked", FISH, "3 oz", 85, [],
      "Wild salmon runs ~300+ mg potassium per 3 oz; keep to one portion."),
    f(173724, "Salmon, pink, canned, drained", FISH, "3 oz", 85, [PROC],
      "Canned fish is salted (~350 mg sodium); rinse, and choose boneless so the bones do not add phosphorus."),
    f(173709, "Tuna, light, canned in water, drained", FISH, "3 oz", 85, [PROC],
      "A good lower-phosphorus fish, but canned in brine (~210 mg sodium); look for 'no salt added'."),
    f(175158, "Tuna, white (albacore), canned in water", FISH, "3 oz", 85, [PROC],
      "Canned in brine (~300 mg sodium); choose 'no salt added' and drain well."),
    f(172006, "Tuna, yellowfin, fresh, cooked", FISH, "3 oz", 85, [],
      "Fresh tuna is one of the higher-potassium fish (~480 mg per 3 oz); cod, tilapia or haddock are lower."),
    f(171956, "Cod, Atlantic, cooked", FISH, "3 oz", 85, []),
    f(175177, "Tilapia, cooked", FISH, "1 fillet", 87, []),
    f(174198, "Haddock, cooked", FISH, "3 oz", 85, []),
    f(173726, "Pollock, Alaska, cooked", FISH, "3 oz", 85, []),
    f(174197, "Flounder or sole, cooked", FISH, "3 oz", 85, []),
    f(174201, "Halibut, cooked", FISH, "3 oz", 85, [],
      "High potassium (~450 mg per 3 oz); cod, haddock or tilapia are the lower white-fish choices."),
    f(173718, "Trout, rainbow, farmed, cooked", FISH, "3 oz", 85, []),
    f(175166, "Catfish, farmed, cooked", FISH, "3 oz", 85, []),
    f(175120, "Mackerel, Atlantic, cooked", FISH, "3 oz", 85, [],
      "Oily fish rich in omega-3 but ~340 mg potassium and ~235 mg phosphorus per 3 oz; keep to one portion."),
    f(175139, "Sardines, canned in oil, with bones", FISH, "1 can, 3.75 oz", 92, [PROC],
      "The edible bones make sardines one of the highest-phosphorus foods (~450 mg per can) and they are salty; canned tuna is the swap."),
    f(171985, "Smoked salmon (lox)", FISH, "2 oz", 57, [PROC],
      "Smoked and salted: ~1100 mg sodium per 2 oz; fresh baked salmon is the swap."),
    f(171971, "Shrimp, cooked", FISH, "3 oz", 85, [PA, PROC],
      "Most frozen shrimp are soaked in sodium tripolyphosphate brine (the USDA entry notes 'additives to retain moisture'); look for 'no additives' or 'dry' shrimp."),
    f(174205, "Crab, blue, cooked", FISH, "3 oz", 85, []),
    f(174209, "Lobster, cooked", FISH, "3 oz", 85, [],
      "Naturally high in sodium (~410 mg per 3 oz); skip the salted butter."),
    f(171975, "Clams, cooked", FISH, "3 oz", 85, [],
      "Very high sodium (~1000 mg) and phosphorus (~290 mg) per 3 oz; keep to a small portion."),
    f(171980, "Oysters, eastern, cooked", FISH, "3 oz", 85, []),
    f(174195, "Fish sticks, frozen, prepared", FISH, "3 sticks", 84, [PA, PROC],
      "Breaded fish sticks are salty and usually treated with sodium tripolyphosphate; bake a plain white fish fillet instead."),
    f(173702, "Imitation crab (surimi)", FISH, "3 oz", 85, [PA, PROC],
      "Surimi is processed with salt, sugar and phosphates; real crab or cooked white fish is the swap."),

    # -------------------------------------------------- Legumes, Nuts & Seeds
    f(173735, "Black beans, cooked", LEGUME, "1/2 cup", 86, [],
      "Beans give ~300 mg potassium and ~120 mg phosphorus per 1/2 cup; a 1/2 cup counts as both a protein and a starch, and canned beans rinsed well lose some potassium."),
    f(173740, "Kidney beans, cooked", LEGUME, "1/2 cup", 89, [],
      "High potassium (~360 mg per 1/2 cup) and phosphorus; rinse canned beans and keep to 1/2 cup."),
    f(175200, "Pinto beans, cooked", LEGUME, "1/2 cup", 86, [],
      "High potassium (~375 mg per 1/2 cup) and phosphorus; rinse canned beans and keep to 1/2 cup."),
    f(173746, "Navy beans, cooked", LEGUME, "1/2 cup", 91, [],
      "Very high potassium (~355 mg per 1/2 cup) and phosphorus; keep portions small."),
    f(173757, "Chickpeas (garbanzo), cooked", LEGUME, "1/2 cup", 82, [],
      "Moderate-high potassium (~240 mg) and phosphorus (~140 mg) per 1/2 cup; hummus in a 2 tbsp portion is the gentler way to eat them."),
    f(172421, "Lentils, cooked", LEGUME, "1/2 cup", 99, [],
      "High potassium (~365 mg per 1/2 cup) and phosphorus; keep to 1/2 cup and count it as your protein."),
    f(172429, "Split peas, cooked", LEGUME, "1/2 cup", 98, [],
      "High potassium (~355 mg per 1/2 cup) and phosphorus; keep to 1/2 cup."),
    f(169135, "Lima beans, boiled", LEGUME, "1/2 cup", 85, [],
      "Very high potassium (~485 mg per 1/2 cup); green beans are the swap."),
    f(175182, "Baked beans, canned", LEGUME, "1/2 cup", 127, [PROC],
      "Canned baked beans add ~430 mg sodium and sugar to the bean potassium; plain beans you season yourself are the swap."),
    f(172438, "Refried beans, canned", LEGUME, "1/2 cup", 119, [PROC],
      "Canned refried beans are salty (~450 mg per 1/2 cup) on top of the bean potassium; keep to 1/4 cup."),
    f(174289, "Hummus", LEGUME, "2 tbsp", 30, []),
    # 172448 (nigari firm tofu) at 1/4 block is the guide's EAT row (K 120, P 98, 7.3 g protein).
    f(172448, "Tofu, firm", LEGUME, "1/4 block, about 3 oz", 81, [],
      "A kidney-friendly protein: 1/4 block is ~7 g protein with ~100 mg phosphorus (plant phosphorus is poorly absorbed); calcium-set brands add calcium."),
    f(168411, "Edamame, prepared", LEGUME, "1/2 cup", 78, [],
      "High potassium (~340 mg per 1/2 cup) and phosphorus; green beans are the snack swap."),
    f(174300, "Soy nuts (roasted soybeans)", LEGUME, "1/4 cup", 43, [],
      "Extremely concentrated potassium (~600 mg) and phosphorus (~150 mg) per 1/4 cup; unsalted popcorn is the crunchy swap."),
    f(174266, "Peanut butter", LEGUME, "2 tbsp", 32, [],
      "Moderate potassium (~180 mg) and phosphorus (~110 mg) per 2 tbsp; 1 tbsp is a sensible portion, cream cheese or jam are swaps."),
    f(174262, "Peanuts, dry roasted, salted", LEGUME, "1 oz", 28, [],
      "Moderate potassium (~180 mg) and phosphorus (~100 mg) per oz plus salt; a small handful of unsalted is the limit."),
    f(170567, "Almonds", LEGUME, "1 oz, 23 nuts", 28, [],
      "Nuts are concentrated phosphorus (~135 mg per oz) and potassium (~210 mg); macadamias or pecans are the lower-mineral nuts."),
    f(170187, "Walnuts", LEGUME, "1 oz, 14 halves", 28, [],
      "Moderate potassium (~120 mg) and phosphorus (~100 mg) per oz; keep to a small handful."),
    f(169421, "Cashews, dry roasted, salted", LEGUME, "1 oz", 28, [],
      "High phosphorus (~140 mg) and potassium (~160 mg) per oz plus salt; macadamias are the lower swap."),
    f(169426, "Pistachios, dry roasted, salted", LEGUME, "1 oz, 49 kernels", 28, [],
      "High potassium (~290 mg per oz) and phosphorus; pecans or macadamias are lower."),
    f(170182, "Pecans", LEGUME, "1 oz, 19 halves", 28, [],
      "One of the lower-potassium nuts (~115 mg per oz); still a phosphorus source, so keep to 1 oz."),
    f(170178, "Macadamia nuts", LEGUME, "1 oz", 28, [],
      "The lowest-potassium, lowest-phosphorus common nut; the usual renal-diet nut choice in a 1 oz portion."),
    f(168599, "Mixed nuts, dry roasted, salted", LEGUME, "1 oz", 28, [],
      "Salted mixed nuts bring ~170 mg potassium, ~130 mg phosphorus and salt per oz; unsalted macadamias are the swap."),
    f(169418, "Sunflower seeds, dry roasted, salted", LEGUME, "1 oz", 28, [],
      "Among the highest-phosphorus snacks (~325 mg per oz) and salted; unsalted popcorn is the swap."),
    f(169415, "Pumpkin seeds, roasted, salted", LEGUME, "1 oz", 28, [],
      "Very high phosphorus (~350 mg) and potassium (~230 mg) per oz; unsalted popcorn or a few macadamias instead."),
    f(170554, "Chia seeds", LEGUME, "1 tbsp", 12, [],
      "Concentrated phosphorus (~100 mg per tbsp); a teaspoon stirred in is plenty."),
    f(169414, "Flaxseed, ground", LEGUME, "1 tbsp", 7, []),

    # --------------------------------------------------------------- Beverages
    f(173647, "Water, tap", BEV, "1 cup, 8 fl oz", 237, [FL]),
    f(171890, "Coffee, brewed", BEV, "1 cup, 8 fl oz", 237, [FL],
      "Black coffee is ~115 mg potassium per cup; a cup or two is fine, and it counts toward any fluid limit."),
    f(171891, "Espresso", BEV, "1 shot, 1 fl oz", 30, [FL]),
    f(173227, "Tea, black, brewed", BEV, "1 cup, 8 fl oz", 237, [FL]),
    f(171917, "Tea, green, brewed", BEV, "1 cup", 245, [FL]),
    f(174129, "Iced tea, lemon, diet, bottled", BEV, "1 cup", 266, [FL, PROC]),
    f(174852, "Cola, regular", BEV, "1 can, 12 fl oz", 370, [PA, GI, FL, PROC],
      "Dark colas get their tang from phosphoric acid (fully absorbed phosphorus) and carry ~39 g sugar; a clear soda, or sparkling water with lemon, is the swap."),
    f(174850, "Cola, diet", BEV, "1 can, 12 fl oz", 355, [PA, FL, PROC],
      "Sugar-free, but still phosphoric acid (~35 mg phosphorus per can, essentially all of it absorbed); diet lemon-lime or sparkling water is the swap."),
    f(173209, "Pepper-type soda, regular", BEV, "1 can, 12 fl oz", 368, [PA, GI, FL, PROC],
      "Contains phosphoric acid and ~40 g sugar; clear soda or sparkling water is the swap."),
    # hypo_treatment foods are served at the rescue portion (~15 g fast carbs) of the handbook's
    # handbook/docs/t1d/treating-a-low.md (formerly docs/diet-guide.md section 4), because the flag switches the carbohydrate warning off: a whole 12 oz can would
    # otherwise hide 38 g of sugar from a type 1 diabetic.
    f(173205, "Lemon-lime soda, regular", BEV, "4 fl oz, 1/3 can", 123, [HYPO, GI, FL, PROC],
      "No phosphoric acid, so a clear soda is the renal choice for treating a low: 4 fl oz is about 13 g carbs. A whole 12 oz can is 3 servings and 38 g of sugar."),
    f(173204, "Lemon-lime soda, diet", BEV, "1 can, 12 fl oz", 355, [FL, PROC]),
    f(174846, "Ginger ale", BEV, "4 fl oz, 1/3 can", 122, [HYPO, GI, FL, PROC],
      "Clear and phosphate-free: 4 fl oz (about 11 g carbs) treats a low. A whole 12 oz can is 3 servings and 32 g of sugar."),
    f(171871, "Root beer", BEV, "1 can, 12 fl oz", 370, [GI, FL, PROC],
      "Usually no phosphoric acid, but ~40 g sugar per can; diet or sparkling water otherwise."),
    f(174842, "Club soda", BEV, "1 can, 12 fl oz", 355, [FL],
      "Fine, but check the label: club soda has added sodium (~75 mg per can), plain seltzer has none."),
    f(167771, "Apple juice", BEV, "1/2 cup, 4 fl oz", 124, [HYPO, GI, FL],
      "4 fl oz is ~14 g fast carbs and only ~125 mg potassium, which is why apple juice is the usual hypo drink for CKD; a full glass doubles everything."),
    f(173041, "Grape juice", BEV, "1/2 cup, 4 fl oz", 127, [HYPO, GI, FL],
      "4 fl oz is ~19 g fast carbs with low potassium, so it works for treating a low; not an everyday drink."),
    f(171903, "Cranberry juice cocktail", BEV, "1/2 cup, 4 fl oz", 126.5, [HYPO, GI, FL],
      "The lowest-potassium juice (~18 mg per 1/2 cup) and NIDDK's named alternative to orange juice for treating a low (4 fl oz is ~17 g fast carbs); the light version is the everyday choice."),
    f(169098, "Orange juice", BEV, "1 cup", 248, [GI, FL],
      "Very high potassium (~495 mg per cup) and 21 g sugar; apple, grape or cranberry juice are the low-potassium swaps."),
    f(168187, "Pineapple juice", BEV, "1/2 cup, 4 fl oz", 125, [GI, FL],
      "Moderate potassium (~160 mg per 4 fl oz); apple or cranberry juice are lower."),
    f(167753, "Prune juice", BEV, "1 cup", 256, [GI, FL],
      "Extremely high potassium (~700 mg per cup); if you need help with constipation ask your care team about a laxative instead."),
    f(170458, "Tomato juice", BEV, "1 cup", 243, [FL, PROC],
      "Very high potassium (~560 mg) and sodium (~650 mg) per cup; cranberry or apple juice are the swaps."),
    f(170063, "Vegetable juice cocktail (V8-type)", BEV, "1 cup", 253, [FL, PROC],
      "Very high potassium (~470 mg) and sodium (~480 mg) per cup; eat low-potassium vegetables instead of drinking them."),
    f(174859, "Lemonade, from powder", BEV, "1 cup", 264, [GI, FL, PROC],
      "Low potassium; sugar varies widely by brand (this USDA entry is ~9 g per cup, many bottled lemonades are 25+ g), so check the label or choose sugar-free."),
    f(174151, "Fruit punch drink", BEV, "1 cup", 248, [GI, FL, PROC],
      "Low in minerals but ~30 g sugar per cup; a sugar-free drink is the swap."),
    f(175108, "Sports drink (lemon-lime)", BEV, "8 fl oz", 243, [HYPO, GI, FL, PROC],
      "Low potassium, so 8 fl oz (~19 g carbs) can treat a low; otherwise it is sugar water with ~110 mg sodium per cup."),
    f(173210, "Energy drink", BEV, "1 can, 8.4 fl oz", 258, [GI, FL, PROC],
      "~27 g sugar plus caffeine and taurine; not recommended with kidney disease, and sugar-free versions still add caffeine."),
    f(174831, "Coconut water", BEV, "1 cup", 245, [FL],
      "Marketed as healthy but ~400 mg potassium per cup; water or a low-potassium juice is the swap."),
    f(173169, "Nutritional shake (Boost Plus-type)", BEV, "1 bottle, 8 fl oz", 237, [FL, PROC],
      "Standard nutrition shakes are high in potassium and phosphorus; renal formulas (e.g. Nepro, Novasource Renal) are made for CKD, ask your dietitian."),
    f(174123, "Hot cocoa, from mix with water", BEV, "1 serving, 6 fl oz", 206, [GI, FL, PROC],
      "Cocoa brings potassium and phosphorus and the mix adds sugar; keep it occasional."),
    f(170883, "Milkshake, chocolate, thick", BEV, "1 container, 10.6 oz", 300, [GI, FL, PROC],
      "Milk plus chocolate: ~670 mg potassium, ~380 mg phosphorus and ~60 g sugar; a small sherbet is the treat swap."),
    f(168746, "Beer, regular", BEV, "1 can, 12 fl oz", 356, [FL, ALC],
      "Moderate potassium and phosphorus (~95 and ~50 mg per can) and it counts as fluid; alcohol also raises hypo risk with insulin."),
    f(168749, "Beer, light", BEV, "1 can, 12 fl oz", 354, [FL, ALC],
      "Lower carbs than regular beer but the same fluid and hypo caution with insulin."),
    f(173190, "Wine, red", BEV, "1 glass, 5 fl oz", 147, [FL, ALC],
      "~190 mg potassium per glass; one glass is usually fine, and it counts toward fluid."),
    f(174837, "Wine, white", BEV, "1 glass, 5 fl oz", 147, [FL, ALC],
      "Lower potassium than red (~105 mg per glass); counts toward fluid, and alcohol raises hypo risk."),
    f(174815, "Spirits (gin, rum, vodka, whiskey), 80 proof", BEV, "1 jigger, 1.5 fl oz", 42, [FL, ALC],
      "No potassium or phosphorus, but alcohol on insulin can cause delayed lows; mix with diet or clear soda, not cola."),

    # --------------------------------------------------------- Sweets & Snacks
    f(167990, "Hard candy", SWEET, "3 pieces", 18, [HYPO, GI],
      "Pure sugar with no potassium or phosphorus: 3 pieces (~17 g carbs) is a renal-safe way to treat a low."),
    f(167991, "Jelly beans", SWEET, "15 small", 17, [HYPO, GI],
      "About 15 g fast carbs with no minerals; a renal-safe hypo treatment."),
    f(167989, "Gummy candy (gummy bears)", SWEET, "10 gummy bears", 22, [GI]),
    f(167995, "Marshmallows", SWEET, "4 regular", 29, [GI],
      "Low in potassium and phosphorus; a renal-diet friendly sweet, but ~24 g fast carbs."),
    f(167974, "Caramels", SWEET, "3 pieces", 30, [GI, PROC]),
    f(167587, "Milk chocolate bar", SWEET, "1 bar, 1.55 oz", 44, [GI, PROC],
      "Chocolate is high in potassium (~165 mg) and phosphorus (~90 mg) per bar; hard candy, marshmallows or a vanilla wafer are the swaps."),
    f(170273, "Dark chocolate, 70-85% cacao", SWEET, "1 oz", 28, [],
      "The darker the chocolate the more potassium (~200 mg per oz) and phosphorus; a small square is the limit."),
    f(168763, "Peanut butter cups", SWEET, "1 package, 1.6 oz, 2 cups", 45, [GI, PROC],
      "Chocolate plus peanuts: ~155 mg potassium and ~70 mg phosphorus; hard candy or a vanilla cookie is the swap."),
    f(172716, "Cookies, chocolate chip", SWEET, "2 cookies", 26, [GI, PROC],
      "Chocolate chips add potassium and phosphorus; sugar cookies, shortbread or vanilla wafers are the lower-mineral cookies."),
    f(172725, "Cookie, oatmeal", SWEET, "1 large cookie", 25, [GI, PROC]),
    f(174971, "Cookies, sugar", SWEET, "2 cookies", 34, [GI, PROC]),
    f(174974, "Vanilla wafers", SWEET, "8 wafers", 30, [GI, PROC]),
    f(174957, "Graham crackers", SWEET, "2 large rectangles", 28, [GI, PROC]),
    f(172718, "Cookies, chocolate sandwich (Oreo-type)", SWEET, "3 cookies", 36, [GI, PROC],
      "Cocoa plus phosphate leavening in many brands; a vanilla sandwich cookie or shortbread is the swap."),
    f(168014, "Animal crackers", SWEET, "1 box, 2 oz", 57, [GI, PROC]),
    f(174945, "Cake, yellow, with vanilla frosting", SWEET, "1 piece", 67, [GI, PA, PROC],
      "Commercial cake uses phosphate leavening and is ~38 g carbs a slice; angel food cake is the lower-phosphorus treat."),
    f(174934, "Cake, chocolate, with chocolate frosting", SWEET, "1 piece, 1/8 of 18 oz cake", 64, [GI, PA, PROC],
      "Chocolate cake stacks cocoa potassium on phosphate leavening; angel food or a plain yellow cake is the swap."),
    f(172694, "Cake, angel food", SWEET, "1 piece, 1/12 of cake", 28, [GI],
      "Egg-white cake with almost no fat, potassium or phosphorus: a favourite renal-diet dessert (still ~16 g carbs)."),
    f(172711, "Cheesecake", SWEET, "1 piece, 1/6 of 17 oz cake", 80, [PROC],
      "Cream cheese keeps potassium modest but it is ~75 mg phosphorus and ~350 mg sodium a slice and very rich; a small slice occasionally."),
    f(175011, "Pie, apple", SWEET, "1 piece, 1/8 of 9 in pie", 125, [GI, PROC],
      "Apple pie is one of the lower-potassium pies but ~40 g carbs a slice; skip pumpkin, pecan and chocolate pies."),
    f(172758, "Doughnut, glazed", SWEET, "1 doughnut", 75, [GI, PA, PROC],
      "Yeast doughnuts still use phosphate leavening and are fried; a plain cake slice or a sugar cookie is the swap."),
    f(172713, "Brownie", SWEET, "1 square, 2-3/4 in", 56, [GI, PROC],
      "Chocolate and often phosphate leavening; a blondie without chocolate chips or angel food cake is the swap."),
    f(167927, "Toaster pastry, frosted", SWEET, "1 pastry", 53, [GI, PA, PROC],
      "Frosted toaster pastries list sodium acid pyrophosphate and are 37 g carbs each; white toast with jam is the swap."),
    f(167575, "Ice cream, vanilla", SWEET, "1/2 cup", 66, [FL],
      "Dairy, so ~70 mg phosphorus and ~130 mg potassium per 1/2 cup; it melts to liquid, so it counts toward fluid."),
    f(168809, "Ice cream, chocolate", SWEET, "1/2 cup", 66, [FL],
      "Chocolate ice cream has about half again the potassium of vanilla; sherbet or vanilla is the swap, and it counts as fluid."),
    f(167577, "Sherbet, orange", SWEET, "1/2 cup", 74, [GI, FL],
      "Lower in phosphorus and potassium than ice cream, so the usual frozen-dessert swap; counts toward fluid."),
    f(168815, "Frozen yogurt, vanilla, soft-serve", SWEET, "1/2 cup", 72, [FL],
      "Dairy minerals similar to ice cream; counts toward fluid."),
    f(168813, "Popsicle (ice pop)", SWEET, "1 pop, 1.75 fl oz", 52, [GI, FL],
      "No minerals, but it is frozen sugar water: count it toward fluid and as ~11 g fast carbs."),
    f(168132, "Popsicle, sugar-free", SWEET, "1 pop, 1.75 fl oz", 55, [FL],
      "A good way to soothe thirst on a fluid limit, but it still counts as ~50 mL of fluid."),
    f(169596, "Gelatin dessert (Jell-O)", SWEET, "1/2 cup", 135, [GI, FL],
      "Low potassium and phosphorus, but it is a liquid at body temperature so it counts toward fluid, and ~19 g fast carbs."),
    f(169598, "Gelatin dessert, sugar-free", SWEET, "1/2 cup", 117, [FL],
      "A classic renal-diet snack with almost nothing in it; still counts toward a fluid limit."),
    f(169608, "Pudding, vanilla, ready-to-eat", SWEET, "1 container, 4 oz", 110, [GI, PA, PROC],
      "Shelf-stable pudding cups thicken with sodium/tetrasodium phosphate on top of milk phosphorus; sugar-free gelatin is the swap."),
    f(168778, "Pudding, chocolate, ready-to-eat", SWEET, "1 container, 4 oz", 108, [GI, PA, PROC],
      "Chocolate pudding cups add cocoa potassium to phosphate additives; sugar-free gelatin or a sherbet is the swap."),
    f(169640, "Honey", SWEET, "1 tbsp", 21, [HYPO, GI],
      "About 17 g fast carbs with negligible potassium: usable to treat a low."),
    f(169655, "Sugar, granulated", SWEET, "1 tbsp", 12.6, [HYPO, GI],
      "A tablespoon is ~13 g pure glucose/fructose with no minerals: a hypo treatment in a pinch."),
    f(168833, "Sugar, brown", SWEET, "1 tsp, packed", 4.6, [GI, ING]),
    f(169661, "Maple syrup", SWEET, "1 tbsp", 20, [GI],
      "Low in minerals but ~13 g sugar per tbsp; sugar-free syrup is the everyday swap."),
    f(168838, "Pancake syrup", SWEET, "1 tbsp", 20, [GI, PROC]),
    f(169641, "Jam or preserves", SWEET, "1 tbsp", 20, [GI]),
    f(169642, "Jelly", SWEET, "1 tbsp", 21, [GI]),
    f(170257, "Sweetener, sucralose packet (Splenda)", SWEET, "1 packet", 1, []),
    f(169677, "Potato chips, salted", SWEET, "1 oz, about 15 chips", 28, [PROC],
      "Potato chips are high in potassium (~350 mg per oz) and salt; unsalted popcorn, pretzels or rice cakes are the swaps."),
    f(167558, "Tortilla chips, salted", SWEET, "1 oz", 28, [PROC],
      "Lower potassium than potato chips but ~90 mg sodium per oz; unsalted popcorn is the swap."),
    f(167949, "Cheese puffs", SWEET, "1 oz", 28, [PA, PROC],
      "Cheese-powder snacks are salty and contain phosphate emulsifiers; unsalted popcorn is the swap."),
    f(167961, "Pork rinds", SWEET, "1 oz", 28, [PROC],
      "Very high sodium (~520 mg per oz); unsalted popcorn is the crunchy swap."),
    f(167959, "Popcorn, air-popped, unsalted", SWEET, "3 cups", 24, [],
      "The renal-diet snack: low potassium, phosphorus and sodium when unsalted."),
    f(167549, "Popcorn, microwave, regular", SWEET, "3 cups, popped", 33, [PROC],
      "Microwave bags add ~300 mg sodium and butter flavouring; air-popped is the swap."),
    f(167555, "Pretzels, hard, salted", SWEET, "1 oz", 28, [PROC],
      "Low potassium and phosphorus but ~350 mg sodium per oz; unsalted pretzels or rice cakes are the swap."),
    f(167542, "Granola bar, hard, plain", SWEET, "1 bar", 28, [PROC],
      "Oats and nuts make granola bars moderately high in phosphorus; a rice-cereal bar or vanilla wafers are lower."),
    f(167561, "Trail mix", SWEET, "1/4 cup", 38, [PROC],
      "Nuts plus dried fruit: ~260 mg potassium and ~130 mg phosphorus per 1/4 cup; unsalted popcorn or a few macadamias is the swap."),
    f(167540, "Fruit snacks (fruit leather)", SWEET, "1 package", 27, [GI, PROC],
      "Mostly sugar with little potassium: fast carbs that can treat a low, but not a fruit serving."),

    # ----------------------------------------------------- Condiments & Sauces
    f(173468, "Salt, table", COND, "1/4 tsp", 1.5, [ING],
      "A quarter teaspoon is ~580 mg sodium, over a quarter of a 2000 mg day; season with herbs, pepper, lemon, vinegar and garlic instead."),
    manual(1, "Salt substitute (potassium chloride, e.g. NoSalt, Nu-Salt)", COND, "1/4 tsp", 1.4,
           {"potassium_mg": 610},
           [AVOID],
           "AVOID with kidney disease: salt substitutes are potassium chloride, ~610 mg potassium per 1/4 tsp, and can push blood potassium to dangerous levels; use herbs, lemon or salt-free herb blends (check they are KCl-free)."),
    manual(2, "Lite salt (half sodium, half potassium chloride)", COND, "1/4 tsp", 1.4,
           {"sodium_mg": 290, "potassium_mg": 350},
           [AVOID],
           "AVOID with kidney disease: 'lite' salt is half potassium chloride (~350 mg potassium per 1/4 tsp) and still a quarter of the day's sodium; use herbs and spices."),
    f(172804, "Baking powder (phosphate type)", COND, "1 tsp", 4.6, [PA, ING],
      "Standard baking powder is sodium acid pyrophosphate or monocalcium phosphate: ~455 mg phosphorus (almost fully absorbed) and ~365 mg sodium per tsp, roughly 40-75 mg phosphorus per slice of a 12-serving cake; use a low-sodium, phosphate-free baking powder."),
    f(174277, "Soy sauce", COND, "1 tbsp", 16, [PROC],
      "~880 mg sodium in one tablespoon (almost half a day's limit); use a teaspoon, dilute with water, or try lemon and ginger."),
    f(172473, "Soy sauce, reduced sodium", COND, "1 tbsp", 14.2, [PROC],
      "'Reduced' still means ~530 mg sodium per tablespoon; measure with a teaspoon."),
    f(171167, "Teriyaki sauce", COND, "1 tbsp", 18, [GI, PROC],
      "~690 mg sodium per tablespoon plus sugar; make your own with a little reduced-sodium soy, garlic, ginger and pineapple juice."),
    f(171610, "Worcestershire sauce", COND, "1 tbsp", 17, [PROC],
      "Moderately salty (~220 mg sodium per tbsp) and made with anchovies and molasses (potassium); a splash is fine."),
    f(168556, "Ketchup", COND, "1 tbsp", 17, [GI, PROC],
      "~150 mg sodium and 4 g sugar per tbsp, plus tomato potassium; a tablespoon is fine, or use a low-sodium ketchup."),
    f(169381, "Ketchup, low sodium", COND, "1 tbsp", 17, [GI, PROC]),
    f(172234, "Mustard, yellow", COND, "1 tsp", 5, []),
    f(171009, "Mayonnaise", COND, "1 tbsp", 13.8, []),
    f(171826, "Tartar sauce", COND, "2 tbsp", 30, [PROC]),
    f(173592, "Ranch dressing", COND, "2 tbsp", 30, [PROC],
      "~260 mg sodium per 2 tbsp and many brands add disodium phosphate; oil and vinegar or lemon is the swap."),
    f(171019, "Italian dressing", COND, "2 tbsp", 29, [PROC],
      "Bottled Italian is ~290 mg sodium per 2 tbsp; mix your own with olive oil, vinegar, garlic and herbs."),
    f(169055, "Caesar dressing", COND, "2 tbsp", 30, [PROC],
      "Parmesan and anchovy make Caesar dressing salty (~360 mg per 2 tbsp); use half the amount or an oil-and-lemon dressing."),
    f(171413, "Olive oil", COND, "1 tbsp", 13.5, [ING]),
    f(172336, "Canola oil", COND, "1 tbsp", 14, [ING]),
    f(172346, "Margarine, stick", COND, "1 tbsp", 14, [PROC, ING]),
    f(173469, "Vinegar, cider", COND, "1 tbsp", 14.9, [ING]),
    f(172241, "Vinegar, balsamic", COND, "1 tbsp", 16, [ING]),
    f(167747, "Lemon juice, fresh", COND, "1 tbsp", 15.2, []),
    f(170931, "Black pepper, ground", COND, "1 tsp", 2.3, [ING]),
    f(174523, "Barbecue sauce", COND, "2 tbsp", 34, [GI, PROC],
      "~350 mg sodium and ~11 g sugar per 2 tbsp, with tomato potassium; a tablespoon brushed on is enough."),
    f(174524, "Salsa", COND, "2 tbsp", 36, [PROC],
      "Tomato-based with ~230 mg sodium per 2 tbsp; fresh pico de gallo without salt is the swap."),
    f(171192, "Marinara / spaghetti sauce, jarred", COND, "1/2 cup", 132, [PROC],
      "Tomato sauce is high in potassium (~400 mg per 1/2 cup) and sodium; use 1/4 cup, or a garlic-olive-oil or cream sauce."),
    f(171186, "Hot sauce, sriracha", COND, "1 tsp", 6.5, [PROC],
      "~140 mg sodium per teaspoon; fresh chilli or crushed red pepper is the salt-free heat."),
    f(171191, "Cheese sauce, ready-to-serve", COND, "1/4 cup", 63, [PA, PROC],
      "Jarred cheese sauce is built on sodium phosphate emulsifiers and salt; melt a little real cheddar into rice milk instead."),
    f(171564, "Gravy, beef, canned", COND, "1/4 cup", 58, [FL, PROC],
      "Canned gravy is ~330 mg sodium per 1/4 cup and, being liquid, counts toward a fluid limit; thicken your own pan juices with a little cornstarch."),
    f(168561, "Pickle relish, sweet", COND, "1 tbsp", 15, [GI, PROC],
      "~120 mg sodium and 4 g sugar per tbsp; a small spoonful is fine."),

    # ---------------------------------------------------- Prepared & Fast Food
    f(171609, "Chicken broth, low sodium, canned", PREP, "1 cup", 240, [FL, PROC],
      "A good base: ~70 mg sodium per cup versus ~860 mg in regular broth; counts toward fluid."),
    f(174557, "Beef broth / bouillon, prepared", PREP, "1 cup", 241, [FL, PROC],
      "Bouillon is salt in a cube (~640 mg sodium per cup); low-sodium broth is the swap, and it counts toward fluid."),
    f(172909, "Soup, chicken noodle, canned, prepared", PREP, "1 cup", 248, [FL, PROC],
      "Canned soup is ~850 mg sodium per cup and counts as fluid; make soup from low-sodium broth, rice and vegetables."),
    f(171176, "Soup, tomato, canned, prepared with water", PREP, "1 cup", 248, [FL, PROC],
      "Tomato soup is both high-potassium (~680 mg) and high-sodium (~460 mg) per cup; a low-sodium chicken-rice soup is the swap."),
    f(172915, "Soup, cream of mushroom, canned, prepared", PREP, "1 cup", 248, [FL, PROC],
      "~870 mg sodium per cup and phosphate stabilisers in many brands; a homemade cream soup with rice milk is the swap."),
    f(174565, "Soup, vegetable beef, canned, prepared", PREP, "1 cup", 244, [FL, PROC],
      "Canned vegetable soups run ~850 mg sodium per cup; homemade with low-sodium broth is the swap."),
    f(174564, "Soup, vegetarian vegetable, canned, prepared", PREP, "1 cup", 241, [FL, PROC],
      "~820 mg sodium and tomato potassium per cup; homemade with leached vegetables is the swap."),
    f(174062, "Clam chowder, New England, canned", PREP, "1 cup", 254, [FL, PROC],
      "~870 mg sodium, milk phosphorus and potato potassium per cup; a small bowl occasionally."),
    f(171549, "Soup, lentil with ham, canned", PREP, "1 cup", 248, [FL, PROC],
      "Lentils plus ham: ~1300 mg sodium and ~350 mg potassium per cup; a low-sodium chicken-rice soup is the swap."),
    f(171177, "Ramen noodles, instant, dry", PREP, "1 package", 81, [PA, PROC],
      "A packet is ~1500 mg sodium with phosphate-treated noodles; cook plain noodles or rice with low-sodium broth instead."),
    f(172097, "Chili con carne with beans, canned", PREP, "1 cup", 242, [PROC],
      "Beans, tomato and salt: ~1000 mg sodium and ~700 mg potassium per cup; homemade chili with fewer beans and no salt is the swap."),
    f(173325, "Macaroni and cheese, canned", PREP, "1 serving", 244, [PA, PROC],
      "Processed cheese sauce means sodium phosphate and ~740 mg sodium; pasta with a little real cheddar is the swap."),
    f(173341, "Macaroni and cheese, boxed mix, prepared", PREP, "1 cup", 198, [PA, PROC],
      "The cheese powder is sodium phosphate and salt (~700 mg); cook pasta and melt a slice of Swiss into rice milk instead."),
    f(173330, "Beef stew, canned", PREP, "1 cup", 196, [PROC],
      "Potatoes, carrots and salt: ~760 mg sodium and ~320 mg potassium per cup; homemade with leached potatoes is the swap."),
    f(170317, "Pizza, cheese, frozen", PREP, "1 slice, 1/9 of 24 oz pizza", 81, [PA, PROC],
      "Frozen pizza combines processed cheese, phosphate-leavened crust and ~360 mg sodium a slice; one slice on white crust with fresh mozzarella is the compromise."),
    f(172096, "Pizza, pepperoni, frozen", PREP, "1/4 of 12 in pizza", 127, [PA, PROC],
      "Pepperoni adds cured-meat sodium to the phosphate-leavened crust and processed cheese; a cheese or vegetable slice is better."),
    f(172114, "Lasagna with meat sauce, frozen", PREP, "1 piece", 255, [PROC],
      "Tomato, cheese and salt: ~900 mg sodium and ~500 mg potassium per piece; a smaller portion with a side salad."),
    f(173331, "Chicken pot pie, frozen", PREP, "1 pie", 302, [PA, PROC],
      "A frozen pot pie is ~1300 mg sodium and phosphate-leavened pastry; roast chicken with rice is the swap."),
    f(173339, "Rice bowl with chicken, frozen", PREP, "1 bowl", 340, [PROC],
      "Teriyaki- and sauce-based frozen bowls are ~1200 mg sodium; cook rice and chicken with a splash of reduced-sodium soy."),
    f(173336, "Burrito, bean and cheese, frozen", PREP, "1 burrito", 129, [PROC],
      "Beans, cheese and salt: ~450 mg sodium and ~270 mg potassium; a chicken-and-rice burrito on a corn tortilla is lower."),
    f(172103, "Egg roll, pork, heated", PREP, "1 roll", 85, [PROC],
      "~350 mg sodium per roll from soy sauce and the wrapper; one is plenty."),
    f(169269, "Potato salad, home-style", PREP, "1/2 cup", 125, [],
      "Potatoes, egg and salt: ~320 mg potassium and ~660 mg sodium per 1/2 cup; use leached potatoes or swap for a pasta or cabbage slaw salad."),
    f(170300, "Coleslaw, fast food", PREP, "3/4 cup", 116, [PROC],
      "Cabbage is renal-friendly, but fast-food slaw dressing adds ~250 mg sodium and sugar; homemade with vinegar is the swap.",
      role="veg_fruit"),
    f(170699, "Mashed potatoes, fast food", PREP, "1/2 cup", 121, [PROC],
      "Instant mashed potatoes with gravy: ~350 mg potassium and ~370 mg sodium per 1/2 cup; rice or a roll is the side swap."),
    f(170698, "French fries, fast food", PREP, "1 medium", 117, [PROC],
      "A medium fries is ~600 mg potassium and ~250 mg sodium; a small, or a side salad, is the compromise."),
    f(170697, "Onion rings, fast food", PREP, "1 order", 117, [PA, PROC],
      "Battered and salted (~900 mg sodium per order) with phosphate leavening in the coating; a side salad is the swap."),
    f(170693, "Hamburger, fast food, plain", PREP, "1 sandwich", 78, [PROC],
      "A plain small burger is the least-bad fast-food choice (~260 mg sodium); skip cheese and ketchup-heavy sauces."),
    f(170691, "Cheeseburger, fast food, with condiments", PREP, "1 sandwich", 127, [PA, PROC],
      "Processed cheese adds sodium phosphate and the bun, pickle and sauce push sodium to ~800 mg; order a plain hamburger instead."),
    f(170718, "Chicken nuggets, fast food", PREP, "6 pieces", 96, [PA, PROC],
      "Nuggets are brined with sodium phosphate and salted (~570 mg sodium per 6); a grilled chicken piece is the swap."),
    f(170756, "Fried chicken breast, fast food, with skin and breading", PREP, "3 oz", 85, [PA, PROC],
      "Fast-food fried chicken is phosphate-marinated and salty (~560 mg sodium per 3 oz); remove the skin and breading or choose grilled."),
    f(170295, "Chicken fillet sandwich, fast food", PREP, "1 sandwich", 187, [PA, PROC],
      "Breaded chicken sandwiches run ~1400 mg sodium with phosphate-brined chicken; a grilled chicken sandwich without pickles is lower."),
    f(170297, "Fish sandwich, fast food, with tartar and cheese", PREP, "1 sandwich", 134, [PA, PROC],
      "Breaded fish, processed cheese and tartar sauce: ~580 mg sodium; skip the cheese or choose grilled fish."),
    f(170689, "Taco, beef, hard shell, fast food", PREP, "1 taco", 69, [PROC],
      "Seasoned beef, cheese and the shell: ~275 mg sodium per taco; two is a meal, four is a sodium day."),
    f(172039, "Burrito, bean and cheese, fast food", PREP, "1 burrito", 185, [PROC],
      "Beans, cheese and a flour tortilla: ~1000 mg sodium and ~500 mg potassium; a chicken soft taco on corn is the swap."),
    f(170308, "Sub sandwich, turkey/roast beef/ham, 6 in", PREP, "1 six-inch sub", 207, [PA, PROC],
      "Deli meats are phosphate-injected and a 6 in sub is ~720 mg sodium and ~550 mg potassium; roast beef only, no cheese, and ask for less meat."),
    f(170291, "Nachos with cheese, fast food", PREP, "1 serving, 6-8 chips", 80, [PA, PROC],
      "Nacho cheese sauce is sodium phosphate and salt; plain tortilla chips with salsa is the swap."),
    f(172028, "Biscuit with egg and sausage, fast food", PREP, "1 sandwich", 162, [PA, PROC],
      "Phosphate-leavened biscuit plus sausage: ~1100 mg sodium; an egg on a plain English muffin is the swap."),
    f(172033, "English muffin with egg, cheese and Canadian bacon", PREP, "1 sandwich", 126, [PA, PROC],
      "Cured bacon and processed cheese add sodium phosphate (~800 mg sodium); ask for egg only on the muffin."),

    # ------------------------------------------------------- Diabetes supplies
    manual(10, "Glucose tablet (4 g carb)", T1D, "1 tablet", 4,
           {"calories_kcal": 16, "carbs_g": 4, "sugar_g": 4},
           [HYPO, GI],
           "Pure dextrose with no potassium, phosphorus or sodium: the ideal hypo treatment with kidney disease (rule of 15: 4 tablets = 16 g, recheck in 15 min)."),
    manual(11, "Glucose gel (15 g carb tube)", T1D, "1 tube", 38,
           {"calories_kcal": 60, "carbs_g": 15, "sugar_g": 15},
           [HYPO, GI],
           "One tube is a full 15 g hypo treatment with no potassium or phosphorus; keep one in every bag."),
    manual(12, "Glucose liquid shot (15 g carb, 2 fl oz)", T1D, "1 bottle, 2 fl oz", 59,
           {"calories_kcal": 60, "carbs_g": 15, "sugar_g": 15, "fluid_ml": 59},
           [HYPO, GI, FL],
           "A 15 g fast-acting dose with no minerals; the 59 mL counts toward a fluid limit, which is still far less than a glass of juice."),
]
